### ISSUE TITLE
ninja build stopped: subcommand failed. Error: Build failed

### ISSUE THREAD

**Issue by ashisham** [weiliu89/caffe#1006]
I am new to caffe and deep learning. I was trying to build the caffe and it is not going well. Below is the system architecture. There is an attached powershell log file. 
Operating system: Windows 10 Education 1903
Compiler:  cmake? ninja?
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 5.0
Python 3.5.xx

Help me getting out of it. 
Thanks in advance
[Issue regarding building.txt](https://github.com/weiliu89/caffe/files/3797566/Issue.regarding.building.txt)

**Comment by hattaaldino** [comment]
Have you solved this? @ashisham
