### ISSUE TITLE
The problem of regarding AlenNet as base network and the fps of ssd300 only reach 28

### ISSUE THREAD

**Issue by lcj1105** [weiliu89/caffe#101]
I use AlenNet as base net , But it works not satisfactory . There is two problem .

one is the conv4 of AlenNet only has 13 * 13 feature map relative to VGG has 38*38 feature map. it is smaller than the second feature map 19*19 .  what's your suggestion , delete this feature map road or modefy it to 38*38 .

 the last problem is the fps of ssd 300*300 only reach to 28 , The configuration of my computer is TitanX with cudNN5.1

**Comment by lcj1105** [comment]
ps:  I modefied the test_bach_size to 8

**Comment by John-HW-Cao** [comment]
First of all, the original AlexNet use a 224x224x3 image as an input and the ssd 300*300 uses a 300*300*3 as an input. So there would be no 13*13 feature map if the input size is enlarged.

Secondly, the low speed may be related to the structure of your base net. Usually, the last few layers of the AlexNet or other Nets should be removed before adding the new SSD-unique layers. On the other hand, if you use the ssd_pascal.py script to generate the new net, the extra layers you add to the base net may be inappropriate for the AlexNet. They performs well for the VGG base net, but may be not so well in your case. You can change their hyperparameters in the script.

**Comment by lcj1105** [comment]
@John-HW-Cao  Hi, Thank for your answer .  
First , use 300 * 300 as an input , the 13 * 13 feature map is more than 13 * 13 . But it still smaller than the 19 *19 feature map (with 300*300 input ,it world be bigger too) . In the paper , the feature map of conv4_3 is big than others feature map , so the parameter of  this default boxes is different with other feature (scale 0.1 aspect ratios 1/2 and 2) .  If regard AlenNet as base net , Does this parameter should be modefied ?

Secondly , the model I tested is SSD 300*300 with VGG16 , not AlexNet . So I am confused that it could not reached to 72 fps.  

By the way , this computer  belongs to laboratory... not private property.   ^_^

**Comment by John-HW-Cao** [comment]
@lcj1105 

1) Yes, this parameter can be modified. More importantly, I think you need change the parameters of conv6 conv7 and the following layers. You may also try to remove some of these layers after you understand what those layers are doing. Finally, the bottom line is that you should make sure the size of the feature map decreases monotonically. 

2) I only see 58 FPS on Pascal VOC2007 test in Table 5 in the original paper. There is no 72 fps.

**Comment by leejiajun** [comment]
@John-HW-Cao How can I get the fps of ssd.
