### ISSUE TITLE
Error while training RESNET101

### ISSUE THREAD

**Issue by kristellmarisse** [weiliu89/caffe#107]
I am trying to train my custom dataset with RESNET101. When I run the script  ssd_pascal_resnet.py, I am getting this error.

NameError: name 'ResNet101Body' is not defined.

**Comment by weiliu89** [comment]
Did you `git pull` the latest code? Did you set the correct PYTHONPATH?

**Comment by kristellmarisse** [comment]
Thanks. The problem is solved after I re-installed SSD.

**Comment by lxd7714059** [comment]
@weiliu89 @kristellmarisse 
I git clone the repo and checkout ssd, but when i run ssd_pascal_resnet.py, I meet the same error.
NameError: name 'ResNet101Body' is not defined.
Could you give me some instructions.
