### ISSUE TITLE
create lmdb problem

### ISSUE THREAD

**Issue by lebronyxm** [weiliu89/caffe#11]
Hi~ I try my data using SSD, and i want to train a 5 classes detector (my labels are defined as number 1-5). but it comes an error to me when using'./data/VOC0712/create_data.sh' to create lmdb. The error is In io.cpp line 285 : unknow name. Do i have to change my own labels to the VOC labels?

**Comment by weiliu89** [comment]
You should create a labelmap file for your own data using [this](https://github.com/weiliu89/caffe/blob/ssd/tools/create_label_map.cpp). And currently it only support annotation whose format is same as VOC or COCO. If not, you should write your own function to read the annotation. You can refer to [this function](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/util/io.cpp#L251).

**Comment by lebronyxm** [comment]
Thank you very much for your help! I really appreciate your work about SSD. Wish you a happy day~

**Comment by junxigauss** [comment]
I have created a labelmap file for my data like this:

item {
  name: "none_of_the_above"
  label: 0
  display_name: "background"
}
item {
  name: "plate"
  label: 1
  display_name: "plate"
}

but the unknow name always be there, Check failed: 'anno' Must be non NULL in io.cpp 321.
can you help me?Thanks......

**Comment by junxigauss** [comment]
@weiliu89 

I have created a labelmap file for my data like this:

item {
name: "none_of_the_above"
label: 0
display_name: "background"
}
item {
name: "plate"
label: 1
display_name: "plate"
}

but the unknow name always be there, Check failed: 'anno' Must be non NULL in io.cpp 321.
can you help me?Thanks......

**Comment by junxigauss** [comment]
@weiliu89 and My data format is VOC.

**Comment by junxigauss** [comment]
@weiliu89 是xml中的问题，name 必须在bndbox之前？这算是bug么？

**Comment by wliu-nuro** [comment]
Please follow the VOC format.

**Comment by weiliu89** [comment]
Please follow VOC format.

**Comment by junxigauss** [comment]
@weiliu89 在io.cpp的ReadXMLToAnnotatedDatum函数中要求name必须在bndbox之前，个人感觉不太合理，我修改了源码，目前没有问题了。

**Comment by Anhaoxu** [comment]
@weiliu89 @lebronyxm @junxigauss  Hello, I met a similar error, I use coco data and followed the instruction, my idea is simple, just delete some classes that I don't need, then every step seems right, but the lmdb file for train is error( there should be 4 lmdb file in coco, and the train and minival lmdb for me is wrong, but the test and testdev lmdb is right).  The wrong information is:
I0820 19:07:13.075296  7382 convert_annoset.cpp:122] A total of 118287 images.
I0820 19:07:13.075664  7382 db_lmdb.cpp:35] Opened lmdb /home/liu/data/coco/lmdb/coco_train_lmdb
F0820 19:07:13.136318  7382 io.cpp:393] Unknown name: 17
*** Check failure stack trace: ***
    @     0x7f4a3168f5cd  google::LogMessage::Fail()
    @     0x7f4a31691433  google::LogMessage::SendToLog()
    @     0x7f4a3168f15b  google::LogMessage::Flush()
    @     0x7f4a31691e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4a31cbf1d8  caffe::ReadJSONToAnnotatedDatum()
    @     0x7f4a31cbf5f1  caffe::ReadRichImageToAnnotatedDatum()
    @           0x407dba  main
    @     0x7f4a30607830  __libc_start_main
    @           0x4089d9  _start
    @              (nil)  (unknown)

**Comment by FoolishMao** [comment]
@Anhaoxu  have you solved this problem? may I know your solutions? Thanks!

**Comment by AllYoung** [comment]
@FoolishMao I have the same problem. After checking, I found that it was because the category in the xml file was wrong.
