### ISSUE TITLE
How to use this parameter( dilation=6 ) to inflation kernel?

### ISSUE THREAD

**Issue by zhenxing9968** [weiliu89/caffe#118]
Hi Wei, I read your SSD train.prototxt,find the fc6 layer has a parameter dilation=6
 And, i find the code in conv_layer.cpp is kernel_extent = dilation_data[i] \* (kernel_shape_data[i] - 1) + 1;
but I could not fully understand the shape of kernel_extent and the relationship between kernel_extent and original kernel,could you help me?  thanks

**Comment by weiliu89** [comment]
The original fc6 has an effective kernel size of 7 x 7. I have made two modifications:

- Subsample the parameters of fc6 so that it becomes 3 x 3
- Change pool5 from stride of 2 to stride of 1

Thus you need to set the dilation value accordingly.

**Comment by zhenxing9968** [comment]
What are the benefits of this strategy?
