### ISSUE TITLE
How  to use the ssd_detect.cpp to detect objects in a image

### ISSUE THREAD

**Issue by ZoneFv** [weiliu89/caffe#122]
I use g++ to compile the ssd_detect.cpp:
g++ ssd_detect.cpp -I /home/bo718.wang/src/caffe/include -I /usr/local/cuda-7.5/include -lpthread -lglog -lboost_system  -o ssd_detect
###  There is a problem:
/usr/bin/ld: /tmp/ccYgnc0y.o: undefined reference to symbol '_ZN6google15SetUsageMessageERKSs'
//usr/lib/x86_64-linux-gnu/libgflags.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status_

**Comment by weiliu89** [comment]
You should do `make -j8`. It will compile it automatically and can be found at build/examples/ssd/ssd_detect

**Comment by ZoneFv** [comment]
Thanks very much!
I found it in the  .build_release/examples/ssd/ssd_detect.bin

**Comment by zhohuiluo** [comment]
@weiliu89  I am sorry to brother you .I rewrite the ssd_detec.cpp.
how to make ? if make in /caffe-ssd/ again, it will spend a lot of time.
Shuld I just make in /caffe-ssd/examples/ssd/?  put the makefile in this fold?
could you tell me the details. I am new to linux and caffe .
I will appreciate for your hlep.
