### ISSUE TITLE
Bounding box exceeds image boundary , should I change my groundtruth?

### ISSUE THREAD

**Issue by ZoneFv** [weiliu89/caffe#126]
When I use the create_data.sh to create my datasets,it shows that "bounding box exceeds image boundary ".
Can I use this lmdb to train the SSD model?
Should I change my groundtruth, to adjust the bounding box inside the image boundary.

**Comment by weiliu89** [comment]
It is recommended to adjust your gt to make sure it is within the image boundary.

**Comment by ZoneFv** [comment]
How does this program to process the bounding box which is outside the image boundary? 
The program will ignore the box or will change it to adapt the boundary？
