### ISSUE TITLE
How do I test my own video with SSD?

### ISSUE THREAD

**Issue by CPFLAME** [weiliu89/caffe#13]
When I run python examples/ssd/ssd_pascal_webcam.py, I Failed to open webcam: 0.
  It seems that I need a webcam connnected to SSD,but how do I test a video with SSD named demo.mp4 that already exits in my 	directory？

**Comment by weiliu89** [comment]
You can modify the video_data_layer.cpp to read video file instead of webcam.

**Comment by CPFLAME** [comment]
Thanks a lot , I will try though it seems a little difficult for me.By the way,SSD is a wonderful project.

**Comment by Mudwall** [comment]
How can I test an image with caffemodel?
What does the 'net.blobs['detectionOutput']' with shape 1x1x200x7 mean?
How can I get the detection loacations and score?

**Comment by weiliu89** [comment]
@Mudwall, please refer to [here](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd_detect.ipynb) for how to use the model to test an image. The first element in each row is image_id in the batch, the rest is described in the link.

**Comment by weiliu89** [comment]
@CPFLAME @Mudwall You could use/modify [this code](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_detect.cpp) to test image/video using a SSD model.
