### ISSUE TITLE
What kinds of NV GPU cards can be used to do the training?

### ISSUE THREAD

**Issue by m5061125** [weiliu89/caffe#132]
Hi, Liuwei, I am new guy to DL filed, so pls forgive me if the question is to naive. I have a GTX660ti GPU card. And I got the following error when I try to do the training, so is this issure caused by the spec
of my GPU card. Would you pls give me a list that what kinds of GPU can be used to do the training, thanks a lot.

Best Regards
Chuanfeng

F0822 12:00:44.495167 28167 parallel.cpp:130] Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal
*** Check failure stack trace: ***
    @     0x7fdc5e14ddaa  (unknown)
    @     0x7fdc5e14dce4  (unknown)
    @     0x7fdc5e14d6e6  (unknown)
    @     0x7fdc5e150687  (unknown)
    @     0x7fdc5e801777  caffe::DevicePair::compute()
    @     0x7fdc5e80661c  caffe::P2PSync<>::Prepare()
    @     0x7fdc5e806b9c  caffe::P2PSync<>::Run()
    @           0x40838b  train()
    @           0x40612c  main
    @     0x7fdc5d45bf45  (unknown)
    @           0x406861  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by kristellmarisse** [comment]
How much memory does your card have?

**Comment by weiliu89** [comment]
The python script uses 4 GPUs to train by default. I guess you don't have 4 GPUs in your machine. Make sure you have the appropriate setting

**Comment by m5061125** [comment]
My GPU only have 2G memory, and now I get the following error message:
F0822 16:10:47.806375 28849 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7faeb014fdaa  (unknown)
    @     0x7faeb014fce4  (unknown)
    @     0x7faeb014f6e6  (unknown)
    @     0x7faeb0152687  (unknown)
    @     0x7faeb09ed2d1  caffe::SyncedMemory::to_gpu()
    @     0x7faeb09ec639  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7faeb07dc572  caffe::Blob<>::mutable_gpu_data()
    @     0x7faeb0a22b1f  caffe::CuDNNConvolutionLayer<>::Forward_gpu()
    @     0x7faeb080fb45  caffe::Net<>::ForwardFromTo()
    @     0x7faeb080feb7  caffe::Net<>::Forward()
    @     0x7faeb07fe6f8  caffe::Solver<>::Step()
    @     0x7faeb07fedfe  caffe::Solver<>::Solve()
    @           0x408848  train()
    @           0x40612c  main
    @     0x7faeaf45df45  (unknown)
    @           0x406861  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by zhenxing9968** [comment]
@m5061125 你的显存不够用啦

**Comment by m5061125** [comment]
@zhenxing9968, Thanks.
