### ISSUE TITLE
How to solver this question during test use coco dataset?

### ISSUE THREAD

**Issue by zhenxing9968** [weiliu89/caffe#136]
I0823 09:31:21.445153  3337 net.cpp:274] Network initialization done.
F0823 09:31:21.669708  3337 net.cpp:765] Cannot copy param 0 weights from layer 'conv4_3_norm_mbox_conf'; shape mismatch.  Source param shape is 243 512 3 3 (1119744); target param shape is 63 512 3 3 (290304). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
*** Check failure stack trace: ***
    @     0x7f2d156d9daa  (unknown)
    @     0x7f2d156d9ce4  (unknown)
    @     0x7f2d156d96e6  (unknown)
    @     0x7f2d156dc687  (unknown)
    @     0x7f2d15c90c77  caffe::Net<>::CopyTrainedLayersFrom()
    @     0x7f2d15c9b702  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f2d15c9b766  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x409baf  test()
    @           0x40855c  main
    @     0x7f2d141dcf45  (unknown)
    @           0x408d2d  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by weiliu89** [comment]
You are loading a wrong model. I am guessing you are loading a COCO model (81 classes) to fine-tuen on PASCAL dataset (21 classes). You have to "extract" the corresponding channels by yourself if you want to fine-tune a COCO model on PASCAL.

**Comment by weiliu89** [comment]
I was wrong. You should change your lmdb and parameters in score_ssd_pascal.py for COCO dataset.

**Comment by zhenxing9968** [comment]
thanks
