### ISSUE TITLE
problem about image size

### ISSUE THREAD

**Issue by lebronyxm** [weiliu89/caffe#14]
Sorry to bother you again. When i'm training the Net using 'examples/ssd/ssd_pascal.py', an error shows up. 

> I0630 12:04:19.019912 38219 caffe.cpp:209] Resuming from models/VGGNet/VOC0712/SSD_300x300/VGG_VOC0712_SSD_300x300_iter_60000.solverstate
F0630 12:04:19.292585 38219 net.cpp:765] Cannot copy param 0 weights from layer 'conv4_3_norm_mbox_conf'; shape mismatch.  Source param shape is 63 512 3 3 (290304); target param shape is 18 512 3 3 (82944). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.

this error always happens in a FC layer because of needing fixed length. But, why it happens here?

**Comment by lebronyxm** [comment]
I found the layer setting:

> layer {
  name: "data"
  type: "AnnotatedData"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }
  transform_param {
    mean_value: 104
    mean_value: 117
    mean_value: 123
    resize_param {
      prob: 1
      resize_mode: WARP
      height: 300
      width: 300
      interp_mode: LINEAR
    }
  }

so it can reshape the data into 300*300 in the net? To make my problem clearly: Should i reshape the images and bounding box locations information into 300*300 style BEFORE createing lmdb file?

**Comment by weiliu89** [comment]
You should change the "job_name" in the python script. I guess you are loading a pre-trained model I provided, which might not be the same (e.g. # of class) as what want.

**Comment by weiliu89** [comment]
The resize is done on the fly. The code will store the *original* image in
the AnnotatedDatum.

**Comment by lebronyxm** [comment]
Thank you for your elaborate answer! I have trained the SSD Net on my own data successfully~

**Comment by Anhaoxu** [comment]
@lebronyxm @weiliu89  This is because it used the wrong pre-trained model? I try to modify it, but I can't understand what you said clearly? Could you explain it for me ?Thank you!
