### ISSUE TITLE
ssd_detect.bin run error with boost::filesystem::create_directories: Permission denied: "/home/wliu/data/ILSVRC2015/results"

### ISSUE THREAD

**Issue by zhonhel** [weiliu89/caffe#140]
Hi weiliu,

I try to run the ssd_detect.bin in the build folder, but encountered a runtime error said this:

terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
what():  boost::filesystem::create_directories: Permission denied: "/home/wliu/data/ILSVRC2015/results"

how can this be solved? 
thank you very much : )

**Comment by youngwanLEE** [comment]
change your own path : /home/"yourPath"/data/~~

**Comment by zhonhel** [comment]
Hi youngwanLEE,
Thank you.
I have got root privilege to solve this problem.

**Comment by weiliu89** [comment]
The deploy.prototxt for ILSVRC model might include some path which should be deleted/modified.

**Comment by zhonhel** [comment]
Hi weiliu,

Thank you very much,
The problem is solved as you said : )
