### ISSUE TITLE
ssd_detect.bin run error with File not found: data/ilsvrc15/labelmap_ilsvrc_det.prototxt

### ISSUE THREAD

**Issue by zhonhel** [weiliu89/caffe#141]
Hi weiliu,

I try to run the ssd_detect.bin in the build folder, but encountered a runtime error said this:

Check failed: fd != -1 (-1 vs. -1) File not found: data/ilsvrc15/labelmap_ilsvrc_det.prototxt

I searched this file in the whole folder, and I found a file with same name under the folder "ilsvrc16", is there anything getting mismatched?

how can this be solved? 
thank you very much : )

**Comment by weiliu89** [comment]
The deploy.prototxt for ILSVRC model might include some path which should be deleted/modified.

**Comment by zhonhel** [comment]
Hi weiliu,

Thank you very much.
I changed the path in deploy.prototxt, and I used the file in ilsvrc2016, it worked.

But another issue occurred, it can't find val2_name_size.txt. And I can't find it in the whole folder.

How can this be solved?
Thank you!

**Comment by weiliu89** [comment]
Please run data/ILSVRC2016 for more details.

**Comment by zhonhel** [comment]
Hi weilliu,
Thank you very much,
I haven't noticed there is a readme in that folder : )
