### ISSUE TITLE
How to save the result of ssd_pascal_video.py ?

### ISSUE THREAD

**Issue by youngwanLEE** [weiliu89/caffe#143]
Hi, Wei. 

I want to save the result of ssd_pascal_video.py by video or image format.
Do you know how to save the result of ssd_pascal_video.py?

thanks

**Comment by weiliu89** [comment]
You can add some opencv code in [this function](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/util/bbox_util.cpp#L1131) to save the result either in video or image format.

**Comment by youngwanLEE** [comment]
oh thank you :)
