### ISSUE TITLE
Message during production: detection_output_layer.cu:123] Couldn't find any detections

### ISSUE THREAD

**Issue by abhisheksgumadi** [weiliu89/caffe#144]
Hi,

  When we pass images through the trained model we get messages like:

"I0825 13:51:56.862592 25317 detection_output_layer.cu:123] Couldn't find any detections"

How do we catch these messages? Does this happen because there is some error in the input image or because no detections have been found? If no detections have been found what would the output of the network "detections = net:forward(..) contain? Would it be null?

**Comment by yeongrok** [comment]
"Couldn't find any detection" message is printed when if detected nothing in the input image. 
In this case, detection output  has -1 value in label, score, xmin, ..., ymax

**Comment by abhisheksgumadi** [comment]
Thanks @yeongrok

**Comment by sunwooOh** [comment]
@abhisheksgumadi Did you solve the problem? I'm sure that I have the correct ground truth labels & images, but I get the same error message as you. How should I fix this? ;(
