### ISSUE TITLE
There is no gt for current image

### ISSUE THREAD

**Issue by yeongrok** [weiliu89/caffe#145]
Hello. 

Sorry but I have a question.  
In case there is no gt for current image, why empty vector is pushed into all_neg_indices??
Don't need to add top n negative boxes into all_neg_indices when do_neg_mining_ is on?

**In multibox_loss_layer**
  for (int i = 0; i < num_; ++i) {
    map<int, vector<int> > match_indices;
    vector<int> neg_indices;
    // Check if there is ground truth for current image.
    if (all_gt_bboxes.find(i) == all_gt_bboxes.end()) {
      // There is no gt for current image. All predictions are negative.
      all_match_indices_.push_back(match_indices);       
      all_neg_indices_.push_back(neg_indices);               <----- empty vector pushed
      continue;
    }
    .....
  }

**Comment by weiliu89** [comment]
Yes. Currently it doesn't sample negatives from images where there is no ground truth. Refer to #146 as well

**Comment by abhisheksgumadi** [comment]
@yeongrok did you manage to get the code working with the modifications for images that do not have any fround truth information? If yes can you please share the code modifications so I can try as well? What changes did you do to include images that should completely be treated as background that do not have any ground truth annotations please? 

@weiliu89 would really appreciate your thoughts on the code changes needed, please - Thanks

**Comment by yeongrok** [comment]
@abhisheksgumadi I've changed code like below to sample negatives from images even there is no ground truth. but I'm not sure it work correctly

In multibox_loss_layer
for (int i = 0; i < num_; ++i) {
map > match_indices;
vector neg_indices;
// Check if there is ground truth for current image.
if (all_gt_bboxes.find(i) == all_gt_bboxes.end()) { 
// There is no gt for current image. All predictions are negative.
 if (do_neg_mining_) {
        // Get max scores for all the non-matched priors.
        vector<pair<float, int> > scores_indices;
        int num_neg = 0;
        for (int m = 0; m < all_max_scores[i].size(); ++m) {
            scores_indices.push_back(std::make_pair(all_max_scores[i][m], m));
            ++num_neg;
        }
        // Pick top 5 num_neg negatives.
        num_neg = std::min(5, num_neg);
        std::sort(scores_indices.begin(), scores_indices.end(),
                  SortScorePairDescend<int>);
        for (int n = 0; n < num_neg; ++n) {
          neg_indices.push_back(scores_indices[n].second);
        }
        num_negs += num_neg;
      }
all_match_indices_.push_back(match_indices);
all_neg_indices_.push_back(neg_indices); 
continue;
}
.....
}

**Comment by gurkirt** [comment]
Hi Yeongrok,

Does your modification works for you?

Thanks
Gurkirt

**Comment by gurkirt** [comment]
@yeongrok  does it work?

**Comment by yeongrok** [comment]
@gurkirt Unfortunatly, the modification seems making some training error like Nan.
