### ISSUE TITLE
The dilation parameter in the convolution operation in fc6

### ISSUE THREAD

**Issue by 1292765944** [weiliu89/caffe#147]
Dear Wei Liu:
         I think the dilation parameter =5.
         The original receptive field in fc6 is 7*7*2
         the receptive field now in fc6 is 3*3*1
         so 7*2 /3 = 5 ? 
         I wonder how to get the dilation parameter 6? Thank you!

**Comment by weiliu89** [comment]
The original kernel size of (convolutional) fc6 is 7 x 7. Since I subsample and reduce it to 3 x 3, dilation should be 3. Besides, I also changed pool4 from stride of 2 to stride of 1, that is how it get to 6. (The default dilation is 1, not 0)

**Comment by 1292765944** [comment]
Thank you Wei Liu, I got it!
