### ISSUE TITLE
Training with custom base network

### ISSUE THREAD

**Issue by forever3000** [weiliu89/caffe#150]
Dear all,

I have a question related to base network. Currently, SSD frame work is based on reduce VGG network, so if I want to replace the base VGG with my own network how can I get the pre-trained model or just leave it blank in ssd_pascal.py script. 

Thanks.

**Comment by weiliu89** [comment]
You have to pretrain your own base network, and then plugin and replace VGGNet in ssd_pascal.py.

**Comment by forever3000** [comment]
Hi @weiliu89 ,

Thank for your answer, however can you guide me or give me a link that have instruction to pretrain my own base network.

Thanks

**Comment by weiliu89** [comment]
You could probably find more information from the official Caffe github page, or from many other websites :)

**Comment by forever3000** [comment]
Hi @weiliu89 
Thank, however when I tried to let the pretrain-model in ssd_pascal.py script as blank and train with my custom base network, the final result after 160k iterations is :  Test net output #0: detection_eval = 0.637057. This one mean mAP is : 63.7 % ??? May I dont use pretrain-model, the mAP will decrease?
Best Regards,

**Comment by weiliu89** [comment]
Of course. If you don't load a pretrain model, the performance is likely to be much worse. 63.7 is not bad considering that you are training a SSD model from scratch.

**Comment by forever3000** [comment]
Thanks, I got it :).
