### ISSUE TITLE
a failure while using create_data.sh 

### ISSUE THREAD

**Issue by wangha43** [weiliu89/caffe#152]
I am using create_data.sh,and a failure happened:
`F0830 15:36:05.484733  1279 io.cpp:288] Unknown name: upperbody`
the `upperbody` is just my detection aim, in XML file it is described as `<name>upperbody</name>`
how to make it run successfully,I truly do not  know what is the failure about.

**Comment by weiliu89** [comment]
You need to create your own labelmap.prototxt file.

**Comment by wangha43** [comment]
Yes,it is the labelmap_voc.prototxt file
