### ISSUE TITLE
Ground truth bbox when warp an image

### ISSUE THREAD

**Issue by UKeyboard** [weiliu89/caffe#160]
Hi @weiliu89 , I find that the ground truth bboxes are not adjusted when the image is warped to 300x300. This will cause gt_bboxes do not match the objects in the warped 300x30 image, which is then supposed to cause training issues, because the size of default boxes is relative to the warped image but that of gt_bboxes is relative to the original sampled image. Is it designed for any specific purpose? Or, it is just a mistake? Please check the [code](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/data_transformer.cpp#L455-L460
).

**Comment by SteveFame** [comment]
The gt_bboxes are normalized. I guess there is no need to resize them - the coordinates of the gt_bboxes are already given in percentage with respect to the image. Correct me if I'm wrong...

**Comment by nopattern** [comment]
I have the  question too .IThe normalized bboxes don't assure right result . I am trying to search codes to find whether I have missed something....

**Comment by UKeyboard** [comment]
Yes, they are normalized. I was lost in the normalized digital world... thanks
