### ISSUE TITLE
problem in parsenet

### ISSUE THREAD

**Issue by 1292765944** [weiliu89/caffe#164]
Dear Wei Liu:
     In your paper ParseNet, I'm confused about the fact that fc7 in FCN with VGG has a 404 × 404 pixels receptive field. However I get only 314*314 pixels totally. The calculation is as follows,
conv1_1: 3x3
conv1_2: 5x5
pool1: 10×10
conv2_1: 12×12
conv2_2: 14×14
pool2: 28×28
conv3_1: 30×30
conv3_2: 32×32
covv3_3: 34×34
pool3: 68×68
conv4_1: 70×70
conv4_2: 72×72
conv4_3: 74×74
pool4: 148× 148
conv5_1: 150×150
conv5_2: 152×152
conv5_3: 154×154
pool5: 308×308
after change fc6 to convolutional layer, its kernel size is 7×7. So the entire receptive field is 314×314. Can you tell me which step I get the wrong result? Thank you!

**Comment by weiliu89** [comment]
You could refer to Table 1 in [this paper](http://arxiv.org/pdf/1412.6631.pdf).

**Comment by 1292765944** [comment]
Thank you, I got it!
