### ISSUE TITLE
Train the Network on New Defined Classes

### ISSUE THREAD

**Issue by sangramioi** [weiliu89/caffe#17]
Dear Contributor,
1. Thanks for making this wonderful code available for general use.
2. I wanted to train on new set of classes and made my changes for the same in prototxt file in data folder and pascal_multilabel_datalayers file in examples/pycaffe/layers, but my training keeps on returning NaN and then on my test image no segmentation comes up.
3. Would be delighted if you could take some time out and help me with the same.

Thanks.

**Comment by weiliu89** [comment]
You should create a labelmap file for your own data using [this](https://github.com/weiliu89/caffe/blob/ssd/tools/create_label_map.cpp). And currently it only support annotation whose format is same as VOC or COCO. If not, you should write your own function to read the annotation. You can refer to [this function](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/util/io.cpp#L251). I would also strongly suggest using [this](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd.ipynb) to debug before you train on your own data.
