### ISSUE TITLE
Wierd error while running ssd_pascal.py

### ISSUE THREAD

**Issue by katariachirag1** [weiliu89/caffe#174]
I tried to follow the steps mentioned on Github.
I ran all the make statements and then downloaded datasets.

But when I run ssd_pascal.py I get the following error:-

*** Aborted at 1478798444 (unix time) try "date -d @1478798444" if you are using GNU date ***
PC: @     0x7fe917ad0e79 (unknown)
*** SIGSEGV (@0xffffffffffffffff) received by PID 21021 (TID 0x7fe9196f9a40) from PID 18446744073709551615; stack trace: ***
    @     0x7fe917472d40 (unknown)
    @     0x7fe917ad0e79 (unknown)
    @           0x40cc58 std::_Rb_tree<>::find()
    @           0x411698 caffe::SolverRegistry<>::CreateSolver()
    @           0x40ac66 train()
    @           0x406ed2 main
    @     0x7fe91745dec5 (unknown)
    @           0x407556 (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)

I added force_color: true in both training and testing parameters but the error continued.

Please Help,I am new to caffe and stuck.
Thanks

**Comment by weiliu89** [comment]
You might try to `make clean` and then make everything again.

**Comment by katariachirag1** [comment]
Thanks for the quick reply.That error was removed and now it is reading the lmdb file,but it again gives the following error-


I1110 23:56:54.883431 32040 db_lmdb.cpp:35] Opened lmdb examples/VOC0712/VOC0712_trainval_lmdb
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Aborted at 1478802414 (unix time) try "date -d @1478802414" if you are using GNU date ***
PC: @     0x7f07308d5cc9 (unknown)
*** SIGABRT (@0x3ee00007d23) received by PID 32035 (TID 0x7f070590e700) from PID 32035; stack trace: ***
    @     0x7f07308d5d40 (unknown)
    @     0x7f07308d5cc9 (unknown)
    @     0x7f07308d90d8 (unknown)
    @     0x7f0730eda535 (unknown)
    @     0x7f0730ed86d6 (unknown)
    @     0x7f0730ed8703 (unknown)
    @     0x7f0730ed8922 (unknown)
    @     0x7f0730ed8e0d (unknown)
    @     0x7f0730f34249 (unknown)
    @     0x7f0730f35971 (unknown)
    @     0x7f0730f35a2d (unknown)
    @     0x7f073214237a caffe::db::LMDBCursor::value()
    @     0x7f0731f9dcfd caffe::DataReader<>::Body::read_one()
    @     0x7f0731fa173c caffe::DataReader<>::Body::InternalThreadEntry()
    @     0x7f0731f8cdbf caffe::InternalThread::entry()
    @     0x7f07299f3a4a (unknown)
    @     0x7f07292ab182 start_thread
    @     0x7f073099947d (unknown)
    @                0x0 (unknown)
Aborted (core dumped)

**Comment by weiliu89** [comment]
Did you creat the lmdb file correctly? You can try to delete those and redo...

**Comment by katariachirag1** [comment]
Its working just fine!!!!!!!!!
Thanks a lot really.....you are such a help :)

**Comment by liuyiyiyiyi** [comment]
do you rebuild your lmdb file?

**Comment by buaacarzp** [comment]
> Did you creat the lmdb file correctly? You can try to delete those and redo...

hi,man,I like you , I try to make my own lmdb datasets and missing the same trouble when running the ssd_coco.py, I remake my lmdb file ,but it didn't work yet...
hopeing you have a nice day. dear liu.
