### ISSUE TITLE
Are SSD detections sensitive to rotation?

### ISSUE THREAD

**Issue by kristellmarisse** [weiliu89/caffe#180]
I am currently planning to train a custom dataset with SSD. In my dataset, the annotated objects are rotated in some images (around 2-5%). So in case if I want to detect rotated objects ( of same class as in training class ), is it ok if I train my dataset as it is or should I add more images to the dataset with rotations?

**Comment by weiliu89** [comment]
According to my experience, the network itself seems to learn some rotation. You could try to do data augmentation by rotation the training images (and adjusting bounding boxes).

**Comment by kristellmarisse** [comment]
Thank you !
