### ISSUE TITLE
ssd_pascal_video.py issue

### ISSUE THREAD

**Issue by youngwanLEE** [weiliu89/caffe#188]
Hi Wei,

recently, I updated CUDA 8.0, cuDNN v5, and OpenCV 3.1 for GTX 1080.

By the way, When I executed ssd_pascal_video.py, a error occurred. 

In the past, I succeeded to execute ssd_pascal_video.py normally on my TITAN X GPU. 

I0923 20:41:39.686223 15489 layer_factory.hpp:77] Creating layer data
I0923 20:41:39.686285 15489 net.cpp:100] Creating Layer data
I0923 20:41:39.686321 15489 net.cpp:408] data -> data
F0923 20:41:39.686467 15489 video_data_layer.cpp:51] Failed to open video: examples/videos/ILSVRC2015_train_00755001.mp4
*** Check failure stack trace: ***
    @     0x7fec3b278daa  (unknown)
    @     0x7fec3b278ce4  (unknown)
    @     0x7fec3b2786e6  (unknown)
    @     0x7fec3b27b687  (unknown)
    @     0x7fec3bb094c2  caffe::VideoDataLayer<>::DataLayerSetUp()
    @     0x7fec3ba7cc63  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7fec3bb53905  caffe::Net<>::Init()
    @     0x7fec3bb55862  caffe::Net<>::Net()
    @           0x4084bd  test()
    @           0x4067f8  main
    @     0x7fec3981ef45  (unknown)
    @           0x40705c  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

I searched VideoDataLayer and thought it was just video open problem.

Do you know what the problem is?

Thank you

**Comment by weiliu89** [comment]
I would do: 0) make clean and then make all things again. 1) Check if you have the video file. 2) Write a simple opencv ***.cpp file and see if you can read the video.

**Comment by Alex287** [comment]
@youngwanLEE It seems as if I met the same problem, how can you solver it.
