### ISSUE TITLE
Which cudnn version should I use?

### ISSUE THREAD

**Issue by sereph** [weiliu89/caffe#19]
Hi, @weiliu89 , I downloaded the code and changed to the ssd branch. But it can not make when I use cudnn v5 or v4.So I want to ask which cudnn version do the code support.Thanks.

**Comment by bcd33bcd** [comment]
I use CUDNNv4 ,and the code could run correctly.

**Comment by weiliu89** [comment]
If you want to use cuDNN5, you could merge the BVLC branch.
