### ISSUE TITLE
Purpose of object-level train/val/trainval files with '-1' in data/VOCdevkit/VOC2012/ImageSets/Main

### ISSUE THREAD

**Issue by aurotripathy** [weiliu89/caffe#197]
I'm coming up-to-speed on SSD to apply on my specific dataset. 

Can someone explain the purpose of the object-level train/val/trainval files with '-1'  content in `data/VOCdevkit/VOC2012/ImageSets/Main` folder.

For a given object class they seem to contain a _negative_ image (as far from the class as it can be)

Are they files used in SSD training process?

**Comment by liu09114** [comment]
The '-1' means the image denoted by the first number does not contain the object defined by the file name.

**Comment by aurotripathy** [comment]
@liu09114 Thank you. It this information used in the training process?

**Comment by weiliu89** [comment]
@aurotripathy no

**Comment by aurotripathy** [comment]
@liu09114 @weiliu89 Thank you for answering.
