### ISSUE TITLE
detection_eval varies dramatically

### ISSUE THREAD

**Issue by joshua19881228** [weiliu89/caffe#201]
Hi Wei Liu, thanks for your marvelous work. 

Recently I have trained a SSD detector using my own network structrue and data. The input size is 224x224 and the size of the featuremaps are 19x19, 10x10, 5x5, 3x3 and 1x1. As I trained the model, the detection_eval value varies dramtically. It climbed from about 0.10@iter100000 to about 0.46@iter150000, and then it drops to 0.32 even 0.15 at iter210000. Then it climbed back to about 0.47.

Have you ever expirenced such training process and do you have any suggestions about it? like the settings of min/max ratio, normalizations?

**Comment by weiliu89** [comment]
When I train on new dataset, I would first run ssd.ipynb to make sure the dataset/ground truth is correct. You could also try to plot the loss. Besides, what is the size of your test set?
