### ISSUE TITLE
No detect result in the output_result_dir/comp4_det_test_classename.txt

### ISSUE THREAD

**Issue by lebronyxm** [weiliu89/caffe#21]
I have trained the Net on my own data successfully. So i try to test the net using 'examples/ssd/score_ssd_pascal.py' , it runs without any error and output:

>I0704 16:32:17.817559  4196 blocking_queue.cpp:50] Data layer prefetch queue empty
I0704 16:32:21.424787  4196 solver.cpp:526]     Test net output #0: detection_eval = 0.936136
I0704 16:32:21.424835  4196 solver.cpp:325] Optimization Done.
I0704 16:32:21.424841  4196 caffe.cpp:222] Optimization Done.

In output_result_dir, i.e.,  "{}/data/VOCdevkit/results/VOC2007/{}_score/Main", there exists some output files which are like 'comp4_det_test_classename.txt'. But there are no words or other information in these txt files. I wonder why? (i check the files in " {}/data/VOCdevkit/results/VOC2007/{}/Main", and they do have results. I think they may be created in training stage not in test stage. )

**Comment by weiliu89** [comment]
Can you try to run the provided example/ssd/score_ssd_pascal.py and see if there are results saved in the output directory?

Make sure you have provided the valid output_directory, label_map_file, and name_size_file according to [here](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/layers/detection_output_layer.cpp#L48-L97).

Please let me know what you find.

BTW. The mAP looks very high. If you didn't mix testing images with training, then congratulations :)

**Comment by lebronyxm** [comment]
Actually, i have run the provided example/ssd/score_ssd_pascal.py successfully. And the results (txt files, which are blank) are saved. I'm sure i have provided valid output_directory, label_map_file, and name_size_file.  To make my confusion clearly: I have obtained the output files, but all those files are blank...

Thanks for your reminder about the mAP issue. my data is small, only have 5 classes object. And the number of test images is only 119, (training data num. is 1084). So this may be the reason why mAP is very high.

**Comment by weiliu89** [comment]
Ah, you should change [this line](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/score_ssd_pascal.py#L330) to:
`test_iter = math.ceil(float(num_test_image) / test_batch_size)`

or you could change test_batch_size to 1.

The reason is that 119 / 8 = 14, and it will never reach to [here](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/layers/detection_output_layer.cu#L195).

**Comment by lebronyxm** [comment]
Wow, thank god i have mentioned the number 119...Also, thank you very much for detailed help! I have done with this problem!

BTW, 

> test_iter = math.ceil(float(num_test_image) / test_batch_size)
should be added an int type transform or it will lead to an error about data type.

> test_iter = int(math.ceil(float(num_test_image) / test_batch_size))

Again, thank you for your help~

**Comment by weiliu89** [comment]
You are right. I updated the script and added a note to it. Thanks for pointing out the bug!
