### ISSUE TITLE
AttributeError: 'module' object has no attribute 'LabelMap'

### ISSUE THREAD

**Issue by tjpuzhaolei** [weiliu89/caffe#22]
the error following:
Traceback (most recent call last):
  File "/home/zhaolei/caffe/data/VOC0712/../../scripts/create_annoset.py", line 103, in <module>
    label_map = caffe_pb2.LabelMap()
AttributeError: 'module' object has no attribute 'LabelMap'

I want to create data,but i run the script ,it not has LabelMap()  function in caffe_pb2.  I have import caffe_pb2 file.

**Comment by weiliu89** [comment]
Please read README.md for details. You need to add the $CAFFE_ROOT/python in your PYTHONPATH

**Comment by tjpuzhaolei** [comment]
I add the $CAFFE_ROOT/python in my PYTHONPATH yet.. I have not found   the  LabelMap() function in caffe_pb2.

**Comment by weiliu89** [comment]
I am guessing you have other version of caffe. You should put the SSD python path at the beginning of PYTHONPATH. Otherwise, it will read your other version of caffe's python module first.

**Comment by tjpuzhaolei** [comment]
I don`t have other version of caffe .  caffe_pb2.py  has not LabelMap() function in the SSD python.   the caffe_pb2.py  is generate  at the during the installation process?  I try to uninstall and  reinstall .

**Comment by weiliu89** [comment]
Have you run `make py`?

**Comment by tjpuzhaolei** [comment]
I reinstall later success， thank you very much.
