### ISSUE TITLE
How to use ssd_detect.cpp 

### ISSUE THREAD

**Issue by duanLH** [weiliu89/caffe#220]
I want to know how to use the cpp file to detect the object. thanks~

**Comment by youngwanLEE** [comment]
You can figure out how to use it on top of the file [here](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_detect.cpp#1-#14)

**Comment by duanLH** [comment]
@youngwanLEE  At first, I need to know how to make,,,but I cant
