### ISSUE TITLE
how many default boxes on conv6, conv7

### ISSUE THREAD

**Issue by liangzimei** [weiliu89/caffe#226]
conv4_3 has 3 anchors(1 , 1/2 , 2), while conv6 has 6 anchors. I know (1 , 1/2 , 2, 1/3, 3 ) are five of them , but which is the last one ?

**Comment by liangzimei** [comment]
i find it.

**Comment by Walid-Ahmed** [comment]
Can you please explain what do you mean by anchor?
I am trying to  figure output how the final dimension is calculated.
