### ISSUE TITLE
regarding VGG16 base

### ISSUE THREAD

**Issue by williamjames1** [weiliu89/caffe#23]
Hi,
Can we use other base network than vgg16 which would be fast?
I want to run SSD @30 fps for 1080p video with GPU memory of 2.5 GB.

Thanks,
william.j.

**Comment by weiliu89** [comment]
Yes, you could. I have successfully trained with Inception v3 and ResNet 101, but it will involve some parameter tuning for a specific network architecture (esp. with network using batch normalization).

**Comment by williamjames1** [comment]
Hi,
Thanks. Can SSD run @30 fps for 1080p video, with 2.5 GB  GPU memory? I have to use SSD.
Have you tested it for 1080p video or 720p video?

Thanks,
william.j.

**Comment by weiliu89** [comment]
With current setting, no.

For 720p video, it needs about 10x more computation than 300 x 300. You could probably get similar performance by resizing the 720p video to 300 x 300 to train and test without losing much accuracy. In the example/ssd/ssd_pascal_webcam.py demo, I did resize the 720p video to 300 x 300. It is about 6FPS on TX1. There are potential ways to further speed up, but it involves many engineering efforts. For example:

- You can try much faster base network. Currently 88% of the time is spent on getting through VGG16 base.

- Do [DeepCompression](https://arxiv.org/abs/1510.00149).

- Wait until researchers can train [binary network](http://arxiv.org/abs/1603.05279) to work as good as float version of network.

- Wait 2 years when NVIDIA release more powerful embedded GPU or when there are some other novel hardware platforms (10x faster).
