### ISSUE TITLE
CUDA 8 - /usr/include/boost/property_tree/detail/json_parser_read.hpp:257:264: error: ‘type name’ declared as function returning an array 

### ISSUE THREAD

**Issue by plsilva** [weiliu89/caffe#237]
I was installing caffe on my machine (with a M60) I installed cuda 8. The cuda 8 installation went well. When I did the command (make -j8) on caffe directory I got error:

> /usr/include/boost/property_tree/detail/json_parser_read.hpp: In constructor ‘boost::property_tree::json_parser::json_grammar<Ptree>::definition<Scanner>::definition(const boost::property_tree::json_parser::json_grammar<Ptree>&)’:
/usr/include/boost/property_tree/detail/json_parser_read.hpp:257:264: error: ‘type name’ declared as function returning an array
                 escape

> /usr/include/boost/property_tree/detail/json_parser_read.hpp:257:264: error: ‘type name’ declared as function returning an array
> make: *** [.build_release/cuda/src/caffe/layers/detection_output_layer.o] Error 1
> make: *** Waiting for unfinished jobs..

What am I doing wrong? Someone can help me?

# EDIT
The problem was that to make caffe with CUDA 8 it is necessary a 5.3 or 5.4 GCC version.
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test`
`sudo apt-get update`
`sudo apt-get install gcc-5 g++-5`
`sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5`

**Comment by northeastsquare** [comment]
Finally, the solution to this problem:

upgrade the boost minimum version to 1.60
upgrade the g++ version to 5.4
comment the 257 line code in "json_parser_read.hpp", as the below:
                /*escape
                    =   chset_p(detail::widen<Str>("\"\\/bfnrt").c_str())
                            [typename Context::a_escape(self.c)]
                    |   'u' >> uint_parser<unsigned long, 16, 4, 4>()
                            [typename Context::a_unicode(self.c)]
                    ;*/

https://github.com/weiliu89/caffe/issues/54
