### ISSUE TITLE
How to evaluate models trained on ILSVRC2015？

### ISSUE THREAD

**Issue by leejiajun** [weiliu89/caffe#24]
it seems that this project do not provide the code of evaluating.

**Comment by weiliu89** [comment]
You could refer to [here](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd_detect.ipynb) on how to load a model and evaluate it. Or you could modify example/ssd/score_ssd_pascal.py to evaluate the model on ILSVRC.

**Comment by weiliu89** [comment]
@leejiajun You could modify [this code](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_detect.cpp) to evaluate models trained on ILSVRC.

**Comment by leejiajun** [comment]
@weiliu89 Thank you.
