### ISSUE TITLE
How to compute the location loss of negative examples in the training?

### ISSUE THREAD

**Issue by yw155** [weiliu89/caffe#240]
Hi, @weiliu89,
I have a question that how to calculate the location loss of negative examples. I know how to deal with the confidence loss of negative examples. But regarding the location loss, I have no idea.

**Comment by weiliu89** [comment]
There is no location loss for negative sample. You can ask yourself such question: what is the ground truth box for negative examples?

**Comment by yw155** [comment]
I am not familiar with this procedure. Thank you for your answer.
