### ISSUE TITLE
F1028 19:21:41.199019 10033 math_functions.cpp:250] Check failed: a <= b (1 vs. 1)  *** Check failure stack trace: *** Aborted (core dumped)

### ISSUE THREAD

**Issue by sxl2016** [weiliu89/caffe#246]
When I using the command python ./examples/ssd/ssd_pascal.py.
It failed.
I1028 19:21:40.995893 10027 layer_factory.hpp:77] Creating layer relu3_2
I1028 19:21:40.995914 10027 net.cpp:100] Creating Layer relu3_2
I1028 19:21:40.995929 10027 net.cpp:434] relu3_2 <- conv3_2
I1028 19:21:40.995944 10027 net.cpp:395] relu3_2 -> conv3_2 (in-place)
I1028 19:21:40.995971 10027 net.cpp:150] Setting up relu3_2
I1028 19:21:40.995986 10027 net.cpp:157] Top shape: 8 256 75 75 (11520000)
I1028 19:21:40.995996 10027 net.cpp:165] Memory required for data: 1428480032
I1028 19:21:40.996007 10027 layer_factory.hpp:77] Creating layer conv3_3
I1028 19:21:40.996037 10027 net.cpp:100] Creating Layer conv3_3
I1028 19:21:40.996048 10027 net.cpp:434] conv3_3 <- conv3_2
I1028 19:21:40.996208 10027 net.cpp:408] conv3_3 -> conv3_3
F1028 19:21:41.199019 10033 math_functions.cpp:250] Check failed: a <= b (1 vs. 1) 
**\* Check failure stack trace: ***
Aborted (core dumped)

What should I do to solve this problem? I use VM to run ubuntu14.04. And changed solver mode to CPU.
Thanks a lot.

**Comment by weiliu89** [comment]
What BLAS are you using? I used OpenBlas and it seems working well. I think it might due to some float precision issue.

**Comment by sxl2016** [comment]
I use apt-get to install OpenBLAS and the version is 0.2.8.

**Comment by sxl2016** [comment]
I use apt-get to install OpenBLAS and the version is 0.2.8.

**Comment by chenxistephen** [comment]
I have the same issue. It works well training on Titan X, but failed on K40c, so I assume it's due to precision problem. I'm trying to change the float to double to see.

**Comment by sxl2016** [comment]
Thanks for all your helps. I change a computer. It can run well.

**Comment by July0zhu** [comment]
@weiliu89 I have the same issue,too. I use  OpenBLAS.0.2.14.1 and GTX 1070.I wonder if the problem can be solved with something ways?

**Comment by Mycenae** [comment]
@weiliu89 I have the same issue, too. I tried ATLAS and OpenBLAS and got the same problem. Can you give some other possible ways to solve this problem? I have stuck on it for days.
