### ISSUE TITLE
When object aspect ratio is close to [8, 1/8] in ground-truth,  can it deal with it well when I use the default settings in train.prototxt?

### ISSUE THREAD

**Issue by wangzhenhua2015** [weiliu89/caffe#249]
Is the default aspect ratio [2,0.5] target for the object or the object togeth with background?
If I changed it to [8, 1/8], will the candidate boxes become much more and the computation be more expensive?
It is expected that about 1/10 images will contain the thin and long objects.

**Comment by weiliu89** [comment]
Default box are used to regress to object.

If you just change the default box's aspect ratio, it shouldn't be more computational expensive. But you have to make sure the new default boxes are within the receptive field of each layer where you add them.
