### ISSUE TITLE
VOC0712 SSD500 eval too low?

### ISSUE THREAD

**Issue by yanxp** [weiliu89/caffe#251]
I test the model VOC0712_SSD500*500_iter_60000.caffemodel you provied,but I only get detection_eval=0.3766,far from 0.75,why is that ? thank you!

**Comment by weiliu89** [comment]
Are you modifying score_ssd_pascal.py for evaluation? You have to make sure everything is set correctly. For example, you can check if the deploy.pbtxt file generated by you is same as the one provided.

**Comment by yanxp** [comment]
yes,I download the model SSD500 *500 provided that contains the deploy.prototxt and caffemodel, and I modifying the score_ssd_pascal.py resize_width=500,resize_heigth=500.I train with only one GPU.Is there questions? I can't get the 0.75 .Now I am training the model with VOC0712 SSD500*500,and want to see the detection_eavl ,wish a good result. Thank you.
