### ISSUE TITLE
Any plans to add caffenet or alexnet for net creation in python script?

### ISSUE THREAD

**Issue by wangzhenhua2015** [weiliu89/caffe#252]
When I manually generate Alexnet prototxt, I found it is not easy for me to adjust the net parameters. 

In my researching, my number classes is 2.

But obviously only changing num_classes from 21 to 2 does not work. 

I checked the python/caffe/model_libs.py, found some other net parameters depend on num_classes to create in function CreateMultiBoxHead. 

@weiliu89 Could you guid me to correct the train proto file (uploaded as train.txt)?

many thanks

FYI

[train.txt](https://github.com/weiliu89/caffe/files/564120/train.txt)

**Comment by 123chengbo** [comment]
if you want to train on your own net， i suggest you do not use the python scripts。
use this：
./xx/xx/caffe train --solver=/xx/xx/xx_solver.prototxt --weight=xxxxxx
you need to write your own solver.prototxt、train.prototxt and test.prototxt(you can imitate weiliu's prototxt files)

**Comment by sunwooOh** [comment]
I've been training two-class(single, without background) detection ssd net, and in my case, changing the num_classes parameter and putting the right lmdb files, and rearranging the paths worked.
I didn't write anything to model_libs.py, and I didn't change [solver, train, test, deploy].prototxt either.
Hope it helps.
