### ISSUE TITLE
Regarding the scale of feature map

### ISSUE THREAD

**Issue by yw155** [weiliu89/caffe#254]
Hi, @weiliu89 ,
In the experiments, I see the difference of the scales between 'conv4_3' and 'conv5_1'. However, the scales I computed are very huge, their maximum values achieve the magnitude of 1e+7. I use VGG-16 model with input size of 300*300. Is it the problem of input images? I just minus the mean values of three channels. Is it need to scale the pixel values of input images to [0, 1]?

**Comment by weiliu89** [comment]
Are you saying the scale of conv4_3 and conv5_1 in the SSD300 model is very large (1e+7)? I haven't examined that. We do not need to scale the pixel to [0, 1]. We only need to subtract the mean values, which means the input image data is roughly within [-128, 128].

**Comment by yw155** [comment]
Yes, the scales of feature maps conv4_3 and conv5_1 are very large. I would like to observe the difference of the scale as mentioned in the SSD and ParseNet papers. If the scale of conv5_1 is not near to 20, do I need to scale the feature map conv4_3 to actual scale of conv5_1 and then learning it?

**Comment by weiliu89** [comment]
I see the scale is normal. You can set `debug_info` to `True` in `score_ssd_pascal.py` and check the scale. Here is what I get, which seems normal.

I1104 10:02:08.779794  2789 net.cpp:608]     [Forward] Layer conv4_3, top blob conv4_3 data: **178.506**
I1104 10:02:08.779896  2789 net.cpp:620]     [Forward] Layer conv4_3, param blob 0 data: 0.00650575
I1104 10:02:08.779947  2789 net.cpp:620]     [Forward] Layer conv4_3, param blob 1 data: 0.0570087
I1104 10:02:08.780369  2789 net.cpp:608]     [Forward] Layer relu4_3, top blob conv4_3 data: 8.6429
I1104 10:02:08.780527  2789 net.cpp:608]     [Forward] Layer conv4_3_relu4_3_0_split, top blob conv4_3_relu4_3_0_split_0 data: 8.6429
I1104 10:02:08.780680  2789 net.cpp:608]     [Forward] Layer conv4_3_relu4_3_0_split, top blob conv4_3_relu4_3_0_split_1 data: 8.6429
I1104 10:02:08.780928  2789 net.cpp:608]     [Forward] Layer pool4, top blob pool4 data: 18.0123
I1104 10:02:08.783884  2789 net.cpp:608]     [Forward] Layer conv5_1, top blob conv5_1 data: **80.8344**
I1104 10:02:08.783982  2789 net.cpp:620]     [Forward] Layer conv5_1, param blob 0 data: 0.00698734
I1104 10:02:08.784034  2789 net.cpp:620]     [Forward] Layer conv5_1, param blob 1 data: 0.10859
I1104 10:02:08.784178  2789 net.cpp:608]     [Forward] Layer relu5_1, top blob conv5_1 data: 8.53096

**Comment by yw155** [comment]
I find that my computation has some problem. Now I get the same results. Thank you very much.

**Comment by knowledgaction** [comment]
sdfsd
