### ISSUE TITLE
GPU is out of memory after 190K iterations

### ISSUE THREAD

**Issue by KienHuynh** [weiliu89/caffe#256]
Hello, @weiliu89 
I was training SSD300 on a subset of VOC2012 and a few hundreds samples from my own dataset (~2500 images in total). Due to my low-capacity GPU, I can only train with a batch size of 2.
Everything was fine until it hit the 190K mark (I set max_ite = 300K). After it saved a snapshot of iteration190K (I set snapshot to 5K), the GPU suddenly went out of memory, I tried reducing the batch_size to 1 but it still got an out of memory error. This is weird because it was fine for 190K iterations.
If there was something wrong to happen, it should happen the first time the training iterated over the dataset. I don't know where it went wrong.
Thanks in advance.

**Comment by KienHuynh** [comment]
To clarify, this did not happen for the first time. There was the same error after a few thousand iterations in my previous training section. I'm just not sure if this is a caffe error or not.
My solution is to switch the training mode to CPU for a few iterations, then switch back to GPU and the error would be gone.

**Comment by weiliu89** [comment]
You could disable the testing during training.

**Comment by youngwanLEE** [comment]
@weiliu89 Let me know the influence of testing during training?

Thanks in advance

**Comment by weiliu89** [comment]
@youngwanLEE If you do testing during training, the test net will occupy some of the GPU memory. So if the GPU has limited memory, probably it is good idea to keep the test batch size small or even not doing any testing. However, if GPU memory is not an issue, I like to do testing during training so that I have a good sense of how the network performance changes through time.

**Comment by youngwanLEE** [comment]
@weiliu89 thanks :)

**Comment by KienHuynh** [comment]
@weiliu89 Thank you. I actually set test_interval=190K. It took a few days to reach 190K so I completely forgot about it.
Silly me.

**Comment by Liampingfang** [comment]
@weiliu89  so how to disable the testing during training.   Thanks.
