### ISSUE TITLE
Separating new layers into separate directory

### ISSUE THREAD

**Issue by ptuls** [weiliu89/caffe#257]
Hi Wei Liu,

Thanks for sharing the code. My question is (hopefully) simple: I'd like to keep my Caffe source the same as the original source from BVLC. However, to use SSD, I'd have to ensure some new layers you've added are present as well.

Is it possible to place your layers in a separate directory and then performs linking? Or is this not possible and the layers have to be integrated into Caffe? 

May I also know what are the new layers you have introducted (e.g. permute)? Thanks!

**Comment by weiliu89** [comment]
The SSD branch is almost sync with the BVLC master caffe branch. Can you just merge it to your branch?

There are couple of standalone layers, such as NormalizationLayer, PermuteLayer, DetectionOutputLayer, MultiBoxLossLayer, which could be taken out. The later two layers uses some of the utility functions defined in src/caffe/util/

There are two other layers which are mingled together with caffe's other code. One is AnnotatedDataLayer which is very similar to DataLayer and uses DataReader in Caffe. Another one is the DetectionEvaluateLayer whose outputs are consumed by the solver.cpp to compute mAP. As you can see, one is input, and the other is output (in inference).

Maybe I miss others, but these are probably the major changes.

**Comment by ptuls** [comment]
Thanks for that! I'll give it a go, and ask questions when appropriate. Cheers.
