### ISSUE TITLE
what's the  VGG_ILSVRC_16_layers_fc_reduced.caffemodel ?

### ISSUE THREAD

**Issue by Sundrops** [weiliu89/caffe#258]
Hi Wei Liu,

Thanks for sharing the code. Is models_VGGNet_VOC0712_SSD_300x300.caffemode based on VGG_ILSVRC_16_layers_fc_reduced.caffemodel by VOC2007 and VOC2012 dataset ? Thanks a lot

**Comment by weiliu89** [comment]
I did net surgery on original VGG16 net by converting fc6 and fc7 from fully connected layer to convolutional layer, and subsample the parameters from them, following what DeepLab did. All released SSD models are built on top of the reduced VGGNet.

**Comment by shawn-tian** [comment]
@weiliu89 the filters are down sampled from 4096 to 1024, is it randomly selected? The kernel size of fc6 is changed from 6*6 to 3*3, how did you down sample the filters here? Thank you

**Comment by Sundrops** [comment]
@weiliu89 thanks a lot !

**Comment by zxDeepDiver** [comment]
@weiliu89 @shawn-tian I also get into this problem when converting other models into fully convolutional networks. Could you tell us how you down sample the filters? Thank you.
