### ISSUE TITLE
Loading SSD in C++

### ISSUE THREAD

**Issue by jricheimer** [weiliu89/caffe#26]
I've been using the SSD model in python scripts, and it works great and always gives consistent results. But when I try doing the same thing in C++ with Caffe::Net<float>::Forward(), the results are inconsistent; i.e. for the exact same input I get different outputs each time I forward pass. Is there an obvious reason for this?

**Comment by weiliu89** [comment]
Can you be more specific? The python script only creates the .prototxt files and bash script in job/ and model/ directory. Eventually it calls the C++ binary to do training and testing.

If you want to evaluate a model you trained, you can refer to [here](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd_detect.ipynb). If you are doing training, and if you have batch_sampler in your train.prototxt, it will be different each time because it randomly samples a patch from a training image every time.

**Comment by jricheimer** [comment]
Thanks for responding. Let me elaborate:

I downloaded the pretrained model from your website, and followed the ssd_detect.ipynb instructions to use it. Then I tried to do pretty much the same thing as what is done in ssd_detect.ipynb, but in C++, and that is where it's failing to give consistent results.

**Comment by weiliu89** [comment]
What do the results look like? How significant is the difference?

**Comment by jricheimer** [comment]
Using the fish-bike image example, the net output is always of shape (1, 1, 200, 7), but the values are always different at each forward pass. From one pass to the next , they're not wildly different; maybe slightly different bounding box sizes and confidence values. It starts off like this:

![46888510](https://cloud.githubusercontent.com/assets/5607334/16635645/32ea819e-4388-11e6-9cd9-45dfd22a0729.jpg)

And after a few more passes through, it gets this: 

![95508362](https://cloud.githubusercontent.com/assets/5607334/16635683/50ec7738-4388-11e6-9890-2a534d99f43f.jpg)

A few more, then this:

![1702073885](https://cloud.githubusercontent.com/assets/5607334/16635709/6d225eae-4388-11e6-956b-be87ccb61b65.jpg)

(two bicycle detections and a person detection)

Then eventually this:

![817817436](https://cloud.githubusercontent.com/assets/5607334/16635737/8c4389f2-4388-11e6-9199-6700e0350fc0.jpg)

(Three person detections and a bicycle detection.)

And it continues to deteriorate. The deterioration is worse on other images that I've tested. (Often it begins to detect false positives with confidence > 0.9 after a few passes.)

What is interesting is that the sequence of outputs tends to be consistent. That is, when I first load the model, it gives me y0 for the first output, then y1 at the next forward pass, etc. And if I reload the model again, it will give me y0 again, then y1, etc.

I've checked my input data. Each time it's identical. Perhaps you have an idea about what might be going on.

**Comment by weiliu89** [comment]
I am guessing you had some bug in your code. I quickly wrote a [demo code](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_detect.cpp), you can check it out. The results seems to be consistent with the .ipynb demo code. The results are consistent no matter how many forward() iterations I run over the same image.

**Comment by Mudwall** [comment]
@jricheimer @weiliu89 I run into the same problem:I transplant SSD to caffe of windows version and I input the 'fish-bike.jpg' and the output is 1x1x200x7,the output form is the same as output of python of ubuntu:the first is the 0,the second is the label...but the confidence is different and any of them is less than 0.6~ ,the others seem ok~

**Comment by zhangyunming** [comment]
@Mudwall  hi，i also test ssd use c++ @weiliu89 on windows,but on my GTx970,it is about 3-4s to process an image, maybe somewhere have a issue.

**Comment by jricheimer** [comment]
@weiliu89 Thank you for looking into this. My code is almost exactly the same as yours. This is very strange. I will have to figure out what's going wrong.

**Comment by jricheimer** [comment]
For those interested, this turned out to be a bug in the version of Intel MKL with which I was compiling caffe. Updating MKL fixed the problem.

**Comment by Mudwall** [comment]
@zhangyunming Your results are correct?
