### ISSUE TITLE
Download the VGG_ILSVRC_16_layers_fc_reduced.caffemodel  Failed on github？

### ISSUE THREAD

**Issue by changss** [weiliu89/caffe#263]
Hi,liu wei
             I‘m in Beijing, and interested with SSD, but  I can't download VGG_ILSVRC_16_layers_fc_reduced.caffemodel on github,could you give me 
Baidu cloud link about VGG_ILSVRC_16_layers_fc_reduced.caffemodel? Thanks a  lot!

**Comment by Sundrops** [comment]
Maybe I can help you.Please leave your email here.

**Comment by changss** [comment]
my email: chang-ss@qq.com, thanks!

**Comment by chenghaozheng** [comment]
please help me too. Email: zch.512@163.com

**Comment by HansonSun** [comment]
please help me too. Email: hansonsun@hust.edu.cn

**Comment by Sundrops** [comment]
link: https://pan.baidu.com/s/1slOZrU9 
pwd: 5tju

**Comment by pythonkerry** [comment]
thanks a lot.
