### ISSUE TITLE
Use ssd_pascal_webcam.py without GPU.Only CPU

### ISSUE THREAD

**Issue by NikishinRoman** [weiliu89/caffe#266]
I gathered from Caffe CPU_ONLY:=1 flag. 
When I run the example( ssd_pascal_webcam.py), you get an error:
I1108 12:16:37.138124  1074 caffe.cpp:217] Using GPUs 0
F1108 12:16:37.138396  1074 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
    @     0x7fc6a6340daa  (unknown)
    @     0x7fc6a6340ce4  (unknown)
    @     0x7fc6a63406e6  (unknown)
    @     0x7fc6a6343687  (unknown)
    @     0x7fc6a676f8b0  caffe::Caffe::SetDevice()
    @           0x408723  train()
    @           0x405fdc  main
    @     0x7fc6a5339f45  (unknown)
    @           0x40684b  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

 Can I run the example ssd_pascal_webcam.py?

**Comment by abdallah95** [comment]
set solver_mode in the ssd_pascal_video.py to P.Solver.CPU

**Comment by NikishinRoman** [comment]
Thanks.
it worked
