### ISSUE TITLE
How to prepare VGG_VOC0712_SSD_300x300.sh for webcam Demo

### ISSUE THREAD

**Issue by JianbinTang** [weiliu89/caffe#269]
Hi, 

When I tried to run the webcam demo, here is the error I've got:

>python examples/ssd/ssd_pascal_webcam.py
jobs/VGGNet/VOC0712/SSD_300x300_webcam/VGG_VOC0712_SSD_300x300.sh: 2: jobs/VGGNet/VOC0712/SSD_300x300_webcam/VGG_VOC0712_SSD_300x300.sh: ./build/tools/caffe: not found

May I know how to generate VGG_VOC0712_SSD_300x300.sh? I've only found one under jobs/VGGNet/VOC712/SSD_300x300, which I think it was generated during the training.

Thank you!

**Comment by chienyiwang** [comment]
"VGG_VOC0712_SSD_300x300.sh" file will be generated automatically in the code. 
It seems like your program could not find caffe in your system path. 
One of the possible solutions is to include $CAFFE_ROOT/python to your PYTHONPATH.
(Add "export PYTHONPATH=$CAFFE_ROOT/python:$PYTHONPATH" in your .bashrc file)

**Comment by JianbinTang** [comment]
Thanks very much Chienyi! Yes, it is because it didn't find caffe.  In my case, I've actually compiled caffe and setup the correct python path. But one weird thing is somehow the caffe was under ./tools, not ./build/tools. I made a symbolic link and at least this issue is gone.
