### ISSUE TITLE
Out memory error

### ISSUE THREAD

**Issue by NikishinRoman** [weiliu89/caffe#271]
Good day! I'm a newbie.
When I run ssd_pascal_webcam.py  on GPU (NVIDEA QUADRA 600 - 1gb) I get the error:
F1109 18:20:40.511134 28312 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7fb7d7b40daa  (unknown)
    @     0x7fb7d7b40ce4  (unknown)
    @     0x7fb7d7b406e6  (unknown)
    @     0x7fb7d7b43687  (unknown)
    @     0x7fb7d820a201  caffe::SyncedMemory::to_gpu()
    @     0x7fb7d8209569  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7fb7d820b382  caffe::Blob<>::mutable_gpu_data()
    @     0x7fb7d8274ef8  caffe::BaseConvolutionLayer<>::forward_gpu_gemm()
    @     0x7fb7d83eec16  caffe::ConvolutionLayer<>::Forward_gpu()
    @     0x7fb7d81d7b25  caffe::Net<>::ForwardFromTo()
    @     0x7fb7d81d7e97  caffe::Net<>::Forward()
    @           0x407a72  test()
    @           0x40627c  main
    @     0x7fb7d6b29f45  (unknown)
    @           0x406aeb  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

Can someone point what's the reason for this error?

**Comment by NikishinRoman** [comment]
I put the card Quadra k4000 - example started. 1 gb of memory is not enough. I Got 5-6 fps

**Comment by jtara1** [comment]
What did you do to solve this? I've got a GTX 970 (4 GB memory), and I'm running `ssd_pascal_orig.py` and getting the out of memory error.

**Comment by NikishinRoman** [comment]
@jtara1  I  replaced the QUADRO 600 video card with QUADRO to 4000
