### ISSUE TITLE
How to calculate AP and mAP using voc2007_test datasets?(mAP in the author's article)

### ISSUE THREAD

**Issue by samylee** [weiliu89/caffe#278]
Hi guys,
How to calculate AP and mAP using voc2007_test datasets?(mAP in the author's article)
Any suggestions would be of great help to me.
Thanks!!!

Samylee

**Comment by yw155** [comment]
You can download VOC2007 dataset and see the 'devkit_doc.pdf'. There is an detailed explanation.

**Comment by samylee** [comment]
Thanks! @yw155
