### ISSUE TITLE
AttributeError: 'module' object has no attribute 'LabelMap'

### ISSUE THREAD

**Issue by lcj1105** [weiliu89/caffe#28]
$ ./data/VOC0712/create_data.sh 
Traceback (most recent call last):
  File "/home/chuanjun/Documents/caffe/data/VOC0712/../../scripts/create_annoset.py", line 103, in <module>
    label_map = caffe_pb2.LabelMap()
AttributeError: 'module' object has no attribute 'LabelMap'
Traceback (most recent call last):
  File "/home/chuanjun/Documents/caffe/data/VOC0712/../../scripts/create_annoset.py", line 103, in <module>
    label_map = caffe_pb2.LabelMap()
AttributeError: 'module' object has no attribute 'LabelMap'

**Comment by lcj1105** [comment]
$ ./data/VOC0712/create_list.sh 
no problem 
but when I used $ ./data/VOC0712/create_data.sh  ,it failed.

**Comment by SteveFame** [comment]
Is your python path including the right directory? Make sure it points to the SSD branch of Caffe and not some other version you have installed on your system. 

For example: "export PYTHONPATH=/path/to/CaffeSSD/python:$PYTHONPATH".

**Comment by lcj1105** [comment]
Thanks, I have solved this problem by modify the PYTHONPATH
