### ISSUE TITLE
About set multiple scales of default boxes on one feature map

### ISSUE THREAD

**Issue by yw155** [weiliu89/caffe#283]
Hi, @weiliu89 ,
I noticed that SSD adds more layers on the basis of VGG16 and assign one scale of default boxes for each feature map. Is it possible to set multiple scales of default boxes on one feature map to increase the coverage of groundtruth. Do you have suggestions on this problem?

**Comment by weiliu89** [comment]
@yw155 It can be achieved by changing the priorbox layer to generate multiple scales of priorboxes on a layer. I will provide an updated code for that later.

**Comment by yw155** [comment]
Thank you very much!
