### ISSUE TITLE
Sometimes I'm getting mbox_loss =0 during training. Is there any problem with that?

### ISSUE THREAD

**Issue by abdallah95** [weiliu89/caffe#285]

**Comment by weiliu89** [comment]
It happens when there are no ground truth boxes in a batch.

**Comment by rremani** [comment]
@weiliu89  Is it also true for loss? I got both loss and mbox loss 0 from the first iteration. I had only two classes.
Thanks

**Comment by abdallah95** [comment]
no it's not. follow weiliu instructions on how to train on a new dataset. Check if you are doing labeling correctly, that's most probably why you have loss 0.

**Comment by Jilliansea** [comment]
@rremani have you deal with the problem? I meet the same problem?
