### ISSUE TITLE
Unable to make caffe-ssd

### ISSUE THREAD

**Issue by theflybat** [weiliu89/caffe#29]
Hi there.

The original caffe (1.0.0-rc3) building process run without any problem.
I'm unable to build caffe-ssd and get the following error:

[ 60%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/log_layer.cpp.o
In file included from /home/caffe-ssd/Downloads/caffe/include/caffe/common.hpp:19:0,
                 from /home/caffe-ssd/Downloads/caffe/include/caffe/blob.hpp:8,
                 from /home/caffe-ssd/Downloads/caffe/include/caffe/layers/multibox_loss_layer.hpp:8,
                 from /home/caffe-ssd/Downloads/caffe/src/caffe/layers/multibox_loss_layer.cpp:6:
/home/caffe-ssd/Downloads/caffe/include/caffe/util/device_alternate.hpp:15:36: error: no ‘void caffe::MultiBoxLossLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’ member function declared in class ‘caffe::MultiBoxLossLayer<Dtype>’
     const vector<Blob<Dtype>*>& top) { NO_GPU; } \
                                    ^
/home/caffe-ssd/Downloads/caffe/src/caffe/layers/multibox_loss_layer.cpp:574:1: note: in expansion of macro ‘STUB_GPU’
 STUB_GPU(MultiBoxLossLayer);
 ^
/home/caffe-ssd/Downloads/caffe/include/caffe/util/device_alternate.hpp:19:39: error: no ‘void caffe::MultiBoxLossLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&)’ member function declared in class ‘caffe::MultiBoxLossLayer<Dtype>’
     const vector<Blob<Dtype>*>& bottom) { NO_GPU; } \
                                       ^
/home/caffe-ssd/Downloads/caffe/src/caffe/layers/multibox_loss_layer.cpp:574:1: note: in expansion of macro ‘STUB_GPU’
 STUB_GPU(MultiBoxLossLayer);
 ^
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/multibox_loss_layer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

**Comment by weiliu89** [comment]
I am guessing you are building a "CPU_ONLY" version. I have fixed the problem. You can pull the update and build again.

**Comment by theflybat** [comment]
Thanks, now all is working like a charm!
