### ISSUE TITLE
Dockerfile points to BVLC Caffe and not SSD

### ISSUE THREAD

**Issue by siddharthm83** [weiliu89/caffe#292]
In `https://github.com/weiliu89/caffe/blob/ssd/docker/standalone/gpu/Dockerfile`:

`RUN git clone -b ${CLONE_TAG} --depth 1 https://github.com/BVLC/caffe.git . && \
    for req in $(cat python/requirements.txt) pydot; do pip install $req; done && \
    mkdir build && cd build && \
    cmake -DUSE_CUDNN=1 .. && \
    make -j"$(nproc)"`

@weiliu89 : I noticed that your docker files don't point to the SSD repo. I was wondering if this was by choice?

**Comment by weiliu89** [comment]
@siddharthm83 I didn't change the docker file. You need to modify it if you want to install ssd with docker.

**Comment by siddharthm83** [comment]
Thanks. will do.

**Comment by liangdashuang** [comment]
I think you should replace "https://github.com/BVLC/caffe.git" in Dockerfile with "https://github.com/weiliu89/caffe.git"
