### ISSUE TITLE
Mininum size of the detected objects

### ISSUE THREAD

**Issue by gdomin** [weiliu89/caffe#297]
For the default setup of SSD using VGG 300x300 using VOC0712, what's the minimum size of an object in order to be detected by the algorithm? 

I have some preliminary results that indicate that for objects whose largest size (i.e., width or height depending on the aspect ratio) lower than 50 the probability of detection abruptly decreases as the largest size decreases as well. Does it make sense?

If one needs to detect smaller objects than that, is there any way of doing it in addition to reducing the size of the prior boxes?

**Comment by weiliu89** [comment]
@gdomin Figure 4 in the paper shows that it does not do well for small objects. I think it is a common problem for any detection methods. A 50x50 object may only have 5-6 pixels on conv4_3 (i.e. 8x reduction in resolution).

To detect smaller objects better, besides what you mentioned, you could increase input image size or increase feature map size.

**Comment by gdomin** [comment]
Thank you very much for your answer. That was also my reasoning, however I wanted to check that I was not missing anything.
