### ISSUE TITLE
what does DecodeBBoxes() do?

### ISSUE THREAD

**Issue by ByoenghakYim** [weiliu89/caffe#298]
Hi, again.

I'm wondering what DecodeBBoxes() do.

I can see prior_bboxes from GetPriorBBoxes() and all_loc_preds from GetLocPredictions() are same if share_location is TURE.

And It does some caculation with  prior_bboxes and all_loc_preds but I have no idea what it exactly does.

That function isn't executed with your default code but I would like to know what "use_prior_for_matching_" parameter means and what happens when "use_prior_for_matching_" is FALSE.

It will be appreciated if you could explain what DecodeBBoxes() performs.

Thanks.

**Comment by weiliu89** [comment]
@ByoenghakYim The network predict the offsets (i.e. all_loc_preds) to the prior boxes. DecodeBBoxes() apply these offsets to the prior boxes.

**Comment by ByoenghakYim** [comment]
you mean that the network predict gives only offset, not exact location, right?

thanks a lot.

**Comment by AresGao** [comment]
yes
