### ISSUE TITLE
./data/VOC0712/create_data.sh   does not exist: /home/yunquan/data/VOCdevkit/VOCdevkit_person/Annotations/000001.xml

### ISSUE THREAD

**Issue by lcj1105** [weiliu89/caffe#30]
./data/VOC0712/create_data.sh 
 does not exist: /home/yunquan/data/VOCdevkit/VOCdevkit_person/Annotations/000001.xml
 does not exist: /home/yunquan/data/VOCdevkit/VOCdevkit_person/Annotations/000003.xml

I referenced http://blog.csdn.net/sinat_30071459/article/details/51332084  to create my own dataset , And I modifyed /home/XXX/caffe/data/VOC0712/trainval.txt  、test.txt and test_name_size.txt  . when I used ./data/VOC0712/create_data.sh ,it failed. I promise 000001.xml and 000003.xml is existed.

**Comment by tumitx** [comment]
check out the trainval.txt created by create_list.sh, maybe there's something wrong such as '\n\r'

**Comment by lcj1105** [comment]
[trainval_new.txt](https://github.com/weiliu89/caffe/files/356753/trainval_new.txt)
[trainval.txt](https://github.com/weiliu89/caffe/files/356748/trainval.txt)

@tumitx  I created the txt file by my own python file , not the create_list.sh 

I'd be grateful  If you can help me check the trainval.txt

**Comment by tumitx** [comment]
It seems no problem about trainval_new.txt, you could check the params such as data_root_dir in create_data.sh.

By the way, you'd better shuffle your data before training.
