### ISSUE TITLE
Any tutorial video/slides available for SSD?

### ISSUE THREAD

**Issue by aurotripathy** [weiliu89/caffe#306]
@weiliu89 Kindly post links for videos to tutorials for SSD.
 
It would be fantastic if slides/video tutorial were available like those  available for the R-CNN.

http://mp7.watson.ibm.com/ICCV2015/slides/iccv2015_tutorial_convolutional_feature_maps_kaiminghe.pdf
http://mp7.watson.ibm.com/ICCV2015/slides/iccv15_tutorial_training_rbg.pdf

**Comment by weiliu89** [comment]
Not sure if this would help:

http://www.cs.unc.edu/~wliu/papers/ssd_eccv2016_slide.pdf

http://www.cs.unc.edu/~wliu/papers/ssd_eccv2016_slide.key

**Comment by aurotripathy** [comment]
@weiliu89 Thank you for releasing the keynote slides. I loved them. The [slides](http://www.cs.unc.edu/~wliu/papers/ssd_eccv2016_slide.key) in conjunction with the [paper](https://arxiv.org/abs/1512.02325) (and the code of course) are invaluable.
