### ISSUE TITLE
How is average precision calculated for object detection when num_classes=1

### ISSUE THREAD

**Issue by abhisheksgumadi** [weiliu89/caffe#309]
Hi,

  I was able to run score_ssd_pascal.py for my test data and get an output like follows:

    `Test net output #0: detection_eval = 0.599566`

which I believe is the average precision for the single class I am detecting. However, I have specific questions:

1. How is this calculated? I understand average precision is the area under the precision-recall curve which is plotted for various values of precision and recall. What parameter is varied to get these different values of precision and recall? Aren't we varying the confidence threshold on the output bounding boxes  and then calculate the recall and precision for various different threshold values on the confidence? If yes, where is the confidence value varied because in the code itself there is a setting that asks for confidence threshold as

    `det_out_param{... 'confidence_threshold': 0.5, ...}`

2. If my understanding of the above setting is wrong, can someone explain how is the precision recall curve generated for the single class object detection?

Thanks

**Comment by abhisheksgumadi** [comment]
Hi,

  Just wanted to add another question related to above. In the process of calculating the average precision for the single class detection, how can I have background images in the test data? I want to have images that are completely background and do not have the object inside it. 

Would the score_ssd_pascal.py allow me to do that?

**Comment by weiliu89** [comment]
Please read the VOCdevkit document on how mAP is computed.

`confidence_threshold` is used to filter out detection results whose score is lower than that. Please check caffe.proto for some explanation of the parameter.

**Comment by abhisheksgumadi** [comment]
Thanks @weiliu89 I was able to the get the required information,

**Comment by XhqGlorry11** [comment]
@abhisheksgumadi  Hi，I have run into the exact same questions as yours. Could you give me some explanation because I haven't figure it out. Where is the VOCdevkit document?
