### ISSUE TITLE
AttributeError: 'module' object has no attribute 'LabelMap'

### ISSUE THREAD

**Issue by NIEYALI** [weiliu89/caffe#311]
Hello Weiliu, when I run file 'create_data.sh' I meet a problem, which shows
"scripts/create_annoset.py", line 103, in <module>
    label_map = caffe_pb2.LabelMap()
AttributeError: 'module' object has no attribute 'LabelMap'"
Do you have any idea about the problem?
Thanks a lot

**Comment by weiliu89** [comment]
Check the README.md. You should add the $CAFFE_ROOT/python to your PYTHONPATH

**Comment by NIEYALI** [comment]
Thanks a lot ,it works
