### ISSUE TITLE
Pretrained model not working with commit 5365d0d

### ISSUE THREAD

**Issue by caiqi** [weiliu89/caffe#314]
`F1129 01:28:56.545753 12057 net.cpp:774] Cannot copy param 0 weights from layer 'conv4_3_norm_mbox_loc'; shape mismatch.  Source param shape is 12 512 3 3 (55296); target param shape is 16 512 3 3 (73728). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.`

After merging the commit 5365d0dccacd18e65f10e840eab28eb65ce0cda7 , run python examples/ssd/score_ssd_pascal.py will cause this error. It seems that the pretrained model does not fit the new prototxt. @weiliu89  Will you release new pretrained model? Thanks.

**Comment by weiliu89** [comment]
@caiqi Sorry. The new models are now released.

**Comment by caiqi** [comment]
Thank you!
