### ISSUE TITLE
Why different number of default bboexs in different layers?

### ISSUE THREAD

**Issue by wk910930** [weiliu89/caffe#316]
Dear Wei,

From section 3.1 in your [paper](https://arxiv.org/abs/1512.02325), 
> For conv4_3, conv10_2 and conv11_2, we only associate 4 default boxes at each feature map location – omitting aspect ratios of 1/3 and 3.

I am curious about why just use 4 default bboxes instead of 6 as in other feature maps. It seems no harm to use 6 default bboxes, right? Or did I miss something?

Thanks!

**Comment by weiliu89** [comment]
conv4_3 is much larger than other layers, using 4 on conv4_3 is to avoid having too many default bboxes

**Comment by wk910930** [comment]
Thanks! Closing the issue.
