### ISSUE TITLE
How to use this parameter(NonMaximumSuppressionParameter)in ssd_detect.cpp?

### ISSUE THREAD

**Issue by zhenxing9968** [weiliu89/caffe#318]
@weiliu89 ,when i use ssd_detect.cpp to test image,I found that there were two overlapping phenomena.
how to solve it?

**Comment by weiliu89** [comment]
You should understand how non-maximum suppression works.

**Comment by zhenxing9968** [comment]
got it. ths

**Comment by leimao** [comment]
Where is the "ssd_detect.cpp" file?
