### ISSUE TITLE
errors run ssd_pascal.py 

### ISSUE THREAD

**Issue by stonycat** [weiliu89/caffe#320]
Operating system:Ubuntu 16.04LTS
Compiler:gcc 5.4.0
CUDA version (if applicable):CUDA 8.0
CUDNN version (if applicable):v5.1
BLAS:openblas
Python or MATLAB version (for pycaffe and matcaffe respectively):Python

I met some errors when I run ssd_paccal.py, code like these:  (I have changed    gpus="0")
I1201 20:24:47.244240 12449 net.cpp:165] Memory required for data: 276480320
I1201 20:24:47.244247 12449 layer_factory.hpp:77] Creating layer conv1_1
I1201 20:24:47.244273 12449 net.cpp:100] Creating Layer conv1_1
I1201 20:24:47.244282 12449 net.cpp:434] conv1_1 <- data_data_0_split_0
I1201 20:24:47.244290 12449 net.cpp:408] conv1_1 -> conv1_1
*** Aborted at 1480595087 (unix time) try "date -d @1480595087" if you are using GNU date ***
PC: @     0x7f6065df32b3 (unknown)
*** SIGSEGV (@0x58) received by PID 12449 (TID 0x7f60fb5bd700) from PID 88; stack trace: ***
    @     0x7f6130b0d4b0 (unknown)
    @     0x7f6065df32b3 (unknown)
    @     0x7f60663ec3ad (unknown)
    @     0x7f6065df6854 (unknown)
    @     0x7f6065df7f1a (unknown)
    @     0x7f6065dee84c __cuda_CallJitEntryPoint
    @     0x7f6101b05562 fatBinaryCtl_Compile
    @     0x7f60fa33b392 (unknown)
    @     0x7f60fa33bf13 (unknown)
    @     0x7f60fa33c5e3 (unknown)
    @     0x7f60fa2367c7 (unknown)
    @     0x7f60fa23706d (unknown)
    @     0x7f60fa235fed (unknown)
    @     0x7f61285218d9 (anonymous namespace)::opencl_fn6<>::switch_fn()
    @     0x7f612859f9b9 cv::ocl::Context::getDefault()
    @     0x7f61285a109b cv::ocl::Device::getDefault()
    @     0x7f61285a10fd cv::ocl::useOpenCL()
    @     0x7f6127405d49 cv::cvtColor()
    @     0x7f6132c675dc caffe::AdjustHue()
    @     0x7f6132c6be1b caffe::RandomHue()
    @     0x7f6132c6cb14 caffe::ApplyDistort()
    @     0x7f6132ba2522 caffe::DataTransformer<>::DistortImage()
    @     0x7f6132af3f16 caffe::AnnotatedDataLayer<>::load_batch()
    @     0x7f6132b5547f caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7f6132bee9a5 caffe::InternalThread::entry()
    @     0x7f6126a7d5d5 (unknown)
    @     0x7f612076670a start_thread
    @     0x7f6130bde82d clone
    @                0x0 (unknown)
Segmentation fault (core dumped)

@weiliu89 Thanks for your SSD, and could you tell me what's the reason of it ?

**Comment by weiliu89** [comment]
What OpenCV version are you using? If you are using OpenCV-3.1.0, you could recompile it without OpenCL option (e.g. `-DWITH_OPENCL=OFF`)

**Comment by stonycat** [comment]
OpenCV3.0.0. Thank you for your reply, I will have a try.

**Comment by roipony** [comment]
I having the same problem. 
@stonycat have you solved the issue ?
Thanks

**Comment by stonycat** [comment]
@roipoby I Recompile opencv

**Comment by stonycat** [comment]
I recompile Opencv, the version I used is 2.4.13. @roipony

**Comment by ChengXu-Jason** [comment]
hi everyone, i have the same problem. i am totally new to this. could anyone tell me how to recompile OpenCV without OpenCL option? I will appreciate it very much.

**Comment by chl916185** [comment]
hi,you solved this problem?How did you solve it？
@ChengXu-Jason @stonycat @roipony

**Comment by linthy** [comment]
hi, i meet the same problem, and i try to recompile OpenCV without OpenCL. But the problem is not solved.@weiliu89 @stonycat
