### ISSUE TITLE
Why ResNets do not outperform VGG16?

### ISSUE THREAD

**Issue by wk910930** [weiliu89/caffe#322]
Dear Wei,

It seems do not make sense that a stronger base network (e.g. ResNet-50/101/152) cannot outperform the weaker (i.e. VGG16) one in SSD. Usually we do not need to adjust many hyper parameters by just changing networks. And we can easily benefit from better feature representations in many tasks and frameworks. What is your personal opinion on that?

(p.s.  #130 gives some explanation, but could you tell me more?)

Thanks!

**Comment by weiliu89** [comment]
We have seen ResNet is about 5-6 points better than VGGNet on COCO. Maybe VOC is too small and VGG is enough to fit it well.

**Comment by wk910930** [comment]
Sounds great! Will you report the results and details in your next version of paper on arXiv?
