### ISSUE TITLE
Original VGG vs. VGG-reduced as base network

### ISSUE THREAD

**Issue by lvauchier** [weiliu89/caffe#324]
Hi @weiliu89,

did you try to use the orgiginal VGG-16 network as base network ?
If so, what are the differences in speed and mAP between these 2 versions of the networks ?

Thanks in advance,
Léa

**Comment by weiliu89** [comment]
There is a section in the ablation study which discusses about this. Please check the paper

**Comment by lvauchier** [comment]
Sorry, I missed it in the paper
