### ISSUE TITLE
How to evaluate AP per class

### ISSUE THREAD

**Issue by SpecialM2580** [weiliu89/caffe#328]
Is there any convenient code to evaluate the AP value for each class ? %>_<%

**Comment by weiliu89** [comment]
Check out this 8a65ae3. Please be noticed that the AP computed is not guaranteed to be exactly same as official evaluation script (e.g. VOCdevkit). However, it should be within 0.* difference (due to some precision issue between Matlab and C++ I guess).

**Comment by SpecialM2580** [comment]
Thanks !!!

**Comment by silvia0223** [comment]
Hello,I download and compile the newest version of caffe-ssd, I check the caffe.proto and solver.cpp,found these options have already exited.    BUT,when I train my data,there are still no 'per class AP' in my log. T--T How can I get the per class AP when testing the model? Thaaanks!

**Comment by silvia0223** [comment]
@SpecialM2580 hi,did u success？

**Comment by lzx1413** [comment]
the detection results will be saved as *.txt in a directory, you can use scrips like https://gist.github.com/lzx1413/7d69b8e4b7f5141cb41acde0f9cf6d23 or the official script to evaluate the results

**Comment by ZongxianLee** [comment]
@lzx1413 你好，感谢分享，我看了您提供的验证的code，但有几个地方不是太明白，val_file = '../../2007test.txt'，det_root = './predict_ss/'，我想知道这个val_file指的是ssd检测结果的txt，但这个det_root比较疑惑，不知道应该是什么路径，希望得到您的指点，谢谢！

**Comment by lzx1413** [comment]
val_file是voc07 的test目录文件，在voc里面有，det_root 是检测结果的txt的文件夹
