### ISSUE TITLE
Check failed: infile.good() Failed to open name size file: data/coco/minival2014_name_size.txt

### ISSUE THREAD

**Issue by NIEYALI** [weiliu89/caffe#334]
Dear Wei,
thanks for your share. But when I use coco dataset, I met then problem"Check failed: infile.good() Failed to open name size file: data/coco/minival2014_name_size.txt", in the file create_list.sh, it doesn't create the 'minival2014_name_size.txt' file, but in 'ssd_coco.py' this file , it use the file. 

could you help me to solve the problem?
Thanks for your kindness

**Comment by weiliu89** [comment]
Please follow the README.md in `data/coco` folder.

**Comment by NIEYALI** [comment]
Thanks, it works

**Comment by wendaoyuchen** [comment]
Hi, I am troubled with the same problem as you, but when I execute as the README.md, I can't find the batch_split_annotation.py and batch_get_image_size.py in the 4th step,can you help me?Thanks.

**Comment by weiliu89** [comment]
Follow exactly what the README in coco folder. You should checkout the dev branch

**Comment by weiliu89** [comment]
Please follow README in the data/coco folder
