### ISSUE TITLE
Computing box priors everytime detection runs ?

### ISSUE THREAD

**Issue by wonwoolee** [weiliu89/caffe#347]
Hi, 

It looks like box priors are implemented as a layer in your code here: 
https://github.com/weiliu89/caffe/blob/ssd/python/caffe/model_libs.py#L801

Does it mean the box priors are computed in every run of detection? 
I though they are constant, once parameters are fixed, e.g, the resolution of detection layers, the number of scales and aspect ratios...

Any comments ?

**Comment by weiliu89** [comment]
It is left as it is to handle the case when the images are of different size during training. You can add a few lines of code to do a check and ignore recomputing when the batch size is same for consecutive iterations.

**Comment by wonwoolee** [comment]
I see the point, thanks.
