### ISSUE TITLE
OpenCV Error: Assertion failed

### ISSUE THREAD

**Issue by NIEYALI** [weiliu89/caffe#353]
Dear Wei, I got new problem, about opencv, The problem is following:
OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F)) in ipp_cvtColor, file /home/user1/opencv-3.1.0/modules/imgproc/src/color.cpp, line 7646
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/user1/opencv-3.1.0/modules/imgproc/src/color.cpp:7646: error: (-215) (scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F) in function ipp_cvtColor

*** Aborted at 1482480286 (unix time) try "date -d @1482480286" if you are using GNU date ***
PC: @     0x7f7e541abcc9 (unknown)
*** SIGABRT (@0x3e900004df8) received by PID 19960 (TID 0x7f7e227fd700) from PID 19960; stack trace: ***
    @     0x7f7e541abd40 (unknown)
    @     0x7f7e541abcc9 (unknown)
    @     0x7f7e541af0d8 (unknown)
    @     0x7f7e54f61535 (unknown)
    @     0x7f7e54f5f6d6 (unknown)
    @     0x7f7e54f5f703 (unknown)
    @     0x7f7e54f5f922 (unknown)
    @     0x7f7e4d12fca0 cv::error()
    @     0x7f7e4d12fe20 cv::error()
    @     0x7f7e4b574c89 cv::ipp_cvtColor()
    @     0x7f7e4b57e4d4 cv::cvtColor()
    @     0x7f7e5600758a caffe::AdjustSaturation()
    @     0x7f7e5600c77a caffe::RandomSaturation()
    @     0x7f7e5600ce96 caffe::ApplyDistort()
    @     0x7f7e561dfeac caffe::DataTransformer<>::DistortImage()
    @     0x7f7e561c7beb caffe::AnnotatedDataLayer<>::load_batch()
    @     0x7f7e560abc29 caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7f7e55ff39f0 caffe::InternalThread::entry()
    @     0x7f7e4abf9a4a (unknown)
    @     0x7f7e4678a182 start_thread
    @     0x7f7e5426f47d (unknown)
    @                0x0 (unknown)
Aborted (core dumped)

Does it mean opencv 3.1 do not support this program?
Do you have any good idea about it?

Thank you very much

**Comment by weiliu89** [comment]
Try adding [this](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_coco.py#L178)?

**Comment by NIEYALI** [comment]
yes,  thank you very much, no problem now
