### ISSUE TITLE
data_transformer.cpp:621] Check failed: mean_values_.size() == 1

### ISSUE THREAD

**Issue by NIEYALI** [weiliu89/caffe#354]
Dear wei, now new problem:
I1223 20:11:59.726653 26060 sgd_solver.cpp:138] Iteration 9990, lr = 0.001
I1223 20:12:08.730830 26060 solver.cpp:433] Iteration 10000, Testing net (#0)
I1223 20:12:09.336642 26060 net.cpp:693] Ignoring source layer mbox_loss
F1223 20:12:10.965924 26111 data_transformer.cpp:621] Check failed: mean_values_.size() == 1 || mean_values_.size() == img_channels Specify either 1 mean_value or as many as channels: 1
*** Check failure stack trace: ***
    @     0x7f12f8089daa  (unknown)
    @     0x7f12f8089ce4  (unknown)
    @     0x7f12f80896e6  (unknown)
    @     0x7f12f808c687  (unknown)
    @     0x7f12f8930a5f  caffe::DataTransformer<>::Transform()
    @     0x7f12f8933bdc  caffe::DataTransformer<>::Transform()
    @     0x7f12f893cfbb  caffe::DataTransformer<>::Transform()
    @     0x7f12f893d078  caffe::DataTransformer<>::Transform()
    @     0x7f12f893d12e  caffe::DataTransformer<>::Transform()
    @     0x7f12f8915e84  caffe::AnnotatedDataLayer<>::load_batch()
    @     0x7f12f87f9c29  caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7f12f87419f0  caffe::InternalThread::entry()
    @     0x7f12ed347a4a  (unknown)
    @     0x7f12e8ed8182  start_thread
    @     0x7f12f69bd47d  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

After 10000 iters, it again has problem.
Do you know why it happens?
thank you

**Comment by NIEYALI** [comment]
I think the problem is solved, thanks a lot

**Comment by katariachirag1** [comment]
I am facing the same problem, how did you solve it?

**Comment by NIEYALI** [comment]
@katariachirag1 I reduced the batch size.

**Comment by jacco09** [comment]
I reduce the batch size,but it dosen't work,can you help me?

**Comment by NIEYALI** [comment]
maybe you also have other problems, please check it carefully
