### ISSUE TITLE
Error: has no field named "filter_stride"

### ISSUE THREAD

**Issue by mjohn123** [weiliu89/caffe#361]
I cloned your newest version code at https://github.com/weiliu89/caffe/tree/fcn

And the VOC12 Pascal training and testing at https://gist.github.com/weiliu89/45e9e8de2c13af6476ca#file-readme-md

After build without error. I try to run the `VGG_VOC2012ext.sh` but I got the error 

```
I1229 21:36:49.356602 32437 solver.cpp:103] Creating training net from net file: ./models/VGGNet/VOC2012ext/VGG_VOC2012ext.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 385:18: Message type "caffe.ConvolutionParameter" has no field named "filter_stride".
F1229 21:36:49.356961 32437 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) 
Failed to parse NetParameter file: ./models/VGGNet/VOC2012ext/VGG_VOC2012ext.prototxt
```

I read your guidance about that

`You should be able to train/eval this model with http://github.com/weiliu89/caffe/tree/fcn. This branch introduces filter_stride (used for 'atrous' algorithm as described in Deeplab), L2-norm layer, evaluation code on the fly, etc.`

But I do not know how can I fix it. Am I wrong to clone the code?

**Comment by weiliu89** [comment]
@mjohn123 Make sure your PYTHONPATH is pointing to the right place.

**Comment by weiliu89** [comment]
The branch is not maintained anymore. You can refer to `[dilation](https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L570)`, which does the same thing as `filter_stride`.

**Comment by mjohn123** [comment]
Thanks weiliu89. You means we have to use the newest caffe branch as `git clone https://github.com/weiliu89/caffe`. is it right?

**Comment by weiliu89** [comment]
@mjohn123 No. If you want to train ParseNet, you should use the `fcn` branch. I was just telling you that `filter_stride` does the same (or similar) thing as `dilation` in the `master` branch. I think if you set PYTHONPATH correctly, you should solve the problem.

**Comment by mjohn123** [comment]
Thank @weiliu89. You are correct. The issue is from PYTHONPATH. I set up it to current caffe version. Hence, it appears the above error. I changed and it worked well
