### ISSUE TITLE
something wrong with 'create_list.sh' file.

### ISSUE THREAD

**Issue by yiakwy** [weiliu89/caffe#367]
Hi, guys 👍 

after successful installation (pass tests) both for caffe and caffe interface pycaffe, I downloaded data files and tar them:

VOC0712	VOC2007	VOC2012

However, when I ran `create_list.sh`, I got:

> E0103 11:49:05.472187 1956942592 io.cpp:183] Could not open or find file /Users/wangyi/data/VOCdevkit/007904

, Which is ridiculous. 

Hence I confirm that `create_list.sh` must be wrong. 

Here is more details:

sh ./data/VOC0712/create_list.sh

A report generated, where line 13 corresponds to line 45 in source file "create_list.sh"

>   1 [test-cmd] : test $dst_file '/Users/wangyi/GitHub/SSD/caffe/data/VOC0712/trainval.txt' existing
>   2 Create list for VOC2007 trainval...
>   3 [test-cmd] : editing image file /Users/wangyi/GitHub/SSD/caffe/data/VOC0712/trainval_img.txt
>   4 Create list for VOC2012 trainval...
>   5 [test-cmd] : editing image file /Users/wangyi/GitHub/SSD/caffe/data/VOC0712/trainval_img.txt
>   6 shuffle trainval file
>   7 target : /Users/wangyi/GitHub/SSD/caffe/data/VOC0712/trainval.txt
>   8 rand file :
>   9 [test-cmd] : test $dst_file '/Users/wangyi/GitHub/SSD/caffe/data/VOC0712/test.txt' existing
>  10 Create list for VOC2007 test...
>  11 [test-cmd] : editing image file /Users/wangyi/GitHub/SSD/caffe/data/VOC0712/test_img.txt
>  12 [test-cmd] gen image name and size
>  13 [test-cmd] get : /Users/wangyi/GitHub/SSD/caffe/data/VOC0712/../../build/tools/get_image_size

Source file :

>  40   # Generate image name and size infomation.
>  41   if [ $dataset == "test" ]
>  42   then
>  43     echo "gen image name and size"
>  44     echo "get : $bash_dir/../../build/tools/get_image_size"
>  45     $bash_dir/../../build/tools/get_image_size $root_dir $dst_file $bash_dir/$dataset"_name_size.txt"
>  46   fi
>  47
>  48   # Shuffle trainval file.
>  49   if [ $dataset == "trainval" ]
>  50   then
>  51     echo "shuffle trainval file"
>  52     echo "target : $dst_file"
>  53     echo "rand file : $rand_file"
>  54     rand_file=$dst_file.random
>  55     cat $dst_file | perl -MList::Util=shuffle -e 'print shuffle(<STDIN>);' > $rand_file
>  56     mv $rand_file $dst_file
>  57   fi

Can anybody help me to figure out what the hell it is?

**Comment by yiakwy** [comment]
From another post, I figured it out that BE some bugs raised from sed in Mac OS since the script only tested in Ubuntu system.

**Comment by yiakwy** [comment]
Ok I will close the problem since I have already figured out how to deal with it. I have already submit a pull request for you to refer. Basically, overwritten sed in "create_list.sh" will be ok.

**Comment by ohkhan** [comment]
I'm on a mac and having this issue as well. Can you expand on how you fixed the sed issue? The "create_list.sh" in the PR seems to be exactly the same as the create_list.sh packaged in the repo.
