### ISSUE TITLE
A video detection

### ISSUE THREAD

**Issue by tjpuzhaolei** [weiliu89/caffe#37]
1.    I want to test a video, not just a picture or obtained from the camera,  to test a video,  what should I do?  
2.   for the  ( from caffe import layers as L ).      I find your reference function{   L.Convolution()}.   but i can`t   find  the function definitions in  the  layers.Where can I find  Convolution()  function?  thank you

**Comment by weiliu89** [comment]
You can pull the latest code and check out [this demo script](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_pascal_video.py).

**Comment by tjpuzhaolei** [comment]
Thank you very much for providing this file.   And I want to know the function{ L.Convolution() } in which files.

**Comment by weiliu89** [comment]
It is something widely used in Caffe. It is define at [here](https://github.com/weiliu89/caffe/blob/ssd/python/caffe/net_spec.py#L215).

**Comment by tjpuzhaolei** [comment]
error  is   type object 'VideoDataParameter' has no attribute 'VIDEO'.    caffe_pb2  need to regenerate ?   
through to execute the command  make py ?     I have already modified. CPP and HPP file.

**Comment by weiliu89** [comment]
Yes, you should `make py` again..

You could use `git pull` to sync to the latest code.

**Comment by tjpuzhaolei** [comment]
I asked the questions are relatively low.Thank you very much for your patient answer.

**Comment by weiliu89** [comment]
No problem :) Good luck!
