### ISSUE TITLE
default box issue during prediction time

### ISSUE THREAD

**Issue by ByoenghakYim** [weiliu89/caffe#372]
Hi.

I wonder why default boxes are not considered when ssd generates prediction.

In R-CNN based approach, I observed that the confidence changes according to the box coordinate because the confidence only relates to the pixels in the box.
(When the box coordinate fits on gt, the gt confidence is higher)

Does default box affect only bbox regression?

Thanks

**Comment by weiliu89** [comment]
There is no pixel or feature resampling step as was used in R-CNN series of methods.
