### ISSUE TITLE
Can the ssd branch be used to train classification model? I got problems.

### ISSUE THREAD

**Issue by zxDeepDiver** [weiliu89/caffe#385]
Hello,

Thanks for your nice work.
I want to used the various data augmentation tricks in classification task. So I only leave the resize and distort transformation in the train.prototxt.  
I generate the prototxt and modified the loss to classificaiton loss. And I generated the lmdb files.
When I run this solver in your caffe code, I got :

F0111 01:39:43.162824 13938 data_transformer.cpp:1036] Check failed: datum_channels > 0 (0 vs. 0)
*** Check failure stack trace: ***
    @     0x7fb5a86dfb5d  google::LogMessage::Fail()
    @     0x7fb5a86e3b77  google::LogMessage::SendToLog()
    @     0x7fb5a86e19f9  google::LogMessage::Flush()
    @     0x7fb5a86e1cfd  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb5ae089c73  caffe::DataTransformer<>::InferBlobShape()
    @     0x7fb5adfdd5f1  caffe::AnnotatedDataLayer<>::DataLayerSetUp()
    @     0x7fb5ae018f63  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7fb5ae0ed15c  caffe::Net<>::Init()
    @     0x7fb5ae0edfe5  caffe::Net<>::Net()
    @     0x7fb5ae0aea7a  caffe::Solver<>::InitTrainNet()
    @     0x7fb5ae0af9fc  caffe::Solver<>::Init()
    @     0x7fb5ae0afd2a  caffe::Solver<>::Solver()
    @     0x7fb5ae0d5c23  caffe::Creator_SGDSolver<>()
    @           0x40f91e  caffe::SolverRegistry<>::CreateSolver()
    @           0x408a12  train()
    @           0x40649c  main
    @     0x7fb5a051fb15  __libc_start_main
    @           0x406d0d  (unknown)

Here is the data layer of my prototxt.

layer {
  name: "data"
  type: "AnnotatedData"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  transform_param {
    mirror: true
    crop_size: 224
    mean_value: 104
    mean_value: 117
    mean_value: 123
    resize_param {
      prob: 1
      resize_mode: WARP
      height: 300
      width: 366
      interp_mode: LINEAR
      interp_mode: AREA
      interp_mode: NEAREST
      interp_mode: CUBIC
      interp_mode: LANCZOS4
    }
    distort_param {
      brightness_prob: 0.5
      brightness_delta: 32
      contrast_prob: 0.5
      contrast_lower: 0.5
      contrast_upper: 1.5
      hue_prob: 0.5
      hue_delta: 18
      saturation_prob: 0.5
      saturation_lower: 0.5
      saturation_upper: 1.5
      random_order_prob: 0.0
     hue_delta: 18
      saturation_prob: 0.5
      saturation_lower: 0.5
      saturation_upper: 1.5
      random_order_prob: 0.0
    }
  }
  data_param {
    source: "examples/imagenet/ilsvrc12_train_lmdb"
    batch_size: 4
    backend: LMDB
  }
}

Thanks in advance.

**Comment by weiliu89** [comment]
How did you generate your `ilsvrc12_train_lmdb`? It should store image in AnnotatedDatum instead of Datum.
