### ISSUE TITLE
Cannot parse label map file

### ISSUE THREAD

**Issue by AndrewZhao** [weiliu89/caffe#39]
I got this error when i run ./data/VOC0712/create_data.sh and i can't generate lmdb files.

**Cannot parse label map file: /home/zhaoboya/SSD/caffe/data/VOC0712/labelmap_voc.prototxt
Cannot parse label map file: /home/zhaoboya/SSD/caffe/data/VOC0712/labelmap_voc.prototxt**

The labelmap_voc.prototxt is not modified.
Thanks for helping me.

**Comment by weiliu89** [comment]
I have no idea. What is your OS environment etc.? It might be some problem related to protobuf

**Comment by zhiqizhang** [comment]
I have the exact same problem. I am using Ubuntu 1.5

Thanks.

**Comment by weiliu89** [comment]
Have you tried to run this [ipynb](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd_detect.ipynb) to see if it can load the labelmap prototxt or not?

**Comment by zhiqizhang** [comment]
I found the problem. I have a previous version of caffe and there is no LabelMap in the proto/caffe_pb2.py file. I changed the python path to the new path, and problem solved. Thanks you

**Comment by CHUNYUWANG** [comment]
I am using Windows Server 2012 and met the same problem. I tried ipynb and it failed to load the labelmap -- the returned list is empty.

**Comment by zhiqizhang** [comment]
I have fixed this problem by double check my Path. and I found that my old python path pointed to another caffe python path.

**Comment by AndrewZhao** [comment]
I have fixed the problem on the condition of python3.In the ./script/creat_annoset.py
`lmf = open(label_map_file, "rb")
    try:
      text_format.Merge(str(lmf.read()), label_map)
    except:
      print("Cannot parse label map file: {}".format(label_map_file))
      sys.exit()`
I changed this:
text_format.Merge(str(lmf.read()), label_map) =>text_format.Merge(lmf.read(), label_map)
