### ISSUE TITLE
Created LMDB by creat_data.sh But Read NULL

### ISSUE THREAD

**Issue by jinfagang** [weiliu89/caffe#390]
Guiding the SSD tutorial I generated lmdb of VOC0712 in `~/data/VOCdevkit/VOC0712/lmdb/VOC0712_trainval_lmdb` and this file seems has 1.8GB for trainval_lmdb, but when I try to read this file, I find the are nothing in database, the read_lmdb.py can read other lmdb file for classify. I post it in here:
```
        lmdb_path = sys.argv[1]
	print('lmdb path at ', lmdb_path)
	lmdb_env = lmdb.open(lmdb_path, readonly=True) 
	lmdb_txn = lmdb_env.begin() 
	lmdb_cursor = lmdb_txn.cursor()
	key = lmdb_cursor.key()
	value = lmdb_cursor.value()
	datum = caffe_pb2.Datum()
	  
	for (idx, (key, value)) in enumerate(lmdb_cursor):
	    datum.ParseFromString(value)
	    print('--- seeing the {0} image in lmdb ---'.format(idx + 1))
	    label = datum.label
	    print('label: ', str(label))

	    width = datum.width
	    print('width', width)
	    height = datum.height
	    print('height', height)

	    data = caffe.io.datum_to_array(datum)
	    print(data.shape)
	    print(data)

	    image = data.transpose(1, 2, 0)
	    print(image)
	    print(image.shape)
	    cv2.imshow('cv2.png', image)  
	    cv2.waitKey(0)

	    if idx >= 50:
	      	break 
	print("lmdb preview done!")   
	cv2.destroyAllWindows()  
	lmdb_env.close()
```
And I just got this:
```
--- seeing the 1 image in lmdb ---
label:  0
width 0
height 0
(0, 0, 0)
[]
[]
(0, 0, 0)
OpenCV Error: Assertion failed (size.width>0 && size.height>0) in imshow, file /home/jfg/opencv-3.1.0/modules/highgui/src/window.cpp, line 281
Traceback (most recent call last):
  File "read_lmdb.py", line 38, in <module>
    cv2.imshow('cv2.png', image)  
cv2.error: /home/jfg/opencv-3.1.0/modules/highgui/src/window.cpp:281: error: (-215) size.width>0 && size.height>0 in function imshow
```
Apparently, the lmdb file was empty! I have to mention that this script can read other lmdb file like minist or others, does anybody know why this happen or is there anybody can give me a help to read the lmdb value in SSD generated datasets?

**Comment by weiliu89** [comment]
The data is saved in a new proto called AnnotatedDatum instead of Datum. You should replace the line to: `datum = caffe_pb2.AnnotatedDatum()`

**Comment by jinfagang** [comment]
thanks for reply, I change into `AnnotatedDatum`, and I read source code find `Datum` is the child property of `AnnotatedDatum`, so I write it like this:
```
lmdb_env = lmdb.open('/home/chenqi-didi/data/VOCdevkit/VOC0712/lmdb/VOC0712_trainval_lmdb', readonly=True) # 打开数据文件  
lmdb_txn = lmdb_env.begin() # 生成处理句柄  
lmdb_cursor = lmdb_txn.cursor()
key = lmdb_cursor.key()
value = lmdb_cursor.value()
anno_datum = caffe_pb2.AnnotatedDatum() # caffe 定义的数据类型  
  
for (idx, (key, value)) in enumerate(lmdb_cursor): # 循环获取数据  
    anno_datum.ParseFromString(value) # 从 value 中读取 datum 数据  
  
    # label = datum.label
    # print 'label: ', str(label)
    data = caffe.io.datum_to_array(anno_datum.datum)  
    print data.shape
    print datum.channels
    image = data.transpose(1, 2, 0)  
    cv2.imshow('cv2.png', image)  
    cv2.waitKey(0)  
  
cv2.destroyAllWindows()  
lmdb_env.close()
```
I am trying to get datum in `AnnotatedDatum` but I got this error:
```
Traceback (most recent call last):
  File "read_lmdb.py", line 22, in <module>
    data = caffe.io.datum_to_array(anno_datum.datum)  
  File "/home/chenqi-didi/Documents/work/caffe/python/caffe/io.py", line 90, in datum_to_array
    datum.channels, datum.height, datum.width)
ValueError: total size of new array must be unchanged
```
What is exactly right approach to get datum's data which contains the image binary data?

**Comment by weiliu89** [comment]
@jinfagang The image is stored in encoded format. You should write your own python function to load the data and decode the image.

**Comment by jinfagang** [comment]
@weiliu89 Yeah, I can read the encoded image data, but in which way it was encoded? Does there are any function provided in SSD source code?

**Comment by jinfagang** [comment]
I think I can change the encoded data into numpy array right now, but it just 1d array, to convert it into image array I need channels, width and height information, how ever this not store in lmdb(in AnnotatedDatum's datum read property has no channels, width and height info). So the question is how to make it back to original image without this info? Seems this is unreasonable for not store size info in Datum because when make it original I have to get size info from annotation xml files which maybe annoying.

**Comment by weiliu89** [comment]
I should save the size information.

Actually, in C++, it calls [`DecodeDatumToCVMatNative`](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/util/io.cpp#L646) to decode the image. `-1` in cv::imdecode() will decode the image in its original format.

**Comment by jinfagang** [comment]
@weiliu89 Sounds practical! But one last question, I am trying to store my own data into lmdb and feed into SSD. I got too folders, save JPGImages and Labels, treed like this:
```
.
└── JPGImages
    ├── frame_000000.jpg
    ├── frame_000001.jpg
    ├── frame_000002.jpg
    ├── frame_000003.jpg
└── Labels
    ├── frame_000000.txt
    ├── frame_000001.txt
    ├── frame_000002.txt
    ├── frame_000003.txt
```
In each label txt files annotate like this:
```
0 25 68 30 95
```
Just like this function inquired.
```
// Parse plain txt detection annotation: label_id, xmin, ymin, xmax, ymax.
bool ReadTxtToAnnotatedDatum(const string& labelfile, const int height,
    const int width, AnnotatedDatum* anno_datum)
```
So there maybe a problem: **AnnotatedDatum** need normalize the bboxes which means it needs **height and width** info, but still in **create_list.sh** & **create_data.sh** I cannot find any code get the width and height(and when call **convert_anno.cpp** it has not send args about widht and height), so how can I exactly call `ReadTxtToAnnotatedDatum` function and send my images width and height into it?

**Comment by weiliu89** [comment]
`ReadTxtToAnnotatedDatum` is called from [`ReadRichImageToAnnotatedDatum`](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/util/io.cpp#L194).

**Comment by weiliu89** [comment]
@jinfagang BTW, I have a quick fix (3d7035d) for the problem you mentioned. You could create the dataset again and the AnnotatedDatum should have the meta information for the image.

**Comment by jinfagang** [comment]
If I not store width and height just send bbox and label into `AnnotedDatum`, will it normalize automatically? @weiliu89

**Comment by jinfagang** [comment]
Hey, I seems meet one last trouble, I generated my Images and Labels folder. In Labels:
```
00001.txt
00002.txt
```
Every txt:
```
0 23 34 40 60
```
```
label_index x_min y_min x_max y_max
```
I got trainval.list:
```
Images/0001.jpg Labels/0001.txt
...
```
When I trying to create data, I edit only one option then original one:
```
label_type="txt"
```
But I got this:
```
I0117 16:30:45.847317 12209 convert_annoset.cpp:122] A total of 11036 images.
I0117 16:30:45.847580 12209 db_lmdb.cpp:35] Opened lmdb /home/chenqi-didi/data/TLR/lmdb/TLR_trainval_lmdb
I0117 16:30:48.628445 12209 convert_annoset.cpp:195] Processed 1000 files.
W0117 16:30:48.945461 12209 io.cpp:506] /home/chenqi-didi/data/TLR/Labels/frame_001104.txt bounding box exceeds image boundary.
W0117 16:30:48.948124 12209 io.cpp:506] /home/chenqi-didi/data/TLR/Labels/frame_001105.txt bounding box exceeds image boundary.
W0117 16:30:48.950716 12209 io.cpp:506] /home/chenqi-didi/data/TLR/Labels/frame_001106.txt bounding box exceeds image boundary.
W0117 16:30:48.953308 12209 io.cpp:506] /home/chenqi-didi/data/TLR/Labels/frame_001107.txt bounding box exceeds image boundary.
W0117 16:30:48.955904 12209 io.cpp:506] /home/chenqi-didi/data/TLR/Labels/frame_001108.txt bounding box exceeds image boundary.
W0117 16:30:48.958518 12209 io.cpp:506] /home/chenqi-didi/data/TLR/Labels/frame_001109.txt bounding box exceeds image boundary.
W0117 16:30:48.961117 12209 io.cpp:506] /home/chenqi-didi/data/TLR/Labels/frame_001110.txt bounding box exceeds image boundary.
```
It says bbox exceeds image boundary, any idea solve this?
