### ISSUE TITLE
Cannot copy param 0 weights from layer 'conv4_3_norm_mbox_conf'; shape mismatch.  Source param shape is 84 512 3 3 (387072); target param shape is 36 512 3 3 (165888).

### ISSUE THREAD

**Issue by jinfagang** [weiliu89/caffe#398]
I saved data into lmdb and read it successfull, I train 8 classes, but when I run ssd_pascal.py(edit dataset dir), I got this error:
```
F0119 14:08:46.572635 30097 net.cpp:774] Cannot copy param 0 weights from layer 'conv4_3_norm_mbox_conf'; shape mismatch.  Source param shape is 84 512 3 3 (387072); target param shape is 36 512 3 3 (165888). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
*** Check failure stack trace: ***
    @     0x7f4ecb4b95cd  google::LogMessage::Fail()
    @     0x7f4ecb4bb433  google::LogMessage::SendToLog()
    @     0x7f4ecb4b915b  google::LogMessage::Flush()
    @     0x7f4ecb4bbe1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4ecbba061b  caffe::Net<>::CopyTrainedLayersFrom()
    @     0x7f4ecbba9b15  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f4ecbba9bae  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x40a849  CopyLayers()
    @           0x40bca4  train()
    @           0x4077c8  main
    @     0x7f4ec9c50830  __libc_start_main
    @           0x408099  _start
    @              (nil)  (unknown)
Aborted (core dumped)

```
I check `train.prototxt` and `test.prototxt`, it seems there is no mismatch at all. I thought the question maybe cause by some source code layer, how to solve it?

**Comment by weiliu89** [comment]
It tries to load `models/VGGNet/VOC0712/SSD_300x300`. You can either change `job_name` in the script or move the model folder somewhere else.

**Comment by jinfagang** [comment]
thks, figure it out

**Comment by RoseLii** [comment]
please help me
Cannot copy param 0 weights from layer 'conv4_3_norm_mbox_conf'; shape mismatch.  Source param shape is 84 512 3 3 (387072); target param shape is 176 512 3 3 (811008). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
*** Check failure stack trace: ***
@jinfagang 怎么改job_name，可以稍微说的详细点吗。有点看不懂

**Comment by evenctit** [comment]
@jinfagang  & @weiliu89 how to change the job name? can help provide more details? thanks.
