### ISSUE TITLE
How to compile ssd_detect.cpp

### ISSUE THREAD

**Issue by youngwanLEE** [weiliu89/caffe#40]
Hi, Wei. Thank you in advance for your wonderful code :)

Already execution file is in $CAFFE_ROOT/build/examples/ssd/ssd_detect.bin. 

I want to execute and integrate the SSD framework with other system on the TX1 board.

Thus, I want to modify and compile the ssd_detect.cpp. But, I'm not familiar with compiling in ubuntu. 

Could you explain how to compile with ssd_detect.cpp ?

**Comment by weiliu89** [comment]
You can modify the file and then `make`, it will replace the ssd_detect.bin

**Comment by youngwanLEE** [comment]
ah, Good !

I have a another issue running the ssd_detect.bin. 

I0714 12:34:22.404853  5080 net.cpp:274] Network initialization done.
I0714 12:34:22.686604  5080 net.cpp:752] Ignoring source layer data
I0714 12:34:22.686632  5080 net.cpp:752] Ignoring source layer data_data_0_split
I0714 12:34:22.695639  5080 net.cpp:752] Ignoring source layer mbox_loss
F0714 12:34:23.028506  5080 ssd_detect.cpp:278] Check failed: !img.empty() Unable to decode image �PNG
*** Check failure stack trace: ***
    @     0x7f9050a8cdaa  (unknown)
    @     0x7f9050a8cce4  (unknown)
    @     0x7f9050a8c6e6  (unknown)
    @     0x7f9050a8f687  (unknown)
    @           0x404a71  main
    @     0x7f904fd9af45  (unknown)
    @           0x404da2  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

Perhaps, png format cannot be decoded.

**Comment by weiliu89** [comment]
Your image path in the list file is weird. It doesn't even show correctly `�PNG`
Maybe the image path is not in english?

**Comment by youngwanLEE** [comment]
This is my command.

./build/examples/ssd/ssd_detect.bin \ models/ResNet/KITTI/SSD_ResNet_19L_300x300/deploy.prototxt  models/ResNet/KITTI/SSD_ResNet_19L_300x300/ResNet_KITTI_SSD_ResNet_19L_300x300_iter_50000.caffemodel  data/kitti_ssd/test_kitti_yolo_img/000039.png

**Comment by weiliu89** [comment]
You should put `data/kitti_ssd/test_kitti_yolo_img/000039.png` in a txt file. Read the head of the ssd_detect.cpp

**Comment by youngwanLEE** [comment]
Thank you very much !
