### ISSUE TITLE
Effect of color during detection

### ISSUE THREAD

**Issue by vj-1988** [weiliu89/caffe#400]
Dear @weiliu89 ,

I have been able to train SSD on my custom dataset that contains logos. The detections are good for most of the classes. But for classes with same background color, the bounding boxes are ok, but the predictions seem to be inconsistent (the predicted classes varies within the set of logos that has same background color). So, to eliminate the effect of background color, would it be sufficient to convert the color images to 3 channel gray scale images before training?

Thank You

**Comment by weiliu89** [comment]
But even if you convert the color image to gray image, wouldn't the background still be same? You could try though.

**Comment by vj-1988** [comment]
@weiliu89 : It is true that the background would be the same if I convert color to gray image. But the difference between the background colors within all the training classes would also reduce thereby possibly reducing the dependency on background color to predict the logos. Anyways, I will try this and update you with the outcome. Thanks for your continued support.

**Comment by vj-1988** [comment]
@weiliu89 : I didn't see any improvement after converting the dataset to grayscale.
