### ISSUE TITLE
Are min_aspect_ratio and max_aspect_ratio relative to the aspect ratio of original images?

### ISSUE THREAD

**Issue by neermat** [weiliu89/caffe#402]
`batch_sampler` samples aspect_ratio of patches from uniform distribution in interval [`min_aspect_ratio`, `max_aspect_ratio`]. Suppose images in my lmdb files are of `w x h` size and we a box is sampled with an aspect ratio of `ar` in this interval. Then what would be the relation between the height and width of the box? `w1/h1=ar*(w/h)` or `w1/h1=ar`?

**Comment by weiliu89** [comment]
It is w1/h1=ar*(w/h)

**Comment by neermat** [comment]
Thanks for answering!
