### ISSUE TITLE
preparing data and training SSD on multi-channel images

### ISSUE THREAD

**Issue by ankitdhall** [weiliu89/caffe#411]
Hello,

I have trained SSD on a customized version of the VOC dataset and used the steps to prepare the data (as in SSD's readme). I would now like to use the above model to fine-tune on multi-channel images (RGB+D) as input. Where can I edit the channels dimensions as I see that the ssd_pascal.py script loads the VGGNet.

Also, what should I do differently to prepare the dataset correctly?

Regards,
Ankit

**Comment by weiliu89** [comment]
Usually almost all pretrained models (i.e. VGGNet) are trained on ImageNet which only has RGB image (3 channels). So either you have to train from scratch if you have enough data. Or you could consider some sort of fusion techniques by taking RGB as one input and D as another (e.g. a simple method is to repeat D channel 3 times). Again, you have to explore a bit to achieve the best performance. Good luck.

**Comment by ankitdhall** [comment]
@weiliu89 thanks, for the reply. I tweaked the AnnotatedData layer to accept .png images and included the 4th channels as disparity for the image. I also tweaked the code for various augmentation functions so that it works with the 4 channel image and treats them as RGB+D.
Cheers,
Ankit

**Comment by gd2016229035** [comment]
@ankitdhall Hello,ankitdhall! I would now like to train on .png images as 4 channel image, just like you! I have successfully created the 4 channel lmdb but failed to train on that. So may you share your code ,or give me some advice on how you can tweak the code to train successfully?  Especially data augmentation functions just treat them as RGB images ,so how can you modify them? Maybe I can just close these function?
Thank you!! ~~
Guan
