### ISSUE TITLE
min_sizes and max_sizes of default boxes not consistent with the paper?

### ISSUE THREAD

**Issue by neermat** [weiliu89/caffe#412]
It is mentioned in the paper that we use default boxes of two scales in each layer: s_k and sqrt(s_k*s_(k+1)). But in the script `ssd_pascal.py` it seems to me that the two scales are s_k and s_(k+1):
```
for ratio in xrange(min_ratio, max_ratio + 1, step):
  min_sizes.append(min_dim * ratio / 100.)
  max_sizes.append(min_dim * (ratio + step) / 100.)
```

Am I wrong in thinking this? Could you please clarify?

**Comment by abdallah95** [comment]
max_size is used to store s_(k+1) so he can compute sqrt(s_k*s_(k+1)) later in PriorBoxLayer. 
[here](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/layers/prior_box_layer.cpp#L164)

**Comment by neermat** [comment]
Thanks for pointing it out in the code. I was also looking for that line but couldn't find it.

**Comment by mvoelk** [comment]
According to the paper, the naive approach to do the calculation of min_sizes and max_sizes in `models/VGGNet/VOC0712Plus/SSD_512x512/ssd_pascal_512.py` would be something similar to
```python
min_dim = 512
mbox_source_layers = ['conv4_3', 'fc7', 'conv6_2', 'conv7_2', 'conv8_2', 'conv9_2', 'conv10_2']
min_ratio = 15
max_ratio = 90

np.linspace(min_ratio, max_ratio, len(mbox_source_layers)+1) * min_dim / 100.
```
array([  76.8   ,  131.6571,  186.5143,  241.3714,  296.2286,  351.0857,  405.9429,  460.8   ])

But how the calculation is done in the implementation leads to different values and code equivalent to
```python
a = np.linspace(min_ratio, max_ratio, 6)
a = np.concatenate((np.array([7]), a ,np.array([a[-1]+15])))
a * min_dim / 100.
```
array([  35.84,   76.8 ,  153.6 ,  230.4 ,  307.2 ,  384.  ,  460.8 ,  537.6 ])

Is there a reason for the different values?
