### ISSUE TITLE
12FPS in SSD300

### ISSUE THREAD

**Issue by CPFLAME** [weiliu89/caffe#42]
I have run ssd_pascal_video.py，and got 12FPS in the video.
  My GPU is Tesla K80,and I use cuda-7.0. I think it's too slow compared with 58 FPS in  your paper.
  Is there something wrong ？

**Comment by weiliu89** [comment]
58 FPS is measured using Titan X with batch size of 8. I think K80 is 2 times slower than Titan X, and if batch size is 1, it doesn't utilize the GPU well.

**Comment by CPFLAME** [comment]
Thanks,I changed test_batch_size to 10,and it performed better.
