### ISSUE TITLE
LMDB files creation ...

### ISSUE THREAD

**Issue by VanitarNordic** [weiliu89/caffe#424]
Hello,

Would you please explain a bit more about LMDB files creation section? I gonna make LMDB files for my own set of images (custom dataset)

I must create several LMDB files for training/validation **images** and **labels**.

- an LMDB file for Training images
- an LMDB file for Training labels
- an LMDB file for Validation images
- an LMDB file for Validation labels

I assume annotations would be in COCO format if I am right.

**Comment by weiliu89** [comment]
It stores the AnnotatedDatum. Check caffe.proto for more information

**Comment by VanitarNordic** [comment]
Caffe prototxt files described your model structure, but I am looking for a procedure to train it with my own custom images. I should make LMDB files myself and train the SSD with.

**Comment by VanitarNordic** [comment]
Please look at this piece of prototxt file from DetectNet. How can I modify the SSD prototxt file to accept these 4 different LMDB files?

------------------------------

name: "DetectNet"
layer {
  name: "train_data"
  type: "Data"
  top: "data"
  data_param {
    backend: LMDB
   ` source: "examples/kitti/kitti_train_images.lmdb"`
    batch_size: 10
  }
  include: { phase: TRAIN }
}
layer {
  name: "train_label"
  type: "Data"
  top: "label"
  data_param {
    backend: LMDB
    `source: "examples/kitti/kitti_train_labels.lmdb"`
    batch_size: 10
  }
  include: { phase: TRAIN }
}
layer {
  name: "val_data"
  type: "Data"
  top: "data"
  data_param {
    backend: LMDB
   ` source: "examples/kitti/kitti_test_images.lmdb"`
    batch_size: 6
  }
  include: { phase: TEST stage: "val" }
}
layer {
  name: "val_label"
  type: "Data"
  top: "label"
  data_param {
    backend: LMDB
    `source: "examples/kitti/kitti_test_labels.lmdb"`
    batch_size: 6
  }
  include: { phase: TEST stage: "val" }

**Comment by weiliu89** [comment]
AnnotatedDatum has both Datum and label information. Please check that proto.
[
convert_annoset.cpp](https://github.com/weiliu89/caffe/blob/ssd/tools/convert_annoset.cpp) is the real function to do the job, which is similar to [convert_imageset.cpp](https://github.com/weiliu89/caffe/blob/ssd/tools/convert_imageset.cpp) but is designed for storing AnnotatedDatum instead of Datum.
