### ISSUE TITLE
Issue when training new dataset

### ISSUE THREAD

**Issue by ShuenLyu** [weiliu89/caffe#426]
hello, I encountered this issue when I attemped to train my own dataset with SSD, any ideas about the belowing issue, please help.

### F0209 00:33:31.934646 21257 annotated_data_layer.cpp:205] Check failed:std::equal(top_shape.begin() + 1, top_shape.begin() + 4, shape.begin() + 1) 
*** Check failure stack trace: ***
    @     0x7fc2c7d7e5cd  google::LogMessage::Fail()
    @     0x7fc2c7d80433  google::LogMessage::SendToLog()
    @     0x7fc2c7d7e15b  google::LogMessage::Flush()
    @     0x7fc2c7d80e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc2c84ff180  caffe::AnnotatedDataLayer<>::load_batch()
    @     0x7fc2c860c77f  caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7fc2c84492b5  caffe::InternalThread::entry()
    @     0x7fc2bb6a55d5  (unknown)
    @     0x7fc2b617f6ba  start_thread
    @     0x7fc2c65fb82d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by ShuenLyu** [comment]
@weiliu89 please help

**Comment by VanitarNordic** [comment]
What format have you used to annotate your images? VOC?

**Comment by ShuenLyu** [comment]
yes, VOC format @VanitarNordic

**Comment by VanitarNordic** [comment]
You know in the VOC format, each image holds its own `.xml` file, but what he mentioned the the description is:

`Create the trainval.txt, test.txt, and test_name_size.txt in data/VOC0712/`

How you made these? That's my question of him after you in a new issue.

**Comment by ShuenLyu** [comment]
there are some files for preparation for training, for example, create_list.sh file to create the trainval.txt test.txt, and create_data.sh to make lmdb file. 
I just modified the corresponding files with my own dataset.

**Comment by VanitarNordic** [comment]
Does it make those txt and LMDB files successfully for you?

**Comment by weiliu89** [comment]
Annotation file should be either following VOC or COCO format. It can also be in plain text format as described at [here](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/util/io.cpp#L465).

**Comment by VanitarNordic** [comment]
is there any annotation tool to make those `.txt` files? 
the one I have create `.xml `file for each image.

**Comment by ShuenLyu** [comment]
yes, after some modifications of create_list.sh and create_data.sh file, I managed to make those txt and lmdb files @VanitarNordic 

have you encountered the issue I posted? any idea about that @weiliu89 , the training stopped at 40000 iterations and thrown that issue

**Comment by VanitarNordic** [comment]
@ShuenLyu 

May I have a look at modified file? I have not trained it myself yet.

**Comment by ShuenLyu** [comment]
In fact, It's very similar with thoes original ones, anyway, what's your email address, I will drop you an email . @VanitarNordic

**Comment by VanitarNordic** [comment]
@ShuenLyu 

hesam dot moshiri at gmail

The `coco_voc_map.txt` should be modified either?

**Comment by weiliu89** [comment]
@ShuenLyu Are you training/testing with FIT_SMALL_SIZE option?

**Comment by ShuenLyu** [comment]
I only referred to VOC dataste, so no need for me, and that's only a mapping file. I don't think we need modify that one also

**Comment by ShuenLyu** [comment]
I used the default option, didn't change the parameters of FIT_SMALL_SIZE @weiliu89

**Comment by VanitarNordic** [comment]
@ShuenLyu 

So no problem if our defined label(s) in annotations contain different name(s) than the ones list inside `coco_voc_map.txt` file? 

@weiliu89  Please guide us more with training with a custom dataset, That's the question of many people. I have opened an issue for this either (#425).

**Comment by ShuenLyu** [comment]
for the mapping file, I created the labelmap_voc.prototxt corresponding to the classes of my own dataset. of course you need make the related mapping file if you train ssd with your own dataset.

**Comment by weiliu89** [comment]
Check this: https://github.com/weiliu89/caffe/wiki/Train-SSD-on-custom-dataset

**Comment by VanitarNordic** [comment]
@weiliu89 

You know I'm not familiar with the syntax that those files are written, so I should understand the inputs and outputs of each file to be able to replicate the result in Windows or by a different programming language.

Then I can create the final LMDB file(s) and comeback and just train the network using your codes. anyway:

> Create a file list which contains the image_path and annotation_path, as was illustrated at here for VOC or here for COCO.

Please consider I have two folders, one names **Train** and another **Test**.
Train contains: `a.jpg`  `b.jpg`  `c.jpg` and also `a.xml` , `b.xml` and `c.xml`
Test folder contains: `d.jpg` `e.jpg` `f.jpg` and also `d.xml` `e.xml` and `f.xml` 

What the output file (the list) should look like then?

**Comment by VanitarNordic** [comment]
@weiliu89 

Okay, I solved my above mentioned question.

Just tell me what should be inside `test_name_size.txt` file?

**Comment by VanitarNordic** [comment]
@ShuenLyu 
What tool have you used to make Pascal VOC xml files?

**Comment by ShuenLyu** [comment]
check this link https://github.com/tzutalin/labelImg

**Comment by fighting-liu** [comment]
@ShuenLyu  Hello, have you solved this issue?  I encounter the same problem after numbers of iterations and i don't know how to fix it .

**Comment by ShuenLyu** [comment]
change the iteration times , and try it again, did the mbox_loss equal to 'nan' when the training stoped? @fighting-liu

**Comment by fighting-liu** [comment]
'mbox_loss' in my case is ok, and loss converges as the time goes by. But crashed after number of iterations. The same error as you got.

**Comment by ShuenLyu** [comment]
change the 590th line of src/caffe/proto/caffe.proto to _optional Resize_mode resize_mode = 1 [default = WARP]._  and try it again @fighting-liu

**Comment by ShuenLyu** [comment]
sorry, line 593th, not 590th

**Comment by ShuenLyu** [comment]
that issue was resolved by chnaging the traing mode from _FIT_SMALL_SIZE_ to _WARP_ mode

**Comment by ShuenLyu** [comment]
what's the difference among these three modes in caffe.proto file, WARP=1, FIT_SMALL_SIZE=2, FIT_LARGE_SIZE_AND_PAD=3  @weiliu89

**Comment by lk123400** [comment]
@ShuenLyu I change the line593 as optional Resize_mode resize_mode = 1 [default = WARP],but met an error as following:
                    caffe.proto:593:38: Field number 1 has already been used in "caffe.ResizeParameter" by field "prob".
Could you help me?

**Comment by mysticforce139** [comment]
Changing Resize_mode to 1 didn't help in my case. I had some images whose depth is 1 while it should have been 3 and when I filtered those images it worked.  You can easily check this in your _**Annotations**_ directory by doing  `grep \<depth\>1 *`

**Comment by RichardMrLu** [comment]
I meet the same trouble, I check my Annotaions, there is no depth = 1 or depth = 4.
Do you solve the probme with any other measures?

**Comment by ramanth-gajula** [comment]
@RichardMrLu  Are you sure depth in your Annotations is correct? Can you check depth directly from images rather than using depth from Annotations.

**Comment by RichardMrLu** [comment]
。。sorry, is it the with 'grep \<depth\>[^3] *' in JPEGImages? I input this order, but it don't print anything.
I have made new LMDB files 3-4 times, but it is the same trouble.Oh my god......

**Comment by ramanth-gajula** [comment]
@RichardMrLu   Check depth of all images from JPEGImages directory by using python PIL module(or any other workarounds)

**Comment by RichardMrLu** [comment]
@mysticforce139  Thanks for your answer, I will try to check my images.

**Comment by zhanghanbin3159** [comment]
I meet the problem,my train prototxt has set resize_mode: WARP. so i cheak the image chanel, first ,use opencv.imread function,the chanel is 3. But when I use PIL.open function to read my train image, the chanel is just 1.
