### ISSUE TITLE
How to use your "ResNet152Body" function?

### ISSUE THREAD

**Issue by peternara** [weiliu89/caffe#43]
Hi,

I want to use resnet152 model for ssd.
and, i convert your "ssd_pascal.py".
so, this part
 
VGGNetBody(net, from_layer='data', fully_conv=True, reduced=True, dilated=True,   dropout=False, freeze_layers=freeze_layers)
--> ResNet152Body(net, from_layer='data')

pretrain_model = "models/VGGNet/VGG_ILSVRC_16_layers_fc_reduced.caffemodel"
--> pretrain_model = "my_path/ResNet-152-model.caffemodel"

finally, commad : python examples/ssd/ssd_pascal.py

but, i have a error..

  File "examples/ssd/ssd_pascal_resnet.py", line 401, in <module>
    prior_variance=prior_variance, kernel_size=3, pad=1)
  File "../opt/caffe/python/caffe/model_libs.py", line 618, in CreateMultiBoxHead
    net[norm_name] = L.Normalize(net[from_layer], scale_filler=dict(type="constant", value=normalizations[i]),
  File ..r/opt/caffe/python/caffe/net_spec.py", line 188, in __getitem__
    return self.__getattr__(item)
  File ".../opt/caffe/python/caffe/net_spec.py", line 182, in __getattr__
    return self.tops[name]
KeyError: 'conv4_3'

thank you.

**Comment by weiliu89** [comment]
The script is **not** fully tested for model which is trained with batch normalization (BN), you should make adjust to certain settings if you want to try ResNet.

For your specific problems, you should change `mbox_source_layers` to layer names you want to use for prediction in ResNet152. And you should use `ResNet152Body(net, from_layer='data', use_pool5=False)`.

**Comment by peternara** [comment]
yes, i already changed "mbox_source_layers" part. 
I try to change  layer names(many time) for prediction in ResNet152. but I have still a error .

I0716 11:52:04.729372  1913 net.cpp:752] Ignoring source layer fc7_relu7_0_split
F0716 11:52:04.730145  1913 net.cpp:765] Cannot copy param 0 weights from layer 'conv6_1'; shape mismatch.  Source param shape is 256 1024 1 1 (262144); target param shape is 256 2048 1 1 (524288). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.

thank you.

**Comment by weiliu89** [comment]
It is weird that you have `fc7_relu7_0_split`, which is not part of ResNet152 (assuming you download it from [here](https://github.com/KaimingHe/deep-residual-networks)). Make sure you are not loading from a previously saved wrong snapshot.

**Comment by peternara** [comment]
thank you.
this problem remained previously logs(model...etc).  I delete this log. 
i try to again.
fortunately, above error not generating! 

but, when resnet execute for training, it generate out of gpu memory.
so, it not generate when I excute using 8 core gpu. 
i running(train) and yet not out of memory.

and
I have a questions.
l wonder optimal layer names  to use for prediction in ResNet152.
how to select optimal ResNet152 ' layer name.

sorry, I am not good at English. and Thank you for the reply.

**Comment by weiliu89** [comment]
ResNet has a problem of consuming a lot of memory. I think usually people use ResNet101 for detection. According to my experience, it's performance is similar to VGG (at least on VOC0712) within the SSD framework.

For optimal layers, you can find corresponding layers which has similar feature map size as the ones used in VGG.

**Comment by peternara** [comment]
tankyou~^^
