### ISSUE TITLE
Train net output #0: mbox_loss = nan (* 1 = nan loss)

### ISSUE THREAD

**Issue by VanitarNordic** [weiliu89/caffe#432]
Hello,

At the beginning I was getting **out of memory** error.

Then I reduced the batch size from 32 to 16.

After that I **always** get: 

`Train net output #0: mbox_loss = nan (* 1 = nan loss)`

even if I put 0 as the learning rate.

My GPU has 6G memory.

How can I solve this?!

**Comment by mauione1** [comment]
I think you can reduce down the batch size 8 further. I had the same issue and I solved reducing the batch size.
