### ISSUE TITLE
location regression

### ISSUE THREAD

**Issue by abdallah95** [weiliu89/caffe#434]
Hi @weiliu89 
I was wondering how much location regression is useful in your model. The output space is already discretized into a default set of bound boxes, so isn't it enough to compute the confidence, and the object location would be the corresponding default bounding box? Somehow similar to a sliding window implemented as a convolution operation.

I think it's useful in case you have no information on the aspect ratios of the objects in the dataset, which is the case in VOC dataset, but it would be enough to compute only the confidence otherwise, right?

**Comment by weiliu89** [comment]
I think it is necessary to have the regression part. The default boxes cannot cover all possible locations and shapes of objects. Faster R-CNN has a section discussing the case when there is no location regression; and the result is much worse. I think SSD is the same in the regard. This might be the main reason that the regression based method (originated from MultiBox) is better than traditional sliding window method (HOG or DPM), other than the more powerful CNN feature.

**Comment by abdallah95** [comment]
Yes it makes sense. Actually I tried it on my dataset and I got ~15% less mAP(hopefully I did it correctly). Thank you for explanation.
