### ISSUE TITLE
out of memory error fix

### ISSUE THREAD

**Issue by VanitarNordic** [weiliu89/caffe#435]
I have a GPU with 6G memory. Cuda-8.0, CuDNN-5.1, Ubuntu 16.04

Training contains 250 images and test contains 50 images.

I constantly get out of memory error from the beginning. What should I do?

**Comment by VanitarNordic** [comment]
I could solve the case by reducing the traing/test images' size. usually they should be around 250 * 250 to 300 * 300 pixel. I hope it could be helpful for anybody who may face this problem afterwards.

**Comment by vipinpillai** [comment]
Reducing the batch size can also help:
Change the following values (originally 32) in ssd_pascal.py :
batch_size = 16 
accum_batch_size = 16

**Comment by VanitarNordic** [comment]
@vipinpillai 
Thank you very much. one question. have you worked with PVANET+ also?

**Comment by vipinpillai** [comment]
@VanitarNordic 
No, I haven't.
