### ISSUE TITLE
is this fine-tuning or training from scratch?

### ISSUE THREAD

**Issue by VanitarNordic** [weiliu89/caffe#439]
@weiliu89 

The tutorial you described to train the SSD, is based on fine-tune the model (`VGG_ILSVRC_16_layers_fc_reduced.caffemodel`) and Train the SSD, or it is based to train the SSD from scratch?

if your intention was fine-tuning, then `VGG_ILSVRC_16_layers_fc_reduced.prototxt` should be uploaded somewhere before training and rename some layers, isn't it?

**Comment by weiliu89** [comment]
Please check README.md

**Comment by VanitarNordic** [comment]
@weiliu89 
Actually I read but this question raised up for me. I appreciate if you make me clear. Thanks.
