### ISSUE TITLE
running speed of ssd300x300 and ssd500x500 for batch=1

### ISSUE THREAD

**Issue by hengck23** [weiliu89/caffe#44]
Hi, according to:

-https://github.com/weiliu89/caffe/issues/34
-https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/score_ssd_pascal.py

The speed reported, e.g. for ssd500x500 is FPS = no_of_test_imgaes/total_time = 4952/67 = 74.
However, i think this is for "test_batch_size = 8" in score_ssd_pascal.py.

In my own measurement, which use my own timing function:
	START_TIMER();
		net.Forward(); 
		cudaThreadSynchronize();
	time  += END_TIMER();

I am getting the below for titan-X: 
voc07+12_ssd300x300	:  30	  ms or  33.3 fps
voc07+12_ssd500x500	: 121 ms or  8.26 fps

Please let me know if my measurement are reasonable.
Also I think the speed from faster-RCNN website and paper  is for batch=1.
YOLO website and paper reports similarly as SSD using batch>=1.

**Comment by weiliu89** [comment]
Not sure why you use cudaThreadSynchronize. Yes, the speed is measured with batch size of 8 as described in the paper and in the script. The reason that faster R-CNN do batch = 1 is because it doesn't resize the image to square as is done in both YOLO and SSD. I think, when referring to classification speed of a network (e.g. AlexNet or VGGNet), it usually also uses batch size > 1.

**Comment by hengck23** [comment]
@weiliu89 
Thank you for the reply.
Calling cudaThreadSynchronize() will make the CPU wait till all previously launched kernels terminate.
Hence this is the best way to measure the time taken to process one image "completely".

Now I am interested in detection speed, i.e. time per image.
E.g. in real-time surveillance camera, car camera, web-cam application , the image arrives one at a time.
So batch=1 gives me an estimate of the complexity of the network. 
(another way is to consider the FLOPS of the network)

**Comment by weiliu89** [comment]
I understand that for video batch_size = 1, it has a much lower FPS as you can see from the webcam demo. It is always faster to process multiple images at a time than processing one image for several iterations. But I think it is more of a hardware problem or real time scheduling problem, which by themselves might be an interesting research area.

**Comment by youngwanLEE** [comment]
@hengck23 Why don't you modify ssd_detect.cpp for time-measurement ? I think ssd_detect.cpp is better than score_ssd_pascal.py with respect to time.

**Comment by leejiajun** [comment]
@hengck23 @weiliu89 How can I get the fps of ssd? Thank you

**Comment by hengck23** [comment]
@leejiajun 
I am using CPU clock

``------------------------------------------------------------------
LARGE_INTEGER STIME;
LARGE_INTEGER ETIME;   
inline float START_TIMER(){  
	LARGE_INTEGER TICKS_PER_SEC;
	QueryPerformanceFrequency(&TICKS_PER_SEC); 
	QueryPerformanceCounter(&STIME); 
	return -1;
};

inline float END_TIMER(){ 
	LARGE_INTEGER TICKS_PER_SEC;
	QueryPerformanceFrequency(&TICKS_PER_SEC); 
	QueryPerformanceCounter(&ETIME); 
	float time = (double)(ETIME.QuadPart-STIME->QuadPart)/TICKS_PER_SEC.QuadPart; //time is in sec
	return time;
};
``------------------------------------------------------------------
 START_TIMER();
net.Forward();
cudaThreadSynchronize();  //wait for all gpu threads to finish
time += END_TIMER();

**Comment by leejiajun** [comment]
@hengck23  Thank you.

**Comment by ujsyehao** [comment]
@hengck23 Hi , I have a problem about speed between different batch size, I submit a new issue, please refer to it #832
