### ISSUE TITLE
problem with the MatchBBox function in bbox_util.cpp

### ISSUE THREAD

**Issue by bluedlw** [weiliu89/caffe#443]
in the bipartite matching part, (find the most overlapped gt and cooresponding predictions), 
where it looks like below:
if (it->second[j] > max_overlap) {
          // If the prediction has not been matched to any ground truth,
          // and the overlap is larger than maximum overlap, update.
          max_idx = i;
          max_gt_idx = j;
          max_overlap = it->second[j];
}

should it be if(it->second[j] > overlap_threshold && it->second[j] > max_overlap)?
otherwise the max matching bboxes may have the overlap below overlap_threshlod.

**Comment by weiliu89** [comment]
The per-prediction match step does that. The purpose of the bipartite matching step is to ensure that each gt box has a matched default box. Although the greedy implementation might not be exactly the true bipartite matching, in practice it seems to work well.

**Comment by bluedlw** [comment]
@weiliu89 
The per-prediction match checks if the default box has matched a gt box, as below: 
if ((*match_indices)[i] != -1) {
          // The prediction already has matched ground truth or is ignored.
          continue;
}
suppose a situation,  only one gt box, and it has overlop with each default box less than
overlap_threshold. After MatchBBox, only one default box and gt box match, and their
overlap is under overlap_threshold.
I will check if all the default boxes cover all possible gt boxes.

**Comment by weiliu89** [comment]
That is exactly what MatchBBox is supposed to do for the case you described. It always make sure that there is at least one default bbox be responsible for a gt bbox (even if the overlap is below the threshold).

**Comment by bluedlw** [comment]
@weiliu89 Thanks very much.
