### ISSUE TITLE
mscoco scripts missing

### ISSUE THREAD

**Issue by siddharthm83** [weiliu89/caffe#45]
@weiliu89, I was trying to follow your steps for training on mscoco. 
As per: https://github.com/weiliu89/caffe/tree/ssd/data/coco
`# Check scripts/batch_split_annotation.py and change settings accordingly.`
`python scripts/batch_split_annotation.py`
`# Create the minival2014_name_size.txt and test-dev2015_name_size.txt in $CAFFE_ROOT/data/coco`
`python scripts/batch_get_image_size.py`

However I can't find `batch_split_annotation.py` or `batch_get_image_size.py` in your repo under scripts folder. Is it stored in a different location?

**Comment by weiliu89** [comment]
It is located at [another repo](https://github.com/weiliu89/coco/tree/dev/PythonAPI/scripts).
The README.md has all the necessary information :)

**Comment by siddharthm83** [comment]
Thanks @weiliu89, my mistake. I missed the `git checkout dev` part and was looking at master.
