### ISSUE TITLE
AttributeError while running ssd_pascal.py

### ISSUE THREAD

**Issue by JunchangFan** [weiliu89/caffe#458]
when i run ssd_pascal.py i get this:
Traceback (most recent call last):
  File "examples/ssd/ssd_pascal.py", line 273, in <module>
    mining_type = P.MultiBoxLoss.MAX_NEGATIVE
  File "/home/fantasi/caffe-ssd/python/caffe/net_spec.py", line 240, in __getattr__
    return getattr(getattr(caffe_pb2, name + 'Parameter'), param_name)
AttributeError: type object 'MultiBoxLossParameter' has no attribute 'MAX_NEGATIVE'

can you tell me how to fix it?
thanks for help

i know the reason ,when i export the PYTHONPATH ,it works.
thanks~~

**Comment by zhanglijun95** [comment]
Hello! How did you solve this problem? Could you give me more details? I met this as well.
