### ISSUE TITLE
Anything I need to notice if I'd like to add a new layer?

### ISSUE THREAD

**Issue by wk910930** [weiliu89/caffe#470]
Dear Wei,

I would like to implement my own layers based on ssd. Since ssd supports multi-gpu training, I was wondering if there is anything (e.g. synchronize gradient) I need to take care of when adding new layers?

Thanks!
Kun

**Comment by wliu-nuro** [comment]
What layer do you want to add? You can refer to existing layers in Caffe. The synchronize gradient thing is handled in solver.cpp I think so you normally don't need to care about that.

**Comment by weiliu89** [comment]
What layer do you want to add? You can refer to existing layers in Caffe. The synchronize gradient thing is handled in solver.cpp I think so you normally don't need to care about that.

**Comment by wk910930** [comment]
I am considering adding some learnable layers. Thanks! Closing the issue.
