### ISSUE TITLE
How are confidence scores arranged?

### ISSUE THREAD

**Issue by wk910930** [weiliu89/caffe#478]
Dear Wei,

Say, for the layer **conv4_3_norm_mbox_conf** (before perm operation), the output has 4*21=84 channels. I was wondering how are these conf arranged? There are two possible ways I can think of:

1. Along prior box, which means the first 21 channels is for the first prior box, and the second 21 channels for the second prior box, and so on;
2. Along class, which means the first 4 channels is for 4 different prior boxes for the first class, and the second 4 channels is for 4 different prior boxes for the second class, and so on.

Which one is correct?

I am sorry, but I am trying to make my question as clear as possible.

Thanks！
Kun

**Comment by weiliu89** [comment]
1 is correct. The reason is because that it is convenient to combine predictions from multiple layers.

**Comment by wk910930** [comment]
Thank you for reply! Closing issue.
