### ISSUE TITLE
How to train SSD 512x512 

### ISSUE THREAD

**Issue by youngwanLEE** [weiliu89/caffe#487]
Hi, Wei.

I tried to train SSD 512x512. However, I couldn't find the SSD512x512 script. So I guessed parameters and trained the SSD512x512 that resulted in mAP 65% on VOC2007.

Could you let me know which parameters should be modified for SSD512x512? 

I guessed

resize_width = 512
resize_height = 512
min_dim = 512

**Comment by silvaph** [comment]
Hi, @youngwanLEE, 

You can find the script in [models section](https://github.com/weiliu89/caffe/tree/ssd#models). Just download one of them and you will find the script to create the prototxt.

I've tried it before and I could train it, however, it didn't show the detection_eval and when I put the layer of it on the test.prototxt I keep receiving errors or the output it isn't the expected one.

**Comment by youngwanLEE** [comment]
@silvaph thanks 👍

**Comment by ithink2** [comment]
@silvaph The reason of no detection_eval is the test net appends a silent layer behind the detection_out layer.
<img width="521" alt="screen shot 2017-04-19 at 3 30 57 pm" src="https://cloud.githubusercontent.com/assets/4011705/25168258/695a1a54-2515-11e7-92a6-0ff127544558.png">

If you want it output detection_eval each time, try to change it to detection_eval layer just like in `ssd/ssd_pascal.py`

**Comment by silvaph** [comment]
Thans @ithink2, it solved my problem.

**Comment by bot66** [comment]
> Hi, @youngwanLEE,
> 
> You can find the script in [models section](https://github.com/weiliu89/caffe/tree/ssd#models). Just download one of them and you will find the script to create the prototxt.
> 
> I've tried it before and I could train it, however, it didn't show the detection_eval and when I put the layer of it on the test.prototxt I keep receiving errors or the output it isn't the expected one.

thank you !
