### ISSUE TITLE
./data/VOC0712/create_data.sh

### ISSUE THREAD

**Issue by SpecialM2580** [weiliu89/caffe#49]
Traceback (most recent call last):
  File "/home/ilab/Documents/SSD/caffe/data/VOC0712/../../scripts/create_annoset.py", line 7, in <module>
    from caffe.proto import caffe_pb2
ImportError: No module named caffe.proto
Traceback (most recent call last):
  File "/home/ilab/Documents/SSD/caffe/data/VOC0712/../../scripts/create_annoset.py", line 7, in <module>
    from caffe.proto import caffe_pb2
ImportError: No module named caffe.proto
---------------------------------------------------------------------
make test, make runtest are all fine, and i follow the step strictly please help

**Comment by weiliu89** [comment]
You should include $CAFFE_ROOT/python into your PYTHONPATH environment variable

**Comment by SpecialM2580** [comment]
THANKS!  I‘'m a newbee~, never add any PATH before when I was using caffe. Thanks very much!!

**Comment by MuhammadAsadJaved** [comment]
@SpecialM2580  @weiliu89  I have the same problem. i am using MobileNet caffe and creating imdb and face same problem. Which path you added? because we did not install caffe separately so i am not sure where is caffe.
