### ISSUE TITLE
How can run ssd_pascal_video/webcam by 07++12+COCO (SSD512) ?

### ISSUE THREAD

**Issue by mintlatte** [weiliu89/caffe#495]
I want to run ssd_webcam & video by ssd512.
So I downloaded 07++12+COCO model and modified code of ssd_pascal_video like finetune_ssd_pascal_512.py. (AddExtraLayers, resize_width/height, job_name ... etc)
But when I run that, this error occurred

Cannot copy param 0 weights from layer 'conv8_2_mbox_loc'; shape mismatch.  Source param shape is 24 256 3 3 (55296); target param shape is 16 256 3 3 (36864). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.

How can I solve this error?
Is any other things I have to modify or rename?

Thank you.

**Comment by fighting-liu** [comment]
It seems there are 6 default boxes associated with 'conv8_2', but your target default boxes is only 4 for 'conv8_2', so it caused shape mismatch when you are finetuning the network.

**Comment by mintlatte** [comment]
Thank you!
