### ISSUE TITLE
Bugs in CMake files

### ISSUE THREAD

**Issue by xmfbit** [weiliu89/caffe#5]
Hi, @weiliu89 . You did a great job! I have learned much from your work. Thank you.
However, I think the CMake files should be updated. When I tried to build the Caffe-SSD project using CMake, errors occurred which informed me that `cv::VideoCapture` and `boost::regex` were undefined references. So I changed the file `/cmake/Dependencies.cmake` to fix the problems.
In line 5, add `regex` at the end.

```
find_package(Boost 1.46 REQUIRED COMPONENTS system thread filesystem regex)
```

In line 72, add `videoio` at the end.

```
find_package(OpenCV QUIET COMPONENTS core highgui imgproc imgcodecs videoio)
```

Thank you for your work!

**Comment by weiliu89** [comment]
@xmfbit Thank you for your interest in the SSD work :) I am glad it helps your research.

I haven't used cmake, but I did add those two dependencies in the Makefile. Thanks for pointing out the problem! I have fixed the problem :)
