### ISSUE TITLE
ssd_pascal_video.py

### ISSUE THREAD

**Issue by AndrewZhao** [weiliu89/caffe#50]
When I run ssd_pascal_video.py, it reports this error:

**Traceback (most recent call last):
  File "./examples/ssd/ssd_pascal_video.py", line 90, in <module>
    'video_type': P.VideoData.VIDEO,
  File "/home/zhaoboya/SSD/caffe/python/caffe/net_spec.py", line 240, in __getattr__
    return getattr(getattr(caffe_pb2, name + 'Parameter'), param_name)
AttributeError: type object 'VideoDataParameter' has no attribute 'VIDEO'**

My environment is python3,ubuntu14.04,cuda7.5 and titanx

**Comment by weiliu89** [comment]
You should `make py` again

**Comment by AndrewZhao** [comment]
I try to make py again,but the error still occur...
The VideoDataParameter class has this attribute: There is not 'VIDEO'..
a.ByteSize(                  a.__getstate__(
a.Clear(                     a.__gt__(
a.ClearExtension(            a.__hash__(
a.ClearField(                a.__init__(
a.CopyFrom(                  a.__instancecheck__(
a.DESCRIPTOR                 a.__itemsize__
a.DEVICE_ID_FIELD_NUMBER     a.__le__(
a.FindInitializationErrors(  a.__lt__(
a.FromString(                a.__module__
a.HasExtension(              a.__mro__
a.HasField(                  a.__name__
a.IsInitialized(             a.__ne__(
a.ListFields(                a.__new__(
a.MergeFrom(                 a.__prepare__(
a.MergeFromString(           a.__qualname__
a.ParseFromString(           a.__reduce__(
a.RegisterExtension(         a.__reduce_ex__(
a.SerializePartialToString(  a.__repr__(
a.SerializeToString(         a.__setattr__(
a.SetInParent(               a.__setstate__(
a.VIDEO_TYPE_FIELD_NUMBER    a.__sizeof__(
a.VideoType                  a.__slots__
a.WEBCAM                     a.__str__(

**Comment by weiliu89** [comment]
Did you see 'VIDEO' in caffe.proto?

**Comment by AndrewZhao** [comment]
no,there is no attribute 'VIDEO' in caffe.proto calss.
caffe.proto.__cached__         caffe.proto.__lt__(
caffe.proto.__class__(         caffe.proto.__name__
caffe.proto.__delattr__(       caffe.proto.__ne__(
caffe.proto.__dict__           caffe.proto.__new__(
caffe.proto.__dir__(           caffe.proto.__package__
caffe.proto.__doc__            caffe.proto.__path__
caffe.proto.__eq__(            caffe.proto.__reduce__(
caffe.proto.__file__           caffe.proto.__reduce_ex__(
caffe.proto.__format__(        caffe.proto.__repr__(
caffe.proto.__ge__(            caffe.proto.__setattr__(
caffe.proto.__getattribute__(  caffe.proto.__sizeof__(
caffe.proto.__gt__(            caffe.proto.__spec__
caffe.proto.__hash__(          caffe.proto.__str__(
caffe.proto.__init__(          caffe.proto.__subclasshook__(
caffe.proto.__le__(            caffe.proto.caffe_pb2
caffe.proto.__loader__

**Comment by weiliu89** [comment]
How about in the original [caffe.proto](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/proto/caffe.proto#L1560) file?

Another choice is to modify the [ssd_detect.cpp](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_detect.cpp) to get video as input and process it, which should be relatively easy.

**Comment by AndrewZhao** [comment]
in the origin caffe.proto file,there is 
```
message VideoDataParameter{
  enum VideoType {
    WEBCAM = 0;
    VIDEO = 1;
  }
  optional VideoType video_type = 1 [default = WEBCAM];
  optional int32 device_id = 2 [default = 0];
  optional string video_file = 3;
}
```
If i want to test the speed of SSD, should I make a video which fps is 58?

**Comment by weiliu89** [comment]
It is weird. Probably it is some problem with Python 3. I am using Python 2.7, which works fine. You could try to `make clean` and then make again.

And I think you can just use normal video.

**Comment by AndrewZhao** [comment]
@weiliu89 Thank you for the reply. 
I have tried to `make clean`, but it doesn't works..Maybe there is some problems between python2 and python3 I haven't seen.
In the ssd_detect.cpp, where should I modify in order to get a video as input?My C++ is poor, are the tutorials?

**Comment by weiliu89** [comment]
I have modified ssd_detect.cpp so that it can also take video as input. You can `git pull` to get the latest code. For details, please checkout at ca8c158.

Notice: The code currently only process one image at a time, which cannot reach 58 FPS. 58 FPS is measured with batch size of 8.

**Comment by AndrewZhao** [comment]
Thank you very much~
