### ISSUE TITLE
Error during building libcaffe on windows 10

### ISSUE THREAD

**Issue by mintlatte** [weiliu89/caffe#516]
I have installed Caffe & SSD on windows 10 using visual studio 2015.
(I followed this route / http://dtmoodie.blogspot.kr/2016/09/getting-caffe-running-on-windows-with.html?m=1)
I finished making solution by using cmake.
But when I built solution, there were several error.

major error (in libcaffe)
1. C3646 /  'base_type' : unknown override specifier 
2. C4430  /  missing type specifier - int assumed. Note: C++ does not support default-int 
both occured in severity_logger.hpp (was in boost/log/source/)    line 75

related error
cannot open input file '~/libcaffe.lib'
caffe.bin, classification, compute_image_mean ,etc.

How can I solve this problem?
Please help me if anyone has solved this problem.

Thank you

**Comment by roipony** [comment]
I encountered the same problem. 
@mintlatte you solved the errors?

**Comment by mintlatte** [comment]
@roipony umm... I've solved it temporarily...
In the code of BVLC, 'LOG(blabla~)'(usually in .cu files) macro referred to glog's macro.
But in the dtmoodie, not using glog, 'LOG~' used boost's  LOG macro.
I thought this caused that error, so I've commented all of that code.
(including 'INSTANTIATE_LAYER~ '. Some of that may caused same error too)

But I have another error, like this
error LNK2001: unresolved external symbol "void __cdecl caffe ~" 

If you've solved this problem, Please let me know how to solve it.

**Comment by mintlatte** [comment]
@roipony Sorry. I misunderstood the error.
INSTANTIATE_LAYER didn't have problem.
(if this code had been commented, it cause lnk2001 error)

Instead, in common.hpp, there was code using LOG~
#define NOT_IMPLEMENTED LOG(fatal) << "Not Implemented Yet"

So comment the code using NOT_IMPLEMENTED
ex) argmax_layer.hpp

After that, maybe you can comfile libcaffe.

**Comment by roipony** [comment]
@mintlatte I installed caffe ssd for windows from the following repo:
https://github.com/conner99/caffe

Before build follow the instructions here:
https://github.com/conner99/caffe/issues/20

Good luck

**Comment by mintlatte** [comment]
@roipony Thank you so much! I will try it.

**Comment by mintlatte** [comment]
I've solved this problem.
