### ISSUE TITLE
the top shape of output layer is wrong in example/ssd_detect.ipynb when batch_size > 1 

### ISSUE THREAD

**Issue by hexiaoyi95** [weiliu89/caffe#522]
### Issue summary
i am using example/ssd_detect.ipynb to do forward and when batch_size >1,the top shape of the output layer still is 1x1x*x7 , Is something wrong with the DetectionOutput layer definition?

**Comment by abhisheksgumadi** [comment]
Yes I saw this as well. So, the output data structure basically holds all the bounding boxes from all the images of the batch. The outer most dimension will remain as 1 as you observed. To be able to associate the bounding box to a particular image in the input batch look at the label dimension. If you print it it would like something like [0,0,0,0,1,1,1,2,2,3,3,3,3,...31,31] for a batch size of 32. So the ouput is basically a dump of all output bounding boxes and you have to parse them based on the labels.

**Comment by hexiaoyi95** [comment]
@abhisheksgumadi  I review the source code of the 'detection_out' layer and confirm your answer is right. Thank you!

**Comment by jinxuan777** [comment]
@hexiaoyi95 @abhisheksgumadi @weiliu89 , I try to do forward with batch_size>1 and find that when batch = 2 the computation time consumption is twice that of batch = 1.No acceleration， is this reasonable?

**Comment by brat-eek** [comment]
@hexiaoyi95 @abhisheksgumadi Can you tell me how exactly are you accessing the label dimension. I get full detections for my batch size of 8, but cannot split it per image. Also I don't see a list like @abhisheksgumadi mentioned while following ssd_detect.ipynb 

Thanks in advance
