### ISSUE TITLE
AttributeError: 'module' object has no attribute 'LabelMap'

### ISSUE THREAD

**Issue by Yeatz** [weiliu89/caffe#523]
Traceback (most recent call last):
  File "/home/lab/caffe-ssd/data/addTruckCar/../../scripts/create_annoset.py", line 107, in <module>
    label_map = caffe_pb2.LabelMap()
 AttributeError: 'module' object has no attribute 'LabelMap'

 lab@lab:~/caffe-ssd$ echo $PYTHONPATH
 /home/lab/caffe-ssd/python:/home/lab/caffe/python:/home/lab/caffe-ssd/python::/home/lab/py-faster-rcnn/lib:  /home/lab/py-faster-rcnn/caffe-fast-rcnn/python

Hi, weiliu. I met the problem when I bash create_data.sh. and I have added the ssd-branch caffe which I named caffe ssd into the PYTHONPATH. I have also regit the ssd branch code and rebuilt them just few days ago. But I still can't make this problem out.

**Comment by Yeatz** [comment]
@weiliu89 sorry to bother. but I really have tried every possibility, could you please give me some advice.

**Comment by Yeatz** [comment]
sys.path.append("/home/lab/caffe-ssd/python")
I have also added  below words in the file create_annoset.py. But it doesn't seem to work.

**Comment by weiliu89** [comment]
Your PYTHONPATH seems to have two `:` and also a space.

Have you tried `export PYTHONPATH=/home/lab/caffe-ssd/python` only?

**Comment by Yeatz** [comment]
@weiliu89   thanks for your reply very much.
The ssd-branch could really work two weeks before and I have even trained  a model using my own data. But the error appeared somehow someday and I can't find the reason.

   lab@lab:~$ echo $PYTHONPATH
     /home/lab/caffe-ssd/python
I have tried the way you refered and above is my PythonPath. But the same error still there.
Also, I have tried to used the VOC data as your instruction, and then met the same error when I bash create_data.sh.
What's more, I have tried below command

lab@lab:~/caffe-ssd$ sudo python examples/ssd/ssd_pascal.py
[sudo] password for lab: 
Traceback (most recent call last):
  File "examples/ssd/ssd_pascal.py", line 3, in <module>
    from caffe.model_libs import *
ImportError: No module named model_libs

I have found that this is because that there is no file model_libs.pyn in the content ~/caffe-ssd/python/caffe. I don't know if this problem matters to the previous problem. Could you give me some more advices please?

**Comment by weiliu89** [comment]
It looks like a system configuration problem. The code has not been changed for a long time at GitHub.

**Comment by Yeatz** [comment]
OMG! It looks liske that I have to reinstall the system. thanks for your advices.

**Comment by Yeatz** [comment]
I am using ubuntu 14.04.I gited the ssd branch caffe and met the problem below when I bash caffe-ssd/data/VOC0712/create_data.sh.(I named the ssd branch caffe caffe-ssd)

Traceback (most recent call last): File "/home/lab/caffe-ssd/data/VOC0712/../../scripts/create_annoset.py", line 107, in label_map = caffe_pb2.LabelMap() AttributeError: 'module' object has no attribute 'LabelMap'

this is my PYTHONPATH:

lab@lab:~$ echo $PYTHONPATH /home/lab/caffe-ssd/python

I have also added below words in the file create_annoset.py. But it doesn't seem to work.

sys.path.append("/home/lab/caffe-ssd/python")

**Comment by Yeatz** [comment]
accept
I guess maybe problem is that the ssd-branch I've git is original version ssd. I d So I download the ssd-branch zip from github

https://github.com/weiliu89/caffe/tree/ssd

and unzip it.Then I met a new problem when I bash create_data.sh like below:

no module named _caffe

though that I could import caffe in the python shell. I have referred that this problem came up due to the $PYTHONPATH confusion,Then I add the below words in the document caffe_root/scripts/create_annosets.py:

sys.path.insert(0,"YOUR_SSD_BRANCH_CAFFE/python")

all done.
