### ISSUE TITLE
Can I get older version pre-trained models?

### ISSUE THREAD

**Issue by mintlatte** [weiliu89/caffe#524]
I am trying to run ssd_pascal_video & webcam on windows. (VOC0712  - SSD_300x300)
* I got the code from [https://github.com/conner99/caffe](url)

But when I run .py files, I got some error. like this

`Cannot copy param 0 weights from layer 'conv4_3_norm_mbox_loc'; shape mismatch.  Source param shape is 16 512 3 3 (73728); target param shape is 12 512 3 3 (55296). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.`

I think that this error occurred because of differences between .py code's net and pre-trained model's net.
I downloaded pre-trained model from your Readme.md and this files had been changed before.
So, can you give me other link of older version? or Can you change above code as it matches to new trained version?

Thank you.

**Comment by mintlatte** [comment]
I've solved this problem by changing code.

**Comment by Anhaoxu** [comment]
@mintlatte Hello, I meet the same problem,when I use ssd_pascal.py,it's ok, but when running the ssd_pascal_video.py,the mistake occured,can you tell me how to solve the problem? Thank you!

**Comment by mintlatte** [comment]
@Anhaoxu 
I changed ssd_pascal_video.py code.
First, AddExtraLayers
`def AddExtraLayers(net, use_batchnorm=True):
    use_relu = True

    # Add additional convolutional layers.
    from_layer = net.keys()[-1]
    # TODO(weiliu89): Construct the name using the last layer to avoid duplication.
    out_layer = "conv6_1"
    ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 256, 1, 0, 1)

    from_layer = out_layer
    out_layer = "conv6_2"
    ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 512, 3, 1, 2)

    from_layer = out_layer
    out_layer = "conv7_1"
    ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 128, 1, 0, 1)

    from_layer = out_layer
    out_layer = "conv7_2"
    ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 256, 3, 1, 2)

    from_layer = out_layer
    out_layer = "conv8_1"
    ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 128, 1, 0, 1)

    from_layer = out_layer
    out_layer = "conv8_2"
    ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 256, 3, 0, 1)

    from_layer = out_layer
    out_layer = "conv9_1"
    ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 128, 1, 0, 1)

    from_layer = out_layer
    out_layer = "conv9_2"
    ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 256, 3, 0, 1)

    # Add global pooling layer.
    # name = net.keys()[-1]
    # net.pool6 = L.Pooling(net[name], pool=P.Pooling.AVE, global_pooling=True)

    return net`

Second, mbox_source_layers & max_sizes & 	aspect_ratios & clip(mayby)
`mbox_source_layers = ['conv4_3', 'fc7', 'conv6_2', 'conv7_2', 'conv8_2', 'conv9_2']`
`max_sizes = [min_dim * 20 / 100.] + max_sizes`
`aspect_ratios = [[2], [2, 3], [2, 3], [2, 3], [2], [2]]`
`clip = False`

If you change code like this, you will be able to run that.

**Comment by Anhaoxu** [comment]
@mintlatte Thank you, it worked,so how the py script and prototxt are inconsistent, what is the key problem ?

**Comment by mintlatte** [comment]
@Anhaoxu Maybe, in this repo, code & model was changed, but window ver. code & files didn't reflect that. I think that is reason.
