### ISSUE TITLE
What does the `ft` suffix mean for the pretrained models?

### ISSUE THREAD

**Issue by albanie** [weiliu89/caffe#525]
Apologies if this is obvious, I couldn't find a reference in the code/paper.

**Comment by spotofleopard** [comment]
should be fine tuning

**Comment by albanie** [comment]
Do you know which data the fine tuning refers to or where it is referenced in the code or the paper?

**Comment by albanie** [comment]
Ah, I found the reference - the script is contained in the pretrained model archives. Thanks!
