### ISSUE TITLE
Why not set clip to true by default in PriorBoxParameter?

### ISSUE THREAD

**Issue by wk910930** [weiliu89/caffe#526]
Dear @weiliu89 ,

 The [clip](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/proto/caffe.proto#L1406) in `PriorBoxParameter` is set to `false` by default. Since it makes sense to always guarantee the prior to be within the valid range (*i.e.* [0, 1]). I cannot think of one situation where we do not need `clip`. What does it mean when we have some priors larger than 1 (or smaller than 0)?

Could you share your thoughts on it? There might be something I am missing.

Thanks!
Kun

**Comment by weiliu89** [comment]
It was true at the first version, but was changed to false later. It has better translation invariance property and performs slightly better

**Comment by wk910930** [comment]
Thanks! Closing the issue.
