### ISSUE TITLE
ERROR by create_annoset.py : when i'm using "sh create_data.sh" to make lmdb data

### ISSUE THREAD

**Issue by dongmingyang** [weiliu89/caffe#527]
I'm using "sh create_data.sh" to make lmdb data
---------------------------------------------------
It's the only change:

#cur_dir=$(cd $( dirname ${BASH_SOURCE[0]} ) && pwd )
 cur_dir=$HOME/ydm/ssd/caffe-ssd/data/VOC0712
---------------------------------------------------
I got this ERRON msg:

/home/shibiaoxu/ydm/ssd/caffe-ssd/build/tools/convert_annoset --anno_type=detection --label_type=xml --label_map_file=/home/shibiaoxu/ydm/ssd/caffe-ssd/data/VOC0712/../../data/VOC0712/labelmap_voc.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/shibiaoxu/ydm/ssd/caffe-ssd/data/VOCdevkit/ /home/shibiaoxu/ydm/ssd/caffe-ssd/data/VOC0712/../../data/VOC0712/test.txt /home/shibiaoxu/ydm/ssd/caffe-ssd/data/VOCdevkit/VOC0712/lmdb/VOC0712_test_lmdb
Traceback (most recent call last):
  File "/home/shibiaoxu/ydm/ssd/caffe-ssd/data/VOC0712/../../scripts/create_annoset.py", line 159, in <module>
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
/home/shibiaoxu/ydm/ssd/caffe-ssd/build/tools/convert_annoset --anno_type=detection --label_type=xml --label_map_file=/home/shibiaoxu/ydm/ssd/caffe-ssd/data/VOC0712/../../data/VOC0712/labelmap_voc.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/shibiaoxu/ydm/ssd/caffe-ssd/data/VOCdevkit/ /home/shibiaoxu/ydm/ssd/caffe-ssd/data/VOC0712/../../data/VOC0712/trainval.txt /home/shibiaoxu/ydm/ssd/caffe-ssd/data/VOCdevkit/VOC0712/lmdb/VOC0712_trainval_lmdb
Traceback (most recent call last):
  File "/home/shibiaoxu/ydm/ssd/caffe-ssd/data/VOC0712/../../scripts/create_annoset.py", line 159, in <module>
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
----------------------------------------------------
I will be thankful if u can provide any help.  : )

**Comment by dongmingyang** [comment]
@weiliu89  Sorry to bother...could u please give me some advise with my error ?

**Comment by dongmingyang** [comment]
problem solved.
I forgot to change the code in Makefile.config.
--------------
BLAS := mkl
--------------
then, remake caffe

**Comment by MatrixPlayer** [comment]
after ssd compiled, there is not build directory in the caffe_root directory, but the path of cmd include "build" directory in the  line 142 of create_annoset.py! you should delete the "build/" in the line 142!
![image](https://user-images.githubusercontent.com/12170233/55272299-6a931500-52f5-11e9-9e3a-5e3865a3683c.png)
