### ISSUE TITLE
How do we determine the number of prediction layers, and additional layers after the base network? 

### ISSUE THREAD

**Issue by villanuevab** [weiliu89/caffe#549]
Hello, I have a conceptual question: 

The default box scales and aspect ratios are dependent on m (p. 6), the number of feature maps we "want" to use for prediction; the paper makes it seem like the number of prediction layers is dynamically set to make the final layer take a 1x1 feature map as input (i.e., reducing the feature maps in scale until this point). How is the number of (1) prediction layers, and (2) additional layers after the base layer (since not all of these are prediction layers) set? I could not find this information in the paper.

**Comment by weiliu89** [comment]
The last layer doesn't need to be 1x1. The gist is that it is better to use multiple layers than single layer for detection.

**Comment by villanuevab** [comment]
Thank you for your response! Does this mean that the number of additional layers after the base layer, as well as the number of prediction layers are effectively hyperparameters that we can tune as part of the SSD architecture? And, that as such, we could have stopped at the 3x3 prediction layer as our final layer?

**Comment by weiliu89** [comment]
Yes.
