### ISSUE TITLE
Why add an 'Permute' layer before flattening the output?

### ISSUE THREAD

**Issue by yw155** [weiliu89/caffe#55]
I have two questions: 
1. Why need to convert N * C * H * W to N * H * W * C, but not flattening it directly?
2. The default input image size is 300*300. If I input an image with a different size, do I need to adjust the pad value and the stride value in the convolution and pooling layer respectively?

**Comment by vivohuang** [comment]
hi,@weiliu89 ,i have a problem ,wish you can help me ,thanks!
the matter : when i  cloned Caffe into $CAFFE_ROOT according to your step, i found there existed two caffe file, one  cotained another. So when i compiled ,there was a error.
![bbox_cpp](https://cloud.githubusercontent.com/assets/20606106/17075211/e81fdd82-50be-11e6-99be-d2aa90a3460a.png)
![bbox_util_cpp](https://cloud.githubusercontent.com/assets/20606106/17075212/e8213a9c-50be-11e6-819f-d9ce536f6b69.png)

**Comment by vivohuang** [comment]
hi,@weiliu89 ,i have a problem ,wish you can help me ,thanks!
the matter : when i  cloned Caffe into $CAFFE_ROOT , i found there existed two caffe files, one  cotained another.  when i compiled ,there was a error.
![bbox_cpp](https://cloud.githubusercontent.com/assets/20606106/17075266/2528d2c2-50c1-11e6-990f-2a9014c9e96c.png)
![bbox_util_cpp](https://cloud.githubusercontent.com/assets/20606106/17075267/25eb606c-50c1-11e6-88db-03d9b008e49e.png)

**Comment by weiliu89** [comment]
@yw155 

1) It is to make it easier to combine predictions from multiple layers.
2) You don't have to.

**Comment by yw155** [comment]
Thank you very much

**Comment by yxchng** [comment]
@weiliu89 how does permuting make it easier to combine predictions from multiple layers?
