### ISSUE TITLE
Where's the recent improvements come from?

### ISSUE THREAD

**Issue by yijunCai** [weiliu89/caffe#554]
Hi @weiliu89 
I notice that the mAP for SSD300 trained on 07+12 has reached 77.2%, but in your latest paper(v5) it's still 74.3%. Can you roughly illustrate where the boost comes from? 
Thanks a lot!

**Comment by wk910930** [comment]
I think the author has has explained in the [paper](https://arxiv.org/pdf/1512.02325.pdf).

> We  achieved  even  better  results  using  an  improved  data  augmentation  scheme  in  follow-on
> experiments: 77.2% mAP for 300×300 input and 79.8% mAP for 512×512 input on VOC2007. Please see Sec. 3.6 for details.

**Comment by yijunCai** [comment]
You are right. I just didn't notice that. Sorry to bother @weiliu89 . Thanks a lot @wk910930 !
