### ISSUE TITLE
Why normalized box coordinates in [0,1]?

### ISSUE THREAD

**Issue by alexekkis** [weiliu89/caffe#556]
What is the advantage of using normalized box coordinates that lie in [0,1]?

Since you are using the (cx, cy, w, h) coordinate format for training and are normalizing the targets by the prior box widths and heights anyway, using normalized or absolute coordinates does not matter, the division by the image width or height cancels out. Example for the cx coordinate, where cx and w mean the absolute coordinate values and gt = ground truth:

(cx(gt) / img_width - cx(prior) / img_width) / (w(prior) / img_width) == (cx(gt) - cx(prior)) / w(prior)

i.e. dividing the absolute ground truth and prior coordinates by the image width makes no difference, it results in the same target used for the training.

Am I overlooking something? I'd be grateful for a brief comment!

**Comment by weiliu89** [comment]
The main reason is to make the manipulation of a lot of box operations easy.

**Comment by alexekkis** [comment]
Thanks a lot for taking the time to reply. It's really awesome that you're always helpful when people have questions about your work!
