### ISSUE TITLE
how to evaluate coco test?

### ISSUE THREAD

**Issue by youngwanLEE** [weiliu89/caffe#557]
Hi, Wei.

Recently, I have trained ssd_coco version. 

My questions are

1. What the meaning of detection_eval value which was displayed in training process ?
 for examples, total mAP([0.5:0.05:0.9]), [0.5,0.9]mAP, 0.5mAP(VOC type) and so on referred to as [ COCO metrics](http://mscoco.org/dataset/#detections-eval)

2. How to measure the detection results like [0.5,0.9]mAP, 0.5mAP, 0.75mAP which you demonstrated in your paper.

Thanks in advance.

**Comment by weiliu89** [comment]
1. Only 0.5.

2. I upload the results to COCO eval server. The DetectionOutputLayer can output the detection results in COCO format. Check out [here](https://github.com/weiliu89/caffe/blob/ssd/src/caffe/layers/detection_output_layer.cpp#L416).

**Comment by youngwanLEE** [comment]
Thanks 👍

**Comment by mna12478** [comment]
@youngwanLEE hi, I also want to evaluate on coco dataset, but I didn't find the function which calls the DetectionOutputLayer in ssd network. So how you solve this problem? Thanks.
