### ISSUE TITLE
Questions about DSSD

### ISSUE THREAD

**Issue by youngwanLEE** [weiliu89/caffe#563]
Hi, Wei. 

Recently, I have re-implemented DSSD based on your SSD code.

I just followed your [arxiv paper](https://arxiv.org/abs/1701.06659).

DSSD used 321 resized input and was down-sampled to 161->80->40(a)->20(b)->10(c)->5(d)->3(e)->2(f).

So, when I tried to deconvolve the feature map(f) with kernel_size=4, stride=2, and pad=1 and eltwise sum with (e), shape miss match error occurred. Because  the size of deconvolved feature map(f) is 4. 

My question is how to solve this problem and how to configure deconvolution layer.

Thanks

**Comment by weiliu89** [comment]
Check https://github.com/BVLC/caffe/pull/2213

**Comment by roipony** [comment]
@youngwanLEE 
Can you share the DSSD code/configuration?

Thanks

**Comment by youngwanLEE** [comment]
@roipony I couldn't finish this re-implementation, yet. When I finish this project, I'll share it
