### ISSUE TITLE
couldn't find Minival annotation in COCO dataset 

### ISSUE THREAD

**Issue by cloudfool** [weiliu89/caffe#570]
Wei,

I have downloaded coco dataset from the official website but couldn't find the minival annotation.
Any advice? Thank you.

**Comment by cloudfool** [comment]
solved

**Comment by Anhaoxu** [comment]
@cloudfool Hello, the instances_minival2014 annotation,do you find it ?

**Comment by cloudfool** [comment]
Please refer 
https://github.com/rbgirshick/py-faster-rcnn/blob/master/data/README.md

**Comment by Anhaoxu** [comment]
@cloudfool Thank you, I have two questions ask you for some help.
First, I find some error in create lmdb, there are 7 annotation files in coco:minival2014,test2014,test2015,test-dev2015,train2014,val2014,valminusminival2014. and 4 lmdb files, right? In split the annotation, my test annotation files were created wrongly.like this:
{
  "annotation": [], 
  "image": {
    "coco_url": "http://mscoco.org/images/1", 
    "date_captured": "2013-11-17 10:40:31", 
    "file_name": "COCO_test2014_000000000001.jpg", 
    "height": 480, 
    "id": 1, 
    "license": 4, 
    "width": 640
  }
}
only these information,but the train and val lmdb were created truly right. Do you know the reason? I'll try it again.
Another problem is I finetune the coco model, only change the classes while use the raw data, in that case some pictures are no use for me, but I didn't delete them, so the corresponding to the raw data is the label name or the class number? Is any advice should I notice ?
