### ISSUE TITLE
problem with score_ssd_coco_testdev.py 

### ISSUE THREAD

**Issue by cloudfool** [weiliu89/caffe#571]
I have downloaded the VGG_coco_SSD_300x300_iter_400000.caffemodel and ran the score_ssd_coco_testdev.py, but the detection_eval = 0. 
What did I do wrong?

**Comment by weiliu89** [comment]
Because we don't have ground truth for the test-dev. How could you get evaluation result? :)

You need to upload the saved result file to coco evaluation server.
