### ISSUE TITLE
shape check failed

### ISSUE THREAD

**Issue by qingzew** [weiliu89/caffe#583]
when I remove `resize_param` in annotated_data_layer, it turns out:

> F0511 11:35:52.028280 13684 annotated_data_layer.cpp:209] Check failed: std::equal(top_shape.begin() + 1, top_shape.begin() + 4, shape.begin() + 1)

I am not sure that after `ExpandImage()` and `CropImage()`, the final `sampled_datum`'s shape is equal to original `anno_datum`'s, is that ok?

**Comment by RichardMrLu** [comment]
do you soleve it? I have the same trouble.
