### ISSUE TITLE
Does the latest ssd sample negatives from images where there is no ground truth?

### ISSUE THREAD

**Issue by KeyKy** [weiliu89/caffe#592]
Hi @weiliu89 
I find your answer to the [question](https://github.com/weiliu89/caffe/issues/145).
```
Yes. Currently it doesn't sample negatives from images where there is no ground truth. Refer to #146 as well
``` 
Does the latest ssd sample negatives from images where there is no ground truth? I find the MineHardExamples code:
```
else if (match_indices[label][m] == -1) { 
          if (sel_indices.find(m) != sel_indices.end()) {
            neg_indices.push_back(m);
            *num_negs += 1;
          }
        }
```
It seems that the latest ssd do sample negatives from images where there is no ground truth. Because in MatchBBox the match_indices are all set to -1 for num_gt == 0
```
match_indices->resize(num_pred, -1);
...
if (num_gt == 0) { 
    return;
}
```

**Comment by l309090299** [comment]
Hi @KeyKy 
Did you figure out the problem how ssd take images without ground truth as negative samples?

**Comment by KeyKy** [comment]
@l309090299 I train a dataset of mine by using ssd. After check the detection results, i think 
```
Yes. Currently it doesn't sample negatives from images where there is no ground truth.
```
is right....
Now i try to debug it....

**Comment by KeyKy** [comment]
I confirm ssd doesn't sample negatives from images where there is no ground truth. So i do some modification to io.cpp and bbox_utils.cpp and give me some surprising results.

**Comment by hyzhan** [comment]
@KeyKy Would you tell us that what type of modification is required for io.cpp and bbox_utils.cpp ?

**Comment by sirluckyluke** [comment]
@KeyKy Do you want to share your modifications with the community? this would be nice for my masters thesis :)
