### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by stweiyy** [weiliu89/caffe#6]
Hi, @weiliu89  , I downloaded the code and changed to the ssd branch. 
it seems there are compiling errors.

In file included from ./include/caffe/layers/annotated_data_layer.hpp:8,
                 from src/caffe/layers/annotated_data_layer.cpp:11:
./include/caffe/data_reader.hpp:76: error: type/value mismatch at argument 1 in template parameter list for ‘template<class T> struct boost::weak_ptr’
./include/caffe/data_reader.hpp:76: error:   expected a type, got ‘caffe::DataReader::Body’
./include/caffe/data_reader.hpp:76: error: template argument 2 is invalid
./include/caffe/data_reader.hpp:76: error: template argument 4 is invalid
make: *** [.build_debug/src/caffe/layers/annotated_data_layer.o] Error 1
make: *** Waiting for unfinished jobs....
and I fount that the data_reader.hpp is different with the original caffe's data_reader.hpp
The original caffe doesn't have this 
template <typename T>
 24 class DataReader {

could help me check it?

**Comment by weiliu89** [comment]
Can you provide the environment you are compiling? For example, what is your gcc version? What architecture? I found this solution online:

http://blog.csdn.net/nick870208/article/details/8970951

Could you try to change DataReader::Body to Body?

**Comment by stweiyy** [comment]
@weiliu89  You are correct. I changed the  data_reader.hpp:76 **DataReader::Body to Body** and it worked, just a small change.
However, I am curious why I can compile the master branch without any change?
the master branch is **static map<const string, boost::weak_ptr<DataReader::Body> > bodies_;**
my g++ version is 4.3.4
and the boost library version I used it boost_1_61_0
do you have any ideas?

**Comment by weiliu89** [comment]
Because DataReader in master branch is not a template class.

I guess it is a g++ bug according to the search results.
You can update your g++, and could potentially solve the problem as well.

**Comment by stweiyy** [comment]
@weiliu89 . Got it, thanks for your help. SSD is great!
