### ISSUE TITLE
weird results by ssd_detect.cpp

### ISSUE THREAD

**Issue by lebronyxm** [weiliu89/caffe#60]
I have tested my own data(some images don't have any object) using ssd_detect.cpp. But the result is quite weird. When the image has no objects, the next line result is wrong. 

> /opt/yangxuemeng/caffe/data/list3500/2288.jpg 1 0.98769 128 134 178 164
/opt/yangxuemeng/caffe/data/list3500/2288.jpg 3 0.987696 181 135 302 164
I0725 10:44:09.412675  9250 detection_output_layer.cu:105] Couldn't find any detections
/opt/yangxuemeng/caffe/data/list3500/2289.jpg 1 0.98769 128 134 178 164
I0725 10:44:09.472481  9250 detection_output_layer.cu:105] Couldn't find any detections
/opt/yangxuemeng/caffe/data/list3500/229.jpg 1 0.98769 273 287 379 350
I0725 10:44:09.526185  9250 detection_output_layer.cu:105] Couldn't find any detections
/opt/yangxuemeng/caffe/data/list3500/2290.jpg 1 0.98769 128 134 178 164
I0725 10:44:09.579421  9250 detection_output_layer.cu:105] Couldn't find any detections
/opt/yangxuemeng/caffe/data/list3500/2291.jpg 1 0.98769 128 134 178 164
I0725 10:44:09.633890  9250 detection_output_layer.cu:105] Couldn't find any detections
/opt/yangxuemeng/caffe/data/list3500/2292.jpg 1 0.98769 128 134 178 164
I0725 10:44:09.797497  9250 detection_output_layer.cu:105] Couldn't find any detections
I0725 10:44:09.851101  9250 detection_output_layer.cu:105] Couldn't find any detections
I0725 10:44:09.904336  9250 detection_output_layer.cu:105] Couldn't find any detections
I0725 10:44:09.958243  9250 detection_output_layer.cu:105] Couldn't find any detections
I0725 10:44:10.014113  9250 detection_output_layer.cu:105] Couldn't find any detections
/opt/yangxuemeng/caffe/data/list3500/23.jpg 4 0.997509 7 254 97 278

Such as, 2290.jpg-2292.jpg, the next line result has the same confidence (sometimes with the location) as the last one.  But, i have checked the image, and it must be impossible. Also, when  consecutive  images have no objects, the next line result is right, such as 23.jpg.  

I think this may caused by a minor issue in ssd_detect.cpp or detection_output_layer.cu.  Do you have any idea about how to fix this? Thanks~

**Comment by lebronyxm** [comment]
`  /* Copy the output layer to a std::vector */
  Blob<float>* result_blob = net_->output_blobs()[0];
  const float* result = result_blob->cpu_data();
  const int num_det = result_blob->height();
  vector<vector<float> > detections;
  for (int k = 0; k < num_det; ++k) {
    vector<float> detection(result, result + 7);
    detections.push_back(detection);
    result += 7;
  }
  return detections;`

i check the ssd_detect.cpp, and find the above codes. If num_det==0, it will skip the loop and return detections without mark or something else. So, the detections vector remains the last time information in the current location. 

` /* Print the detection results. */
    for (int i = 0; i < detections.size(); ++i) {
      const vector<float>& d = detections[i];
      // Detection format: [image_id, label, score, xmin, ymin, xmax, ymax].
      CHECK_EQ(d.size(), 7);
      const float score = d[2];
      if (score >= confidence_threshold) {
        out << imgfile << " ";
        out << static_cast<int>(d[1]) << " ";
`
When it printing the result, it did't check the above issue? I'm not sure whether it's the reason or not.

**Comment by lebronyxm** [comment]
I have modified the detection_output_layer.hpp and made a flag in it. Using this flag, the ssd_detection.cpp and detection_output_layer.cu could have fixed this problem. But i failed...Maybe the flag should not put in detection_output_layer.hpp....

**Comment by weiliu89** [comment]
There was a bug in the code. I have fixed the problem (hopefully) at 0c16cf6. You can pull the newest code and try again. Let me know if there are still problems.

**Comment by lebronyxm** [comment]
Thanks for your  elaborate help, I have done with this!
