### ISSUE TITLE
Question about coco's labelmap_coco.prototxt

### ISSUE THREAD

**Issue by wk910930** [weiliu89/caffe#605]
Dear @weiliu89 ,

When I read the [labelmap_coco.prototxt](https://github.com/weiliu89/caffe/blob/ssd/data/coco/labelmap_coco.prototxt), I found the `name` and the `label` are a little bit confusing. For example, [this](https://github.com/weiliu89/caffe/blob/ssd/data/coco/labelmap_coco.prototxt#L61) item has a `name` of 13, while a `label` of 12. Shouldn't them be the same? Since some items are while some are not. And what is the use of [labels.txt](https://github.com/weiliu89/caffe/blob/ssd/data/coco/labels.txt), which is not included in [VOC0712](https://github.com/weiliu89/caffe/tree/ssd/data/VOC0712)?

Thanks!
Kun

**Comment by weiliu89** [comment]
The name is the category id used in coco (from 1 to 90) and the label id is the one used internally in SSD. Name can be anything specified in the dataset. Check labelmap_voc.prototxt

**Comment by wk910930** [comment]
Thanks for reply. Yes, [labelmap_voc.prototxt](https://github.com/weiliu89/caffe/blob/ssd/data/VOC0712/labelmap_voc.prototxt) makes sense to me. But I am confused about why [some](https://github.com/weiliu89/caffe/blob/ssd/data/coco/labelmap_coco.prototxt#L56-L60) items match while [some](https://github.com/weiliu89/caffe/blob/ssd/data/coco/labelmap_coco.prototxt#L61-L65) items don't in labelmap_coco.prototxt. So there is no other reason to do so, right? Just because of the accident?

**Comment by weiliu89** [comment]
Check coco annotations

**Comment by wk910930** [comment]
Now I got it. Thanks! Closing the issue.
