### ISSUE TITLE
Can't use the deploy.prototxt with SSD500x500 model to detect objects

### ISSUE THREAD

**Issue by nature1317** [weiliu89/caffe#63]
I want to  use the SSD500x500  model you trained to detect objects,but I run the ssd_detect.exe，errors are below:
E:\zcCaffe\result>ssd_detect.exe ./deploy.prototxt ./VVGG_VOC0712_SSD
_500x500_iter_60000.caffemodel ./ssd_detect
[libprotobuf ERROR D:\ThirdPartyLibrary\protobuf\src\google\protobuf\text_format
.cc:291] Error parsing text-format caffe.NetParameter: 824:14: Message type "caf
fe.LayerParameter" has no field named "norm_param".
F0726 14:21:25.072182  6228
upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Fai
led to parse NetParameter file: ./deploy.prototxt
*** Check failure stack trace: ***

E:\zcCaffe\result>echo.   & pause

**Comment by weiliu89** [comment]
Please make sure you have added the SSD `$CAFFE_ROOT/python` to your PYTHONPATH environment variable.
