### ISSUE TITLE
Where to find  ZF_conv_reduced.caffemodel

### ISSUE THREAD

**Issue by SeanChenxy** [weiliu89/caffe#630]
I want to try ssd_pascal_zf.py, but there is no ZF_conv_reduced.caffemodel. Could you tell me where to download it?

**Comment by weiliu89** [comment]
Check the top of the script.

**Comment by SeanChenxy** [comment]
I found it. Thank you!

**Comment by lifeiove** [comment]
> I found it. Thank you
Do you still have the zf_conv_reduced.caffemodel model? Could you share it with me? Path in file is not accessible.(lifei1286@163.com)
