### ISSUE TITLE
Bug in bipartite matching strategy in bbox_util.cpp? 

### ISSUE THREAD

**Issue by siddharthm83** [weiliu89/caffe#635]
@weiliu89 
In the bipartite matching, I feel the break statement in L667 may have unintended consequence that prevents any further matching before the per prediction matching.
https://github.com/weiliu89/caffe/blob/ssd/src/caffe/util/bbox_util.cpp#L665-L667

You are indexing wrt the prior box index first and finding overlap with any of the p ground truth boxes, lets say the first prior box has no match with any of the ground truth boxes. In this case, I feel the break statement prevents matching for any subsequent prior boxes. 

The per prediction matching may still find the most overlapped boxes but you may be missing out on matching any prior box for a few ground truth boxes.

**Comment by weiliu89** [comment]
I don't think so. There is a two for-loop which checks the maximum pair.
https://github.com/weiliu89/caffe/blob/ssd/src/caffe/util/bbox_util.cpp#L642-L664

**Comment by siddharthm83** [comment]
Oh, i missed that. thanks!
