### ISSUE TITLE
SSD+Resnet-50: Check failed: bottom[1]->num() == 1 (2 vs. 1)

### ISSUE THREAD

**Issue by July0zhu** [weiliu89/caffe#636]
@weiliu89 hi，weiliu，I meet some problem when i train SSD + Resnet
 error message：Check failed: bottom[1]->num() == 1 (2 vs. 1)
I use the data set is the 200 kinds of ILSVRC2016 and the base network 
model is Resnet-50, according to the data\ILSVRC2016 file generated LMDB data,according to the examples\ssd\ssd_pascal_resnet.py formation of train.prototxt and test.prototxt, I don't know where is the problem, can you give me some advice?(PS:My English is poor,please forgive me if i make mistak.)

**Comment by wliu-nuro** [comment]
Check #192

**Comment by weiliu89** [comment]
Check #192

**Comment by July0zhu** [comment]
hi,weiliu.Before ask help for you,I have noticed this issue #192. According to your reply, I checked my .prototxt carefully.ResNet-50 conv1 layer ‘s bias_term was set false,but my problem still exists.

**Comment by July0zhu** [comment]
hi,weiliu. Another error message :Check failed: num_priors_ * num_classes_ == bottom[1]->channels() (7315308 vs. 153468) Number of priors must match number of confidence predictions.  What is the cause of this problem?

**Comment by July0zhu** [comment]
@weiliu89 sorry，i make a mistak about test data ,The problem has been solved now,Thank you very much!

**Comment by 24475401** [comment]
@July0zhu 
num_priors_ * num_classes_ == bottom [1] - > channels（）（7315308 vs. 153468）先验数量必须与置信度预测数相匹配。这个问题的原因是什么？请问这个问题怎么解决
