### ISSUE TITLE
How to fine-tune VGG_VOC0712_SSD_300x300_iter_60000.caffemodel ?

### ISSUE THREAD

**Issue by Mamba-fx** [weiliu89/caffe#64]
First, I want to say: it is a wonderful project !

And, I want to fine-tuning  VGG_VOC0712_SSD_300x300_iter_60000.caffemodel which you give us.
but I only have a deploy.protxt of this caffemodel. I also need train_val.prototxt and solver.protxt. How can   I get these ?

**Comment by weiliu89** [comment]
The train.prototxt, test.prototxt, and solver.prototxt can be generated by `examples/ssd/ssd_pascal.py`.

**Comment by Mamba-fx** [comment]
hi , thanks for your reply.
Now , I changed num_classes to 6.  And data are re-prepared from VOC0712 to fit the change. 
Then I used ssd_pascal.py to train the model , but the mbox_loss has been maintained between 2 to 7.
I have tried to adjustment the base_lr . But it didn't work neither.
Should I change other param from ssd_pascal.py？ 
Thanks all.

**Comment by Mamba-fx** [comment]
I get this. thank you for all.
