### ISSUE TITLE
ssd_pascal_video fail to open video

### ISSUE THREAD

**Issue by kuonangzhe** [weiliu89/caffe#658]
### Issue summary
The ssd_pascal_video fails to open video. This worked well before but after I installed two versions of caffe (both already configured in path), it failed. 
I used sys.path.insert at the beginning of the file to refer to caffe-ssd.

### Details
I0628 13:26:31.689558  3540 layer_factory.hpp:77] Creating layer data
I0628 13:26:31.689595  3540 net.cpp:100] Creating Layer data
I0628 13:26:31.689606  3540 net.cpp:408] data -> data
F0628 13:26:31.689692  3540 video_data_layer.cpp:53] Failed to open video: examples/videos/ILSVRC2015_train_00755001.mp4
*** Check failure stack trace: ***
    @     0x7f88db9e1ea4  (unknown)
    @     0x7f88db9e1deb  (unknown)
    @     0x7f88db9e17bf  (unknown)
    @     0x7f88db9e4a35  (unknown)
    @     0x7f88dc207f28  caffe::VideoDataLayer<>::DataLayerSetUp()
    @     0x7f88dc13accb  caffe::BaseDataLayer<>::LayerSetUp()
    @     0x7f88dc13ad53  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7f88dbfbd9d3  caffe::Net<>::Init()
    @     0x7f88dbfbf3e8  caffe::Net<>::Net()
    @           0x40a7ca  test()
    @           0x40837d  main
    @     0x7f88da033a40  (unknown)
    @           0x408d29  _start
    @              (nil)  (unknown)
Aborted (core dumped)

### Your system configuration
Operating system: Ubuntu15.04
Compiler:
CUDA version (if applicable):8.0
CUDNN version (if applicable):5
BLAS:atlas
Python or MATLAB version (for pycaffe and matcaffe respectively):python 2.7

**Comment by kuonangzhe** [comment]
I know this is weird but just want to know if there are any possible circumstances that might lead to this.
Thanks for the help!

**Comment by weiliu89** [comment]
Probably your opencv is not compiled with video stuff?

**Comment by kuonangzhe** [comment]
@weiliu89 This might be the issue, but I checked the .so files and found that all video required modules are compiled properly.

**Comment by wematan** [comment]
Have you compiled caffe with opencv 3?
if so did you edit the Makefile and applied the following: 
"opencv_core opencv_highgui opencv_imgproc opencv_imgcodecs opencv_videoio"
to LIBRARIES variable?

Check the building procedure in caffe's main branch:
https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide

* It says 15.10 but the opencv part of the build corresponds to you also.

**Comment by kuonangzhe** [comment]
@wematan Thanks for the help! Due to the time constraints, actually finally I solved the problem by reinstalling the Ubuntu system and the framework(or I can say the problem is not solved due to weird problems).

I think the problem is due to mis-installation of different versions of opencv and caffe but not config them correctly. 

Thanks for the help anyway!!!
