### ISSUE TITLE
Windows10 SSD build error on boost library

### ISSUE THREAD

**Issue by dsafkldjla** [weiliu89/caffe#665]
### Issue summary
Hello.
I am using boost version 1.61.
There is no problem when I build master caffe branch on Windows 10 with same external libraries.
However, when I build SSD branch, errors related with boost library appear.
I tried multiple time changing boost library version, almost same errors appear.
My question is how to solve this problem.
Please do not hesitate to contact me if you need any other information.

### Steps to reproduce
Error	2560	error C2015: too many characters in constant	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\regex_traits_defaults.hpp	333	caffe	1
Error	2561	error C2017: illegal escape sequence	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\regex_traits_defaults.hpp	333	caffe	1
Error	2562	error C2059: syntax error : ']'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\regex_traits_defaults.hpp	333	caffe	1
Error	2563	error C2001: newline in constant	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\regex_traits_defaults.hpp	333	caffe	1
Error	2564	error C2015: too many characters in constant	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\regex_traits_defaults.hpp	336	caffe	1
Error	2565	error C2059: syntax error : ']'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\regex_traits_defaults.hpp	336	caffe	1
Error	2566	error C2017: illegal escape sequence	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\regex_traits_defaults.hpp	336	caffe	1
Error	2567	error C2001: newline in constant	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\regex_traits_defaults.hpp	336	caffe	1
Error	2568	error C2059: syntax error : ']'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\regex_traits_defaults.hpp	355	caffe	1
Error	2569	error C2059: syntax error : ')'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\regex_traits_defaults.hpp	355	caffe	1
Error	2570	error C2017: illegal escape sequence	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\regex_traits_defaults.hpp	355	caffe	1
Error	2571	error C2001: newline in constant	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\regex_traits_defaults.hpp	355	caffe	1
Error	2573	error C2143: syntax error : missing ';' before '<'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	130	caffe	1
Error	2574	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	130	caffe	1
Error	2575	error C2238: unexpected token(s) preceding ';'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	130	caffe	1
Error	2576	error C2146: syntax error : missing ',' before identifier 'int_least_helper'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	131	caffe	1
Error	2577	error C2275: 'boost::boost::int_t<Bits>::int_least_helper' : illegal use of this type as an expression	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	131	caffe	1
Error	2578	error C2977: 'boost::boost::int_fast_t' : too many template arguments	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	131	caffe	1
Error	2579	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	131	caffe	1
Error	2580	error C2143: syntax error : missing ';' before '>'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	131	caffe	1
Error	2581	error C2059: syntax error : '>'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	131	caffe	1
Error	2582	error C2238: unexpected token(s) preceding ';'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	131	caffe	1
Error	2583	error C2143: syntax error : missing ';' before '<'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	161	caffe	1
Error	2584	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	161	caffe	1
Error	2585	error C2238: unexpected token(s) preceding ';'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	161	caffe	1
Error	2586	error C2146: syntax error : missing ',' before identifier 'uint_least_helper'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	163	caffe	1
Error	2587	error C2275: 'boost::boost::uint_t<Bits>::uint_least_helper' : illegal use of this type as an expression	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	163	caffe	1
Error	2588	error C2977: 'boost::boost::int_fast_t' : too many template arguments	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	163	caffe	1
Error	2589	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	163	caffe	1
Error	2590	error C2143: syntax error : missing ';' before '>'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	163	caffe	1
Error	2591	error C2059: syntax error : '>'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	163	caffe	1
Error	2592	error C2238: unexpected token(s) preceding ';'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\integer.hpp	163	caffe	1
Error	2594	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\cpp_regex_traits.hpp	242	caffe	1
Error	2595	error C2143: syntax error : missing ',' before '&'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\cpp_regex_traits.hpp	242	caffe	1
Error	2596	error C2942: 'boost::boost::re_detail_106100::cpp_regex_traits_base<charT>' : template-class-id redefined as a formal argument of a function	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\cpp_regex_traits.hpp	242	caffe	1
Error	2597	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\cpp_regex_traits.hpp	437	caffe	1
Error	2598	error C2143: syntax error : missing ',' before '&'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\cpp_regex_traits.hpp	437	caffe	1
Error	2599	error C2942: 'boost::boost::re_detail_106100::cpp_regex_traits_base<charT>' : template-class-id redefined as a formal argument of a function	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\cpp_regex_traits.hpp	437	caffe	1
Error	2600	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	157	caffe	1
Error	2601	error C2146: syntax error : missing ',' before identifier 'l'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	157	caffe	1
Error	2602	error C2039: 'lcid_type' : is not a member of 'boost::re_detail_106100'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	191	caffe	1
Error	2603	error C2061: syntax error : identifier 'lcid_type'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	191	caffe	1
Error	2604	error C2244: 'boost::boost::re_detail_106100::w32_regex_traits_char_layer<charT>::w32_regex_traits_char_layer' : unable to match function definition to an existing declaration	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	234	caffe	1
Error	2605	error C2061: syntax error : identifier 'lcid_type'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	305	caffe	1
Error	2606	error C2039: 'lcid_type' : is not a member of 'boost::re_detail_106100'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	435	caffe	1
Error	2607	error C2061: syntax error : identifier 'lcid_type'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	435	caffe	1
Error	2608	error C2039: 'syntax_type' : is not a member of 'boost::boost::regex_constants'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	582	caffe	1
Error	2609	error C2146: syntax error : missing ';' before identifier 'syntax_type'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	582	caffe	1
Error	2610	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	582	caffe	1
Error	2611	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	583	caffe	1
Error	2613	error C2039: 'escape_syntax_type' : is not a member of 'boost::boost::regex_constants'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	586	caffe	1
Error	2614	error C2146: syntax error : missing ';' before identifier 'escape_syntax_type'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	586	caffe	1
Error	2615	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	586	caffe	1
Error	2616	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	587	caffe	1
Error	2618	error C2039: 'error_type' : is not a member of 'boost::boost::regex_constants'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	662	caffe	1
Error	2619	error C2061: syntax error : identifier 'error_type'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\regex\v4\w32_regex_traits.hpp	662	caffe	1
Error	2620	error C2039: 'shared_ptr' : is not a member of 'boost::boost'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\smart_ptr\shared_ptr.hpp	433	caffe	1
Error	2621	error C2143: syntax error : missing ')' before '<'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\smart_ptr\shared_ptr.hpp	433	caffe	1
Error	2622	error C2143: syntax error : missing ';' before '<'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\smart_ptr\shared_ptr.hpp	433	caffe	1
Error	2623	error C2652: 'boost::shared_ptr<const boost::boost::re_detail_106100::w32_regex_traits_implementation<charT>>' : illegal copy constructor: first parameter must not be a 'boost::shared_ptr<const boost::boost::re_detail_106100::w32_regex_traits_implementation<charT>>'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\smart_ptr\shared_ptr.hpp	433	caffe	1
Error	2624	error C2238: unexpected token(s) preceding ';'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\smart_ptr\shared_ptr.hpp	433	caffe	1
Error	2625	error C2988: unrecognizable template declaration/definition	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\smart_ptr\shared_ptr.hpp	433	caffe	1
Error	2626	error C2059: syntax error : '<'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\smart_ptr\shared_ptr.hpp	433	caffe	1
Error	2627	error C2059: syntax error : ')'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\smart_ptr\shared_ptr.hpp	433	caffe	1
Error	2628	error C2039: 'shared_ptr' : is not a member of 'boost::boost'	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\smart_ptr\shared_ptr.hpp	447	caffe	1
Error	2629	error C2334: unexpected token(s) preceding ':'; skipping apparent function body	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\smart_ptr\shared_ptr.hpp	447	caffe	1
Error	2630	error C1075: end of file found before the left brace '{' at 'C:/Users/SUN/.caffe/dependencies/libraries_v120_x64_py27_1.1.0/libraries/include/boost-1_61\boost/regex/v4/char_regex_traits.hpp(36)' was matched	C:\Users\SUN\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost\smart_ptr\shared_ptr.hpp	771	caffe	1

### Your system configuration
Operating system: Windows 10
Compiler: _MSC_VER 1800
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 5.1
BLAS: openblas
Python or MATLAB version (for pycaffe and matcaffe respectively): 2.7.13

**Comment by WUhailing** [comment]
Did you solve it？I ran into the same error but cannot fix it.:(

**Comment by dsafkldjla** [comment]
It's been a long time since I was not sure, but I remember it was an error related to regex.
I modified some file in the SSD repository that use boost regex.
I'm sorry I can not tell you in more detail.

**Comment by WUhailing** [comment]
@dsafkldjla thanks anyway, I will check ssd repo and see if i can make some change to fix the error.
FYI, commenting out regex,rv lines in detection_output_layer.cu,   regex,rv and #include<boost/regex.hpp> lines in detection_output_layer.hpp do the trick.
