### ISSUE TITLE
SSD Data layer prefetch queue empty loss=0

### ISSUE THREAD

**Issue by jiangwqcooler** [weiliu89/caffe#668]
![image](https://user-images.githubusercontent.com/11244330/27959108-b6ee0eac-6358-11e7-8925-180f5adb4a9c.png)

**Comment by jiangwqcooler** [comment]
I had found this problem，cause by xml annotation which position coordinate <xmin>2.0000</xmin>, ichange to <xmin>2</xmin> can solutaion it.

**Comment by RoseLii** [comment]
please help me
无法下载Download fully convolutional reduced (atrous) VGGNet
能给我发一下吗？

**Comment by RoseLii** [comment]
你好，打扰一下。我下载了VOCtrainval_06-Nov-2007，但是在运行./data/VOC0712/create_list.sh时出现
cp: cannot stat '/y/2T/caffe/data/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt': No such file or directory。这是怎么回事呀。

**Comment by corleonechensiyu** [comment]
> I had found this problem，cause by xml annotation which position coordinate 2.0000, ichange to 2 can solutaion it.

老哥，我跟你遇到的一模一样，请问具体怎么解决的呢
