### ISSUE TITLE
When I run the command "python examples/ssd/ssd_pascal_video.py" , I get wrong messge

### ISSUE THREAD

**Issue by sunume** [weiliu89/caffe#673]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
When I run the command "python examples/ssd/ssd_pascal_video.py" , I get follow wrong messge:
*** Aborted at 1500109708 (unix time) try "date -d @1500109708" if you are using GNU date ***
PC: @     0x7f10ad137ce0 (unknown)
*** SIGSEGV (@0x8) received by PID 13468 (TID 0x7f11055cfa80) from PID 8; stack trace: ***
    @     0x7f1102ada4b0 (unknown)
    @     0x7f10ad137ce0 (unknown)
    @     0x7f10ad137d5e (unknown)
    @     0x7f10ad159c1d (unknown)
    @     0x7f10ad15e175 (unknown)
    @     0x7f10ad716f9d (unknown)
    @     0x7f10ad16fc90 (unknown)
    @     0x7f10ad11c4a5 (unknown)
    @     0x7f10ad716f9d (unknown)
    @     0x7f10ad11fc24 (unknown)
    @     0x7f10ad121391 (unknown)
    @     0x7f10ad117aec __cuda_CallJitEntryPoint
    @     0x7f10b54565c2 fatBinaryCtl_Compile
    @     0x7f10b583cee2 (unknown)
    @     0x7f10b583da63 (unknown)
    @     0x7f10b579622e (unknown)
    @     0x7f10b5796510 (unknown)
    @     0x7f10f2c3e68d (unknown)
    @     0x7f10f2c340b0 (unknown)
    @     0x7f10f2c41906 (unknown)
    @     0x7f10f2c44f11 (unknown)
    @     0x7f10f2c38a7c (unknown)
    @     0x7f10f2c252d2 (unknown)
    @     0x7f10f2c5aa4f (unknown)
    @     0x7f10f2708714 cudnnCreate
    @     0x7f1104ad0021 caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7f1104c1e732 caffe::Net<>::Init()
    @     0x7f1104c20770 caffe::Net<>::Net()
    @           0x4097a7 test()
    @           0x4077c8 main
    @     0x7f1102ac5830 __libc_start_main
    @           0x408099 _start
Segmentation fault (core dumped)
However,I also run this in nvidia TX1 and nvidia TX2 where succed. 
### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:UBUNTU 16.04
Compiler: G++
CUDA version (if applicable):cudn8.0
CUDNN version (if applicable):cudnn5.1.10
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):python

**Comment by wematan** [comment]
Just solved in my project.
Recompile opencv 3 with WITH_OPENCL=OFF.

**Comment by sunume** [comment]
thanks，let me try

**Comment by Vilour** [comment]
I have the same issue.Have you solved the problem?

**Comment by sunume** [comment]
I have recompile opencv3 with WITH_OPENCL=OFF,but I failed.
Maybe using opencv2 is better.I succeed run it with opencv2 in NVIDIA TX1 andTX2

**Comment by Vilour** [comment]
Recompiling opencv 3 works for me.I uninstall opencv 2 and compile opencv 3 then it works.Thanks a lot

**Comment by sunume** [comment]
I try recompile opencv3 with WITH_OPENCL=OFF again and it works.Maybe I did something wrong when I tried to recompile opencv3 at the first time. Thanks a lot to @wematan and @Vilour .

**Comment by 408550969** [comment]
Excuse me,what's the speed of SSD300 on TX2?

**Comment by sunume** [comment]
about 4/5 fps when use TX2 @408550969

**Comment by 408550969** [comment]
Thanks,  It looks like that TX2 does not increase the speed compared with TX1.
