### ISSUE TITLE
How to interpret the output of 'detection_out' layer

### ISSUE THREAD

**Issue by vj-1988** [weiliu89/caffe#68]
I used net.forward() method to test an image using a pre-trained model. The output from 'detection_out' layer is an numpy array of shape (1, 1, x, 7) where x varies with image. 

Can someone explain how to interpret this output from network.

**Comment by weiliu89** [comment]
Check out [this](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_detect.cpp#L329).

**Comment by vj-1988** [comment]
@weiliu89 : Thank you !
