### ISSUE TITLE
Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal

### ISSUE THREAD

**Issue by fuxianh** [weiliu89/caffe#69]
when i try to train SSD, the shell command is "python examples/ssd/ssd_pascal.py "
The system is Ubuntu 14.04, with one GPU
Can anyone give me some advice, thank you.
@weiliu89

**Comment by weiliu89** [comment]
You should change [this line](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_pascal.py#L285) to `gpus = '0'`

**Comment by fuxianh** [comment]
Wow, so great, thank you. Next time I would check the train file first.
