### ISSUE TITLE
could not pass in a picture

### ISSUE THREAD

**Issue by zhou503m** [weiliu89/caffe#696]
I want to write a Java call to the SSD in my JNI program using the following code but with the following error, Does anyone know how to fix it? Thanks! I really don‘t konw why could not pass in a picture

    cv::Mat img = cv::imread("*.jpg", -1);
    std::vector<vector<float> > detections = detector.Detect(img);

**OpenCV** Error: Sizes of input arguments do not match (The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array') in arithm_opfile /home/**/software/opencv-3.2.0/modules/core/src/arithm.cpp, line 659
terminate called after throwing an instance of 'cv::Exception' what():  /home/**/software/opencv-3.2.0/modules/core/src/arithm.cpp:659: error: (-209) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar',                                                                                                                                                                      nor 'scalar op array' in function arithm_op

**Comment by weiliu89** [comment]
You should resize the image and also do data preprocessing before passing it to the model. You could check `examples/ssd_detect.ipynb`.
