### ISSUE TITLE
lmdb error!

### ISSUE THREAD

**Issue by funnyzhou** [weiliu89/caffe#7]
Hi, @weiliu89 , I downloaded the code and changed to the ssd branch. 
When I run the ssd_pascal.py, there are some errors about lmdb. I've followed your instructions in readme file. Could you help me check it?

I0624 22:59:21.664676 12142 layer_factory.hpp:77] Creating layer data
I0624 22:59:21.665473 12142 net.cpp:91] Creating Layer data
I0624 22:59:21.665518 12142 net.cpp:399] data -> data
I0624 22:59:21.665637 12142 net.cpp:399] data -> label
I0624 22:59:21.682493 12155 db_lmdb.cpp:35] Opened lmdb /home/caffe_ssd/examples/VOC0712/VOC0712_trainval_lmdb
C: @     0x7f56d22717d0 cv::_InputArray::getMat_()
*** SIGSEGV (@0x80030001) received by PID 12142 (TID 0x7f56dddc39c0) from PID 18446744071562264577; stack trace: ***
    @     0x7f56db1ccd40 (unknown)
    @     0x7f56d22717d0 cv::_InputArray::getMat_()
    @     0x7f56dbcb32b9 cv::imdecode()
    @     0x7f56dcf3c392 caffe::DecodeDatumToCVMatNative()
    @     0x7f56dcfaa086 caffe::DataTransformer<>::InferBlobShape()
    @     0x7f56dce53009 caffe::AnnotatedDataLayer<>::DataLayerSetUp()
    @     0x7f56dceaabe9 caffe::BaseDataLayer<>::LayerSetUp()
    @     0x7f56dceab036 caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7f56dcdcc374 caffe::Layer<>::SetUp()
    @     0x7f56dcf000bd caffe::Net<>::Init()
    @     0x7f56dcefe471 caffe::Net<>::Net()
    @     0x7f56dceeaddd caffe::Solver<>::InitTrainNet()
    @     0x7f56dceea600 caffe::Solver<>::Init()
    @     0x7f56dceea09c caffe::Solver<>::Solver()
    @     0x7f56dcfb5bd3 caffe::SGDSolver<>::SGDSolver()
    @     0x7f56dcfc1227 caffe::Creator_SGDSolver<>()
    @           0x421971 caffe::SolverRegistry<>::CreateSolver()
    @           0x41d34c train()
    @           0x41f7df main
    @     0x7f56db1b7ec5 (unknown)
    @           0x41c199 (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)

**Comment by funnyzhou** [comment]
Ok, I've solved it.... You cannot include opencv in Makefile.config

**Comment by weiliu89** [comment]
What is your opencv version?

**Comment by liunlll** [comment]
@funnyzhou 
Hello,I also have the error,could i see your Makefile.cogfig?

**Comment by chenzyhust** [comment]
@funnyzhou can you tell me how to solve the problem in detail,thank you very much
