### ISSUE TITLE
When train with coco dataset, print warning info: "Missing true_pos for label: 71". 

### ISSUE THREAD

**Issue by KevinYuk** [weiliu89/caffe#717]
### Issue summary
I am training SSD 300x300 with coco dataset, but it print the information below:
W0822 05:57:51.463230 20221 solver.cpp:743] Missing true_pos for label: 71
W0822 05:57:51.472806 20221 solver.cpp:743] Missing true_pos for label: 79
The training could continue. However, could we ignore the print above?

### Steps to reproduce

Just as Readme for coco training. Nothing special.

### Your system configuration
Operating system: ubuntu
Compiler: icc
Just use CPU, not GPU

**Comment by weiliu89** [comment]
You could ignore it. Those classes are probably hard or do not have many samples. It should detect some true positives after more iterations.

**Comment by KevinYuk** [comment]
Thanks for your confirmation.
