### ISSUE TITLE
Does training voc  parameter is not same with coco?

### ISSUE THREAD

**Issue by Anhaoxu** [weiliu89/caffe#719]
@weiliu89  Hi,I have trained the voc script, but when I run ssd_coco.py,some errors happened,like this:AttributeError: type object 'MultiBoxLossParameter' has no attribute 'MAX_NEGATIVE',and the function CreateMultiBoxHead has no keyword name "steps",what's the problem? voc and coco' parameter file is different?

**Comment by weiliu89** [comment]
Have you pulled the latest code?

**Comment by Anhaoxu** [comment]
@weiliu89 Thanks for your reply, I justify the new script. I find the new train script add some parameters, like steps,and in " ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 256, 1, 0, 1,lr_mult=lr_mult)" add lr_mult=lr_mult and so on, these has some influence to train the ssd_coco.py? 
Another problem is I use all the 80 classes coco dataset to train my 6 classes model, the class is all overlap with coco, then I change the "conf" layer name to support my work, but the loss is ranging and detection accuracy is very low, is finetune model like this wrong? Can I use the dataset like this ? I'm not sure about the principle of caffe, also I heard you teach us to use net surgery, but this work maybe need lots of time to learn, so can you answer the above questions? Thank you!

**Comment by weiliu89** [comment]
I always recommend people run [this](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd.ipynb) to make sure all the data/labels are correct before they do any training.

In your case, you have to adjust the annotation files to only include 6 categories.
