### ISSUE TITLE
SyntaxError: invalid syntax when running "create_data.sh"

### ISSUE THREAD

**Issue by yutingchen1211** [weiliu89/caffe#739]
### Issue summary
Error when running VOC0712 example:
Followed the steps and locations exactly. Running ./data/VOC0712/create_list.sh is fine, however getting the following error when running ./data/VOC0712/create_data.sh

Please advise, thanks!

### Steps to reproduce

(testcaffe) yuting@ubuntu:~/caffe$ ./data/VOC0712/create_data.sh
  File "/home/yuting/caffe/scripts/create_annoset.py", line 75
    print "root directory: {} does not exist".format(root_dir)
                                            ^
SyntaxError: invalid syntax
  File "/home/yuting/caffe/scripts/create_annoset.py", line 75
    print "root directory: {} does not exist".format(root_dir)

### Your system configuration
Operating system: Ubuntu
Compiler:
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 7.0
BLAS: MKL
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by yutingchen1211** [comment]
Problem was print is a function in python 3, changed all print commands from print *** to print(***) and is solved

**Comment by RoseLii** [comment]
你好，打扰一下。我下载了VOCtrainval_06-Nov-2007，但是在运行./data/VOC0712/create_list.sh时出现
cp: cannot stat '/y/2T/caffe/data/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt': No such file or directory。这是怎么回事呀。
