### ISSUE TITLE
How to test in single Image

### ISSUE THREAD

**Issue by RaisingSun** [weiliu89/caffe#76]
I used examples/ssd_detect.ipynb to test single image, but the deploy.prototxt is not the correct one, so how can I generate a matched deploy.prototxt.
Thanks

**Comment by lcj1105** [comment]
examples/ssd_detect.ipynb is enough , check your code

**Comment by guhaohitsz** [comment]
@weiliu89 
I don't know how to detect the position of the object in a single, could you help me about you command. I have no ideal how to use examples/ssd_detect.ipynb and examples/ssd/ssd_detect.cpp.

regards

**Comment by guhaohitsz** [comment]
@RaisingSun 
have you solved the problem, please help me with your command, I don't know how to use examples/ssd_detect.ipynb and examples/ssd/ssd_detect.cpp.

regards
