### ISSUE TITLE
why the model output two or more detections for the truth object

### ISSUE THREAD

**Issue by OMG59E** [weiliu89/caffe#763]
hi all:
       why the model output two or more detections for a truth object ?
       i set the "nms threshold" is 0.3. anyone can help me.
![wuhan 70](https://user-images.githubusercontent.com/16315529/31930954-247e1216-b8d4-11e7-9b9a-87a821bb96a0.jpg)

**Comment by zoumengchao** [comment]
应为他们属于不同的默认框. 就相当于检测两个目标了.只是这两个目标正好是同一个物体而已. 新的SSD好像对这个问题进行了处理.

**Comment by zoumengchao** [comment]
@xwg031459 应为他们属于不同的默认框. 就相当于检测两个目标了.只是这两个目标正好是同一个物体而已. 新的SSD好像对这个问题进行了处理.
