### ISSUE TITLE
How to generate voc2012 test lmdb

### ISSUE THREAD

**Issue by lzx1413** [weiliu89/caffe#766]
In the model 07++12, I find that the test set is voc2012test_lmdb, but the voc2012 test do not have xml. So how can I generate this lmdb? thanks.

**Comment by shudct** [comment]
have you solved the problem? i only convert the images to lmdb. however, the script ssd_pascal.py needs val-data, and i can't test the trained models. can you give me some advice?

**Comment by lzx1413** [comment]
you can refer to this project https://github.com/sfzhang15/RefineDet
