### ISSUE TITLE
unable to download  VGGNet

### ISSUE THREAD

**Issue by RoseLii** [weiliu89/caffe#767]
please help me
无法下载Download fully convolutional reduced (atrous) VGGNet
能给我发一下吗？

**Comment by LuckyQinn** [comment]
楼主找到了吗，我也下载不了，求发一份

**Comment by RoseLii** [comment]
链接：http://pan.baidu.com/s/1boCEN3D 密码：9hrz
链接：http://pan.baidu.com/s/1mhYGWm0 密码：8akh

**Comment by LuckyQinn** [comment]
谢谢。
