### ISSUE TITLE
 running ./data/VOC0712/create_list.sh

### ISSUE THREAD

**Issue by RoseLii** [weiliu89/caffe#768]
please help me .
I download VOCtrainval_06-Nov-2007，but when i running ./data/VOC0712/create_list.sh have error that
y@y-System-Product-Name:~/2T/wangxingli/caffe$ ./data/VOC0712/create_list.sh
Create list for VOC2007 trainval...
cp: cannot stat '$/data/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt': No such file or directory
sed: can't read /home/y/2T/wangxingli/caffe/data/VOC0712/trainval_img.txt: No such file or directory
sed: can't read /home/y/2T/wangxingli/caffe/data/VOC0712/trainval_img.txt: No such file or directory
cp: cannot stat '$/data/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt': No such file or directory
sed: can't read /home/y/2T/wangxingli/caffe/data/VOC0712/trainval_label.txt: No such file or directory
sed: can't read /home/y/2T/wangxingli/caffe/data/VOC0712/trainval_label.txt: No such file or directory
paste: /home/y/2T/wangxingli/caffe/data/VOC0712/trainval_img.txt: No such file or directory
Create list for VOC2012 trainval...
cp: cannot stat '$/data/VOCdevkit/VOC2012/ImageSets/Main/trainval.txt': No such file or directory
sed: can't read /home/y/2T/wangxingli/caffe/data/VOC0712/trainval_img.txt: No such file or directory
sed: can't read /home/y/2T/wangxingli/caffe/data/VOC0712/trainval_img.txt: No such file or directory
cp: cannot stat '$/data/VOCdevkit/VOC2012/ImageSets/Main/trainval.txt': No such file or directory
sed: can't read /home/y/2T/wangxingli/caffe/data/VOC0712/trainval_label.txt: No such file or directory
sed: can't read /home/y/2T/wangxingli/caffe/data/VOC0712/trainval_label.txt: No such file or directory
paste: /home/y/2T/wangxingli/caffe/data/VOC0712/trainval_img.txt: No such file or directory
Create list for VOC2007 test...
cp: cannot stat '$/data/VOCdevkit/VOC2007/ImageSets/Main/test.txt': No such file or directory
sed: can't read /home/y/2T/wangxingli/caffe/data/VOC0712/test_img.txt: No such file or directory
sed: can't read /home/y/2T/wangxingli/caffe/data/VOC0712/test_img.txt: No such file or directory
cp: cannot stat '$/data/VOCdevkit/VOC2007/ImageSets/Main/test.txt': No such file or directory
sed: can't read /home/y/2T/wangxingli/caffe/data/VOC0712/test_label.txt: No such file or directory
sed: can't read /home/y/2T/wangxingli/caffe/data/VOC0712/test_label.txt: No such file or directory
paste: /home/y/2T/wangxingli/caffe/data/VOC0712/test_img.txt: No such file or directory
I1025 21:36:51.506589  1277 get_image_size.cpp:61] A total of 0 images.
Why is this wrong?

**Comment by skathi1991** [comment]
Any suggestion ? I have the same error! 

Create list for VOC2007 trainval...
cp: /test/Documents/VOCdevkit//VOC2007/ImageSets/Main/trainval.txt: No such file or directory
sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_img.txt'
sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_img.txt'
cp: /test/Documents/VOCdevkit//VOC2007/ImageSets/Main/trainval.txt: No such file or directory
sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_label.txt'
sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_label.txt'
paste: /Users/test/Documents/caffe-ssd/data/VOC0712/trainval_img.txt: No such file or directory
Create list for VOC2012 trainval...
cp: /test/Documents/VOCdevkit//VOC2012/ImageSets/Main/trainval.txt: No such file or directory
sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_img.txt'
sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_img.txt'
cp: /test/Documents/VOCdevkit//VOC2012/ImageSets/Main/trainval.txt: No such file or directory
sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_label.txt'
sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_label.txt'
paste: /Users/test/Documents/caffe-ssd/data/VOC0712/trainval_img.txt: No such file or directory
Create list for VOC2007 test...
cp: /test/Documents/VOCdevkit//VOC2007/ImageSets/Main/test.txt: No such file or directory
sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/test_img.txt'
sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/test_img.txt'
cp: /test/Documents/VOCdevkit//VOC2007/ImageSets/Main/test.txt: No such file or directory
sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/test_label.txt'
sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/test_label.txt'
paste: /Users/test/Documents/caffe-ssd/data/VOC0712/test_img.txt: No such file or directory
I1025 21:11:31.261265 3549418432 get_image_size.cpp:61] A total of 0 images.

**Comment by RoseLii** [comment]
@skathi1991 你的问题解决了吗

**Comment by 91Eric** [comment]
If you read creat_list.sh,You will find the the data should be putted in /home/username/data/..but not in /home/username/caffe/data/...   .one solution is :you can change root_dir=$HOME/data/VOCdevkit/ to root_dir=$HOME/caffe/data/VOCdevkit/ in creat_list.sh as well as creat_data.sh .Another is:put VOC datasheet in /home/username/data/  .

**Comment by ranjiewwen** [comment]
> Any suggestion ? I have the same error!
> 
> Create list for VOC2007 trainval...
> cp: /test/Documents/VOCdevkit//VOC2007/ImageSets/Main/trainval.txt: No such file or directory
> sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_img.txt'
> sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_img.txt'
> cp: /test/Documents/VOCdevkit//VOC2007/ImageSets/Main/trainval.txt: No such file or directory
> sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_label.txt'
> sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_label.txt'
> paste: /Users/test/Documents/caffe-ssd/data/VOC0712/trainval_img.txt: No such file or directory
> Create list for VOC2012 trainval...
> cp: /test/Documents/VOCdevkit//VOC2012/ImageSets/Main/trainval.txt: No such file or directory
> sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_img.txt'
> sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_img.txt'
> cp: /test/Documents/VOCdevkit//VOC2012/ImageSets/Main/trainval.txt: No such file or directory
> sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_label.txt'
> sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/trainval_label.txt'
> paste: /Users/test/Documents/caffe-ssd/data/VOC0712/trainval_img.txt: No such file or directory
> Create list for VOC2007 test...
> cp: /test/Documents/VOCdevkit//VOC2007/ImageSets/Main/test.txt: No such file or directory
> sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/test_img.txt'
> sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/test_img.txt'
> cp: /test/Documents/VOCdevkit//VOC2007/ImageSets/Main/test.txt: No such file or directory
> sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/test_label.txt'
> sed: 1: "/Users/test/Documents/c ...": undefined label 'est/Documents/caffe-ssd/data/VOC0712/test_label.txt'
> paste: /Users/test/Documents/caffe-ssd/data/VOC0712/test_img.txt: No such file or directory
> I1025 21:11:31.261265 3549418432 get_image_size.cpp:61] A total of 0 images.

i thinks you only have voc2012 datasets,but dont have voc207datasets

**Comment by FathiMahdi** [comment]
Hey, I have the same problem @RoseLii how you solve it
