### ISSUE TITLE
Is there any trick when use this to train Pedestrian Detection

### ISSUE THREAD

**Issue by lcj1105** [weiliu89/caffe#77]
I hope author can give some tips

**Comment by weiliu89** [comment]
What do you mean by 'trick'? You could just adapt the python script to design an pedestrian detector. Of course, different dataset might have their own characteristics, which you could explore a little bit. But I doubt that will be significant helpful. You could try to incorporate tricks that are particularly useful for pedestrian detection problem, which is out of the scope of this repository.

**Comment by kristellmarisse** [comment]
Annotate your pedestrian dataset to PASCALVOC format using this tool

https://github.com/tzutalin/labelImg

Then follow the steps mentioned in the home page to train your dataset and check the accuracy using this script .

https://github.com/weiliu89/caffe/blob/ssd/examples/ssd_detect.ipynb
