### ISSUE TITLE
 shape mismatch

### ISSUE THREAD

**Issue by RoseLii** [weiliu89/caffe#773]
please help me

Cannot copy param 0 weights from layer 'conv4_3_norm_mbox_conf'; shape mismatch.  Source param shape is 84 512 3 3 (387072); target param shape is 176 512 3 3 (811008). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
*** Check failure stack trace: ***
I have num_class=44

**Comment by zhaobaozi** [comment]
hi have you finish?
