### ISSUE TITLE
ERROR: ./data/VOC0712/create_list.sh

### ISSUE THREAD

**Issue by luowy1001** [weiliu89/caffe#779]
My system configuration:
Operating system: Ubuntu14.04 LTS
CUDA version : 7.5
CUDNN version : 5.0

I follow the tutorial to run the command `./data/VOC0712/create_list.sh`. I have a error:
```
ubuntu@INTERNET-16s-2:~/caffe-ssd$ ./data/VOC0712/create_list.sh
Create list for VOC2007 trainval...
Create list for VOC2012 trainval...
Create list for VOC2007 test...
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1105 21:26:46.171340 27748 get_image_size.cpp:110] This tool requires OpenCV; compile with USE_OPENCV.
*** Check failure stack trace: ***
./data/VOC0712/create_list.sh: line 6: 27748 Aborted                 (core dumped) $bash_dir/../../build/tools/get_image_size $root_dir $dst_file $bash_dir/$dataset"_name_size.txt"
```
But when I install caffe, I modified `Makefile.config` with `USE_OPENCV := 0` , `OPENCV_VERSION := 2.4.13`
Can you help me?
@weiliu89

**Comment by hardi-desai** [comment]
Hi! 
@luowy1001 
Can you please post solution to this issue? I have the same issue right now.

Thank you.

**Comment by hardi-desai** [comment]
I figured the solution. I had to modify Makefile.config with USE_OPENCV:=1 and OPENCV_VERSION.

**Comment by suyali** [comment]
Hello,I have the same issue:
$./data/VOC0712/create_list.sh

Create list for VOC2007 trainval...
Create list for VOC2012 trainval...
Create list for VOC2007 test...
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0723 17:11:38.821144 32303 get_image_size.cpp:110] This tool requires OpenCV; compile with USE_OPENCV.
*** Check failure stack trace: ***
./data/VOC0712/create_list.sh: 行 6: 32303 已放弃               (核心已转储) $bash_dir/../../build/tools/get_image_size $root_dir $dst_file $bash_dir/$dataset"_name_size.txt"

if I modify Makefile.config with USE_OPENCV:=1,whtn I run$ make -j8, it failed with 


..build_release/lib/libcaffe.so：对‘cv::String::allocate(unsigned long)’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::VideoWriter::write(cv::Mat const&)’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::getTextSize(cv::String const&, int, double, int, int*)’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::VideoCapture::open(cv::String const&)’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::VideoWriter::VideoWriter(cv::String const&, int, double, cv::Size_<int>, bool)’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::imread(cv::String const&, int)’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::VideoCapture::open(int)’未定义的引用
......

Do you know why? 
Thank you .

**Comment by 15966697671** [comment]
> I figured the solution. I had to modify Makefile.config with USE_OPENCV:=1 and OPENCV_VERSION.

I had to modify Makefile.config with USE_OPENCV:=1 and OPENCV_VERSION. But I didn't figure the solution.
