### ISSUE TITLE
Compile issue with cudnn v2

### ISSUE THREAD

**Issue by ByoenghakYim** [weiliu89/caffe#79]
Hi, I installed cudnn v2 and I'm trying to run this caffe on the Jetson TK1 board.

But there is an error at the beginning of the make compile time.

Is cudnn v2 incompatible with this caffe?

Thanks in advance.

**Comment by weiliu89** [comment]
The ssd branch is synced to the BVLC caffe, which dropped support for anything under cudnn v4. You could switch to cudnn v4 or v5.
