### ISSUE TITLE
The problem about prior_box?

### ISSUE THREAD

**Issue by 408550969** [weiliu89/caffe#796]
Can I tune SSD 512 in conv4_3 into smaller values to predict smaller targets?

**Comment by AndrewZhao** [comment]
yes, you can.

**Comment by 408550969** [comment]
Thanks,does it have any negative effects? Will it increase the amount of calculation? Will the error increase?

**Comment by 408550969** [comment]
What is the meaning of min_size and max_size? Why when min_size is 35.84, SSD  still can predict very small target .

**Comment by AndrewZhao** [comment]
In a certain feature map, the 6 or 4 3*3 convs represent bounding boxes range from min_size to max_size. you can see more details in prior box generation part.
The amount of calculation would not increase if you only change the min_size and max_size, bacause the number of prediction layers is same. For each feature point the conv kernal size is always 3*3.
SSD may have bbox smaller than min_size. this may be due to the last nms process.

**Comment by 408550969** [comment]
Thanks,does the reduction of min_size improve the precision of the small target? Or is there a better way to detect small targets?

**Comment by AndrewZhao** [comment]
the most halpful method is enlarge the input. For example, make the input from 300 to 500. 
you could also try to run DSSD or other methods claimed better for tiny objects.

**Comment by 408550969** [comment]
Now I turn the resolution into 768. Can you give me a specific proposal for the size of each layer of min_size and max_size? Thanks.

**Comment by AndrewZhao** [comment]
the min_size and max_size in each layer depend on yourself. The min_size and max_size is continous between each layer.
for example, the object size you want to detect is range from 100 to 500. then, you can change the smin to 100/768 and smax to 500/768. Use the function (4) in paper to calculate sk(k=feature layers taken part in detection). At last, min_size and max_size in k's feature layer is (sk-1) multiplies 768 and sk multiplies 768.

**Comment by 408550969** [comment]
Thank you very much

**Comment by AndrewZhao** [comment]
the prameter(min_size,max_size) in this repo is not same as the paper. don't care about it. change the prameter to fit you application is ok.
