### ISSUE TITLE
GPU crashed after running ssd_pascal.py on Ubuntu 14.04/TitanX

### ISSUE THREAD

**Issue by chenxistephen** [weiliu89/caffe#80]
I tried to run the ssd_pascal.py demo on Ubuntu 14.04 with TitanX GPU, CUDA 7.5 and NVdia driver 352.63, but the system will crashed (black screen) while loading the VGG model into GPU (at around 1GB memory) and the system will restart without any error messages. I tried different Ubuntu/CUDA/Nvidia driver versions (Ubuntu 16.04 with driver 361) but this still happens. Anyone has encountered such error and has any idea why this happens?  Thanks a lot!

**Comment by weiliu89** [comment]
I am using 361.62 (comes with cuda8.0 I believe), which seems fine.

**Comment by chenxistephen** [comment]
Thanks, I'll try to upgrade my driver. Do you also work on Ubuntu 14.04?
