### ISSUE TITLE
/usr/include/boost/property_tree/detail/json_parser_read.hpp:257:264: error: ‘type name’ declared as function returning an array

### ISSUE THREAD

**Issue by duanLH** [weiliu89/caffe#83]
I use GTX1080,cuda8.0, When I compile ssd ,the error is :
 /usr/include/boost/property_tree/detail/json_parser_read.hpp:257:264: error: ‘type name’ declared as function returning an array

But I compile caffe successfully
How to solve this problem?, I can not change the cuda version .
thanks

**Comment by weiliu89** [comment]
Other people have successfully compiled with gcc 5.3/5.4 + CUDA 8.0 according to #54.

**Comment by duanLH** [comment]
@weiliu89 thanks , it worked by changing the gcc to 5.3

**Comment by yonti** [comment]
我也是GTX1080,cuda8.0 ，如果用gcc4.8编译proto ，用5.3编译caffe时回报错，如果直接用gcc5.3 编译proto就过不去，怎么办阿？
