### ISSUE TITLE
detection_eval by Class

### ISSUE THREAD

**Issue by silvaphl** [weiliu89/caffe#835]
Hi,

is there a way to show the "detection_eval" by class?

I've been using SSD for a while, and until now it was fine to use just the "detection_eval", however, this is a metric for all classes. I want something that can be used to get the metric by class, in that way I will be able to focus my strength in the classes with the lowest results.

**Comment by Gesalat** [comment]
As you can read here #722 and here #330 (knowing that detection_eval is nothing else then mean average precision):
You should set `show_per_class_result: true` in the solver.
:)

**Comment by silvaphl** [comment]
Thanks @Gesalat
