### ISSUE TITLE
[Question] How to change size of Feature Maps

### ISSUE THREAD

**Issue by gachiemchiep** [weiliu89/caffe#838]
Hello @weiliu89 
At first thank you for your great software and contribution.

Current we are using SSD512 to detect our on our custom dataset. In most case it worked very well.
Because the dataset is quite simple so it acquire more than 90% of accuracy.
But in some case when the object is too long, the accuracy suddenly drop. The highest score is only about 40%.  

We believe the  (32x32 ,16x16, 8x8, 4x4, 2x2, 1x1) feature map is the main reason.
We want to change  (32x32 ,16x16, 8x8, 4x4, 2x2, 1x1) feature map into (16x32, 8x16, 4x8, 2x4, 1x2, 1x1). Do you know how can we make that?

Thank you for your time.

**Comment by borisgribkov** [comment]
If I understand you correctly you have problems in case of long (maybe high) objects, in this case I would play with an aspect ratio of prior_boxes. Second thing, original SSD detector uses square-like input (512x512), if your aspect ration is not square (for example 16:9) change the input of SSD according to your aspect ratio.

Regarding feature maps you asked, do you feature maps after Conv layers? you can change it if you change input dimensions of the detector from for example 512x512 to 256x512. Hope it helps

**Comment by gachiemchiep** [comment]
@borisgribkov 
thank you for comment.

yes, that's true. currently we have to deal with very long object.

    in this case I would play with an aspect ratio of prior_boxes

Sorry, i don't get your points. what is prior_boxes ?

     Second thing, original SSD detector uses square-like input (512x512), if your aspect ration is not square (for example 16:9) change the input of SSD according to your aspect ratio.     Regarding feature maps you asked, do you feature maps after Conv layers? you can change it if you change input dimensions of the detector from for example 512x512 to 256x512. Hope it helps

We are using this approach now. But thank you by the way.

Actually in author's source code, there is a method where he add layer for bounding box detections. 
This is where the feature maps (32x32, 16x16, ...) is generated. Do you know how to change this method ?

    def AddExtraLayers(net, use_batchnorm=True, lr_mult=1):
        use_relu = True
    
        # Add additional convolutional layers.
        # 32 x 32
        from_layer = net.keys()[-1]
    
        # TODO(weiliu89): Construct the name using the last layer to avoid duplication.
        # 16 x 16
        out_layer = "conv6_1"
        ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 256, 1, 0, 1,
            lr_mult=lr_mult)
    
        from_layer = out_layer
        out_layer = "conv6_2"
        ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 512, 3, 1, 2,
            lr_mult=lr_mult)
    
        # 8 x 8
        from_layer = out_layer
        out_layer = "conv7_1"
        ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 128, 1, 0, 1,
          lr_mult=lr_mult)
    
        from_layer = out_layer
        out_layer = "conv7_2"
        ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 256, 3, 1, 2,
          lr_mult=lr_mult)
    
        # 4 x 4
        from_layer = out_layer
        out_layer = "conv8_1"
        ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 128, 1, 0, 1,
          lr_mult=lr_mult)
    
        from_layer = out_layer
        out_layer = "conv8_2"
        ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 256, 3, 1, 2,
          lr_mult=lr_mult)
    
        # 2 x 2
        from_layer = out_layer
        out_layer = "conv9_1"
        ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 128, 1, 0, 1,
          lr_mult=lr_mult)
    
        from_layer = out_layer
        out_layer = "conv9_2"
        ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 256, 3, 1, 2,
          lr_mult=lr_mult)
    
        # 1 x 1
        from_layer = out_layer
        out_layer = "conv10_1"
        ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 128, 1, 0, 1,
          lr_mult=lr_mult)
    
        from_layer = out_layer
        out_layer = "conv10_2"
        ConvBNLayer(net, from_layer, out_layer, use_batchnorm, use_relu, 256, 4, 1, 1,
          lr_mult=lr_mult)
    
        return net

**Comment by borisgribkov** [comment]
Check this like: https://github.com/weiliu89/caffe/blob/4817bf8b4200b35ada8ed0dc378dceaf38c539e4/examples/ssd/ssd_pascal.py#L319

digit in brackets determines aspect ratio of prior boxes, now it could be 1 (it's default and not shown there), 2 and 3 (and 1/2 and 1/3 if "flip" it true, see line 327 ). If you have something very long with length / height ratio larger, for example 5 or 10, set 2 or 3 is not enough,  you should add 5 or 10 and so on. But retraining is needed after that

regarding feature maps ( 32x32... ), in the code above it's just for instance, because it depends on input resolution, so you could change input dims like we discussed before. You can check  feature map dims using ssd_net.blobs[  "layer_name"  ].data.shape. You will get output feature map dimensions, but it will be 4D or 3D tesnor, on of the dimensions relates to the number of kernels.

**Comment by gachiemchiep** [comment]
@borisgribkov . You're the best

Thank you for pointing it out.

I got it now. by default the flip option is set to true. So in the case of  [2, 3], from default bounding box 4 different bounding boxes will be cropped. And 1 more default bounding box is also selected. So at last a total 6 bounding box is cropped.

For visualization :Default bounding box

![image](https://user-images.githubusercontent.com/2300329/36296230-a293b934-132f-11e8-9b4e-75f1e60f23a1.png)

 5 new bounding box

![image](https://user-images.githubusercontent.com/2300329/36296239-abd79a10-132f-11e8-8998-545acf6e0afe.png)

![image](https://user-images.githubusercontent.com/2300329/36296413-858f7ba6-1330-11e8-9a27-a13080086582.png)

The size of the new cropped bounding box is actually multiple/ divide with the square root of aspect ratio values. So instead of 5 or 10, i will check the size of object in our dataset and find the correct value.

**Comment by borisgribkov** [comment]
If you have you test/train dataset, I guess you have, you can plot histogram of object dimensions and aspect ratios, maybe this helps a bit to understand what kinds of objects you have.

**Comment by gachiemchiep** [comment]
X    0.885964912281
	X    1.0500736377
	X    0.744220730798
	X    1.72413793103
	X    1.44238683128
	X    1.41771315268
	X    1.53296321999
	X    0.803907885555
	X    2.86666666667
	X    2.85859269283
	X    3.05595408895
	X    2.73441558442
	X    1.39127604167
	X    2.81800132363
	X    1.40448625181
	X    2.81972789116
	X    1.44103279833
	X    2.8635451505
	X    1.29072031149
	X    1.29072031149
	X    1.40326167532
	X    1.4301230992
	X    2.81722550953
	X    2.88941979522
	X    1.46882043576
	X    1.41554271034
	X    1.43633655994
	X    2.90928122819
	X    1.42583392477
	X    2.97664543524
	X    1.42063492063
	X    2.85828343313
	X    0.707509881423
	X    0.7
	X    0.6953125
	X    2.82465753425
	X    5.63387978142

For our dataset the ratio is as above. It range in inside range  [1/2, 2, 3, 8, 9]So we currently using the below setting.
The 32x32, 2x2, 1x1 feature maps is either too small or too large so we keep it as default. 
For 16x16, 8x8, 4x4 faeture maps we add new size.

    aspect_ratios = [[1/2, 2], [1/2, 2, 3, 8, 9], [1/2, 2, 3, 8, 9], [1/2, 2, 3, 8, 9], [1/2, 2, 3, 8, 9], [1/2, 2], [1/2, 2]]
    flip = False

**Comment by borisgribkov** [comment]
aspect_ratios = [[1/2, 2], [1/2, 2, 3, 8, 9], [1/2, 2, 3, 8, 9], [1/2, 2, 3, 8, 9], [1/2, 2, 3, 8, 9], [1/2, 2], [1/2, 2]]
according to this line, you did't modify 1st, 6st and 7st priorbox layers, in the beginning I would add [2, 3, 8, 9] everywhere. So it should be like this: [ [2, 3, 8, 9], [2, 3, 8, 9], [2, 3, 8, 9], [2, 3, 8, 9], [2, 3, 8, 9], [2, 3, 8, 9], [2, 3, 8, 9] ]. No need to add 1/2 (the same as 1/3, 1/8 and so on) there, in case of flip=True it will be created automatically.

**Comment by borisgribkov** [comment]
Maybe no need to add 8 and 9, because it's quite close, just try to add 9 first

**Comment by gachiemchiep** [comment]
@borisgribkov 
Thank you Boris. Your advice work great. It did boost our ssd performance a lot.

Hope this thread will help someone else.

**Comment by borisgribkov** [comment]
Happy to hear it, you are always welcome!
