### ISSUE TITLE
Train on RESNET

### ISSUE THREAD

**Issue by kristellmarisse** [weiliu89/caffe#84]
Is there any Resnet based implementation of SSD just like VGG16? Or has anyone succeeded in training SSD using RESNET based network?

**Comment by weiliu89** [comment]
I will try to include a demo python script on how to train with ResNet. So far, I couldn't observe any advantage of using ResNet 101 over the reduced VGG16 I used in the paper. It could be that I haven't made ResNet work in the optimal way.

**Comment by kristellmarisse** [comment]
Thank you. Just a humble request. Is it possible to add a ZF based network on SSD at some point in future like in py-faster-rcnn?

**Comment by weiliu89** [comment]
Sorry, I don't have plan to include ZF network. You could add it by yourself. Just refer to VGGNet definition. It should be straightforward.

**Comment by forever3000** [comment]
Hi @weiliu89 ,

It would be great if you can include the python script on how to train and test with ResNet-50.

Thanks

**Comment by kristellmarisse** [comment]
There is a ILSVRC2015 trained model on the home page which reports mAP of 46.4. Is there any Resent trained SSD model for ILSVRC or any comparisons of RESNET with VGG16 on ILSVRC dataset?

**Comment by kristellmarisse** [comment]
https://github.com/weiliu89/caffe/issues/92?_pjax=%23js-repo-pjax-container

**Comment by kristellmarisse** [comment]
https://github.com/weiliu89/caffe/issues/92
