### ISSUE TITLE
Finetuning error: "Creating layer conv14_2_mbox_conf_flat" --> "Check failed: std::equal(top_shape.begin() + 1, top_shape.begin() + 4, shape.begin() + 1) "

### ISSUE THREAD

**Issue by gombru** [weiliu89/caffe#840]
Hello,

I'm trying to fine-tune MobileNet SSD using a modified version of COCO. I have created the lmdb's of my modified COCO version using the given scripts. 
When I call train to start the finetuning, I get this error:

0209 12:37:34.576712 15523 layer_factory.hpp:77] Creating layer conv14_2_mbox_conf_flat F0209 12:37:34.581527 15545 annotated_data_layer.cpp:205] Check failed: std::equal(top_shape.begin() + 1, top_shape.begin() + 4, shape.begin() + 1)

Any idea about the reason? I'm not modifying the net architecture, so its weird.
Thanks!

**Comment by Li1991** [comment]
Hi, I have encountered the same problem with you. Can you tell me the reason and how to solve it? Thank you very much. @gombru @weiliu89

**Comment by ujsyehao** [comment]
The reason is coco dataset has some 1 or 4 channel images, the solution is to turn these images into 3 channels, you can use a script or add `force_color: true` in AnnotatedData layer.

**Comment by gombru** [comment]
True, I solved it but forgot to post it here, sorry. Closing
