### ISSUE TITLE
Visualizing net detection during training

### ISSUE THREAD

**Issue by raviv** [weiliu89/caffe#844]
Hi,

I'd like to visualize the network's detentions while training (once every few iterations)
Which blob contains the detected bboxes?
Please note that this is during training so the "detection_out" layer is not present.

Thanks.

**Comment by swcho84** [comment]
You can see the layer by modifying the deep-visualization-toolbox after finishing the learning step. (https://github.com/yosinski/deep-visualization-toolbox) 
However, it cannot see it while learning.

**Comment by raviv** [comment]
Thanks @swcho84 but the goal was to periodically evaluate the nets detection while training.
My solution was to load the network in test mode once every few iterations and use the 'detection_out' layer. 
This obviously slows down the overall training process but I think it's worth while if done sparsely.
