### ISSUE TITLE
About the bounding box offset for each class

### ISSUE THREAD

**Issue by yw155** [weiliu89/caffe#86]
Hi, @weiliu89 ,
I have a question that there is no need to train _K_ bounding box offsets corresponding to _K_ categories for each box? In the paper, I noticed that it only train one offset for whole classes on one box.
Thanks.

**Comment by weiliu89** [comment]
You are right. It is reflected in [this variable](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_pascal.py#L224).

**Comment by yw155** [comment]
Thank you.
