### ISSUE TITLE
Is it need to restrict the predicted localization values within [0, 1]?

### ISSUE THREAD

**Issue by yw155** [weiliu89/caffe#89]
Hi, @weiliu89 ,
In the calculating the localization loss of predicted box, the coordinates, height and width of default boxes and ground truth are normalized to [0, 1], thus I have a question that is it need to impose some restrictions on the outputs of the predicted box? According to my understanding, it is possible to output a negative value or a value exceed 1, is it correct? Or these two cases are accepted by smooth L1 loss?

**Comment by weiliu89** [comment]
You don't have to impose the restriction during training. Wouldn't any detection methods have the same issue? During testing time, I did "clip" the output so that it is within [0, 1], which should be slightly better for evaluation purpose (mAP).

**Comment by yw155** [comment]
Before I have not noticed these details. Thanks for your explanations.
