### ISSUE TITLE
The resnet feature dimension problem

### ISSUE THREAD

**Issue by jiamingNo1** [weiliu89/caffe#892]
in file ssd_pascal_resnet.py, line 252, you say that the res3b3_relu dimension is 38x38, but why the res5c_relu is 19x19, isn't it 10x10, after all, there is a res4 layer in the middle.

**Comment by jiamingNo1** [comment]
I know there is a dilation conv5, but can the caffe model use the changed prototxt?

**Comment by jiamingNo1** [comment]
I solved this problem, thx.

**Comment by TheodoreG** [comment]
> I solved this problem, thx.

Could you please explain the reason for me?

**Comment by jiamingNo1** [comment]
> > I solved this problem, thx.
> 
> Could you please explain the reason for me?

you can see the line 382,ResNet101Body(net, from_layer='data', use_pool5=False, use_dilation_conv5=True)
then turn to python/caffe/model_libs feel the function.
