### ISSUE TITLE
What does min_size and max_size mean?

### ISSUE THREAD

**Issue by 408550969** [weiliu89/caffe#918]
Hello, I have some issues about the priorbox
When priorbox layer is generated, what does min_size and max_size mean?
And what is  the width and length of the priorbox when aspect_ratio is 2 if the layer is conv4_3_norm_mbox_priorbox(min_size 30,max_size 60)?

**Comment by eng100200** [comment]
@408550969  hello did you get the answer of your question?

**Comment by 408550969** [comment]
You can see the narrative in the paper near Formula 4.
