### ISSUE TITLE
what does s1 and s2 means?

### ISSUE THREAD

**Issue by isalirezag** [weiliu89/caffe#924]
In the papers it says:
'subsample parameters from fc6 and fc7, changepool5 from2×2−s2to3×3−s1'
Can you please tell me what does it mean by s1 and s2?

also we can see `3x3x512-s2` and `3x3x256-s1` in the following figure
![image](https://user-images.githubusercontent.com/12434910/43351282-9f15c68a-91dd-11e8-97bb-fb7152369471.png)

**Comment by fraukej** [comment]
It means the convolutional parameter `stride`. `s1` means `stride = 1` and `s2` means `stride = 2`.

**Comment by isalirezag** [comment]
Thanks
