### ISSUE TITLE
Subset person VOC

### ISSUE THREAD

**Issue by Steffgroe** [weiliu89/caffe#954]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
I want to train SSD on a subset of pascal VOC. I tried to subset VOC by changing the classes in labelmap_voc_prototxt to:

item {
  name: "none_of_the_above"
  label: 0
  display_name: "background"
}
item {
  name: "person"
  label: 1
  display_name: "person"
}

When I try to run ./data/VOC0712/create_data.sh it gives errors related to classes I removed.
How can I subset VOC properly?
### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by Mycenae** [comment]
I just finished some scripts for extracting subsets of pascal voc, converting subsets of coco datasets to pascal format and creating related txts.
