### ISSUE TITLE
how to improve CPU detection speed?

### ISSUE THREAD

**Issue by linquanxu** [weiliu89/caffe#960]
hi，when i used ssd300(VGG) to train a model and detected objects with CPU, the inference time is very slow which is 1.5s. how to improve it？
thanks.

### Your system configuration
Operating system: ubuntu 16.04
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS: open
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by matt-ny** [comment]
Try using Intel MKL instead of OpenBLAS, and perhaps try Intel Caffe https://github.com/intel/caffe

**Comment by linquanxu** [comment]
@matt-ny thank you very much, I will try it.
