### ISSUE TITLE
why not use 1*1 conv in convolutional classifier?

### ISSUE THREAD

**Issue by blateyang** [weiliu89/caffe#975]
Hi，wei @weiliu89 : 
    I have a question when reading the paper. As shown in the picture, 3\*3 conv is used in convolutional classifier. Why not use 1*1 conv which can also merge feature maps and have less parameters in convolutional classifier? Wish to your reply!

![tmp](https://user-images.githubusercontent.com/26182129/54067808-c54dc980-427f-11e9-8ae7-545312bfeb8b.GIF)

**Comment by ujsyehao** [comment]
I guess 3x3 conv has a big receptive field.

**Comment by blateyang** [comment]
Thanks for your reply!@ujsyehao your reply may be the reason. And I found that I got a wrong place to ask this question about SSD. I will close this issue.
