### ISSUE TITLE
tools/get_image_size.cpp ERROR

### ISSUE THREAD

**Issue by John-HW-Cao** [weiliu89/caffe#99]
I am trying to follow the tutorial. But I have the following:

caowendong@Media:~/caffe-ssd> ./data/VOC0712/create_list.sh 
Create list for VOC2007 trainval...
Create list for VOC2012 trainval...
/home/caowendong/caffe-ssd/data/VOC0712
Create list for VOC2007 test...
/home/caowendong/caffe-ssd/data/VOC0712
test
/home/caowendong/caffe-ssd/data/VOC0712/test.txt
/home/caowendong/data/VOCdevkit/
I0811 15:39:58.097544 21543 get_image_size.cpp:61] A total of 4952 images.
I0811 15:39:58.097836 21543 get_image_size.cpp:65] 
I0811 15:39:58.097889 21543 get_image_size.cpp:85] /home/caowendong/data/VOCdevkit//home/caowendong/caffe-ssd/data/VOC0712/test_name_size.txt
I0811 15:39:58.097913 21543 get_image_size.cpp:93] /home/caowendong/data/VOCdevkit/VOC2007/JPEGImages/000001.jpg
/home/caowendong/caffe-ssd/data/VOC0712/../../build/tools/get_image_size: symbol lookup error: /home/caowendong/caffe-ssd/data/VOC0712/../../build/tools/get_image_size: undefined symbol: _ZN5caffe12GetImageSizeERKSsPiS2_

From the message above, I can determine that the undefined symbol comes from this line in tools/get_image_size.cpp

`GetImageSize(img_file.string(), &height, &width);`

Could anyone please help me on this problem?

**Comment by weiliu89** [comment]
You can try `make clean` and then make everything again.

**Comment by John-HW-Cao** [comment]
OK. The problem is solved. Thank you very much~
